// Module: Bağlaçlar & Akıcılık (linking words, conjunctions, discourse markers)
window.EA_MODULES = window.EA_MODULES || [];
window.EA_MODULES.push({
  id: "connectors",
  title: "Bağlaçlar & Akıcılık",
  icon: "🔗",
  color: "#2ecc71",
  description: "Bağlaçlar, bağlantı sözcükleri ve konuşma işaretleri: fikirleri hem konuşmada hem yazıda akıcı ve doğal biçimde birbirine bağlamayı öğren.",
  units: [
    // ───────────────────────── WEEK 1 ─────────────────────────
    {
      id: "connectors-01",
      title: "Ekleme: and, also, moreover…",
      level: "B1+",
      week: 1,
      intro: {
        tr: "Bir fikre yeni bilgi eklemek için farklı bağlaçlar kullanırız. 'and, also, too, as well' günlük konuşmada; 'in addition, moreover, furthermore' daha resmi yazıda; 'besides, what's more' ise konuşmada ikna etmek için kullanılır. Bağlacın cümledeki yeri ve noktalaması önemlidir.",
        points: [
          "also → genelde fiilden önce, 'be' fiilinden sonra: We also offer… / It is also…",
          "too / as well → cümle sonunda: We offer installation too / as well.",
          "In addition, / Moreover, / Furthermore, → cümle başında + virgül (resmi).",
          "in addition to + isim / -ing: In addition to glass, we supply frames.",
          "Besides, / What's more, → konuşmada ek argüman; 'besides' = 'zaten, hem de'."
        ],
        examples: [
          { en: "Our glass is strong. Moreover, it is very light.", tr: "Camımız sağlam. Üstelik çok hafif." },
          { en: "We also provide on-site installation.", tr: "Yerinde montaj da sağlıyoruz." },
          { en: "I like hiking, and I enjoy swimming as well.", tr: "Yürüyüşü severim, yüzmeyi de severim." },
          { en: "In addition to the windows, they ordered two portholes.", tr: "Pencerelere ek olarak iki lomboz da sipariş ettiler." }
        ]
      },
      cards: [
        { en: "and", tr: "ve", ex: "We cut and temper the glass in our own factory." },
        { en: "also", tr: "ayrıca, de/da", ex: "We also offer a five-year warranty." },
        { en: "too", tr: "de/da (cümle sonu)", ex: "I'm from Istanbul too." },
        { en: "as well", tr: "de/da (cümle sonu)", ex: "Could you send the invoice as well?" },
        { en: "in addition", tr: "buna ek olarak", ex: "In addition, all panes are tested before shipping." },
        { en: "in addition to", tr: "…e ek olarak (+isim/-ing)", ex: "In addition to tempering, we offer laminating." },
        { en: "moreover", tr: "üstelik, dahası (resmi)", ex: "The price is fair. Moreover, delivery is free." },
        { en: "furthermore", tr: "ayrıca, bunun yanı sıra (resmi)", ex: "Furthermore, the glass meets IMO standards." },
        { en: "besides", tr: "hem de, zaten, üstelik", ex: "It's too late to go out. Besides, I'm tired." },
        { en: "what's more", tr: "dahası, üstüne üstlük (konuşma)", ex: "It's cheap, and what's more, it's really good." }
      ],
      exercises: [
        { type: "mcq", q: "We supply tempered glass. We ___ supply laminated glass.",
          options: ["too", "as well", "also", "what's more"], answer: 2,
          explain: "'also' fiilden önce gelir; 'too' ve 'as well' cümle sonunda olur; 'what's more' cümle başında kullanılır." },
        { type: "mcq", q: "I've been to London, and I've been to Paris ___.",
          options: ["too", "moreover", "either", "in addition to"], answer: 0,
          explain: "Olumlu cümle sonunda 'too' veya 'as well' kullanılır; 'either' yalnızca olumsuz cümlede gelir." },
        { type: "fill", q: "___ to the windows, the shipyard ordered ten portholes.",
          answers: ["In addition"], hint: "iki kelime, + to",
          explain: "'In addition to + isim' = …e ek olarak." },
        { type: "mcq", q: "The glass passed every test. ___, it was delivered ahead of schedule.",
          options: ["Also to", "Too", "As well", "Furthermore"], answer: 3,
          explain: "Cümle başında resmi ekleme: 'Furthermore,' + virgül." },
        { type: "order", answer: "We also offer free technical support.",
          alts: ["Also, we offer free technical support."],
          tr: "Ücretsiz teknik destek de sunuyoruz.",
          explain: "'also' ana fiilin (offer) önüne gelir." },
        { type: "match", pairs: [["moreover", "üstelik (resmi)"], ["as well", "de/da (cümle sonu)"], ["besides", "hem de, zaten"], ["in addition to", "…e ek olarak"], ["what's more", "dahası (konuşma)"]],
          explain: "Ekleme bağlaçlarının Türkçe karşılıkları." },
        { type: "fill", q: "Can I have a coffee? And a glass of water as ___, please.",
          answers: ["well"], explain: "'as well' = de/da, cümle sonunda." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["In addition to offer a discount, we pay for shipping.", "In addition to offering a discount, we pay for shipping.", "In addition offering a discount, we pay for shipping.", "In addition of offering a discount, we pay for shipping."], answer: 1,
          explain: "'in addition to' sonrası isim veya -ing gelir; 'to' burada edattır." },
        { type: "listen", text: "Moreover, the glass is certified for marine use.",
          tr: "Üstelik cam denizcilik kullanımı için sertifikalıdır." },
        { type: "mcq", q: "\"Let's not go to that restaurant. It's expensive. ___, the food isn't great.\"",
          options: ["Too", "Also to", "As well", "Besides"], answer: 3,
          explain: "Konuşmada ek bir gerekçe sunmak için 'Besides,' kullanılır." },
        { type: "order", answer: "The panes are light, and what's more, they are cheap.",
          tr: "Levhalar hafif, üstelik ucuzlar.",
          explain: "'what's more' konuşmada ek ve güçlü bir argüman ekler." },
        { type: "fill", q: "She speaks English and Turkish. She ___ speaks a little Greek.",
          answers: ["also"], hint: "de/da anlamında, fiilden önce",
          explain: "Fiilden önce 'also'." },
        { type: "listen", text: "I love cooking, and my wife does too.",
          tr: "Yemek yapmayı severim, eşim de sever." }
      ]
    },
    {
      id: "connectors-02",
      title: "Zıtlık I: but, although, however",
      level: "B1+",
      week: 1,
      intro: {
        tr: "Zıt fikirleri bağlamak için 'but' en temel bağlaçtır. 'although / though / even though' bir yan cümle başlatır (özne + fiil). 'However' ise yeni bir cümle başlatır ve virgülle ayrılır. 'while' iki şeyi karşılaştırırken kullanılır.",
        points: [
          "but → iki cümleyi ortadan bağlar: The price is high, but the quality is excellent.",
          "although / even though + özne + fiil (cümle başında veya ortada). 'even though' daha güçlüdür.",
          "though → konuşmada cümle sonunda da gelir: It's expensive. It's good, though.",
          "However, → yeni cümle başında + virgül: ... . However, ...  (iki cümleyi virgülle bağlayamaz!)",
          "while → karşılaştırma: I prefer tea, while my wife prefers coffee.",
          "Although ile 'but' aynı cümlede birlikte KULLANILMAZ."
        ],
        examples: [
          { en: "Although the order was late, the customer was satisfied.", tr: "Sipariş gecikmiş olsa da müşteri memnundu." },
          { en: "The glass is expensive. However, it lasts much longer.", tr: "Cam pahalı. Ancak çok daha uzun ömürlü." },
          { en: "Even though it was raining, we went for a walk.", tr: "Yağmur yağıyor olmasına rağmen yürüyüşe çıktık." },
          { en: "Nice hotel. A bit noisy, though.", tr: "Güzel otel. Biraz gürültülü ama." }
        ]
      },
      cards: [
        { en: "but", tr: "ama, fakat", ex: "The price is good, but the delivery time is long." },
        { en: "although", tr: "-e rağmen, -se de", ex: "Although we tried hard, we missed the deadline." },
        { en: "though", tr: "gerçi, yine de (cümle sonu: ama)", ex: "It was a long trip. I enjoyed it, though." },
        { en: "even though", tr: "-diği halde, -mesine rağmen (güçlü)", ex: "Even though I was tired, I finished the report." },
        { en: "however", tr: "ancak, bununla birlikte", ex: "The sample is fine. However, the edges need polishing." },
        { en: "while", tr: "-iken, oysa (karşılaştırma)", ex: "Our old supplier was cheap, while you are more reliable." },
        { en: "yet", tr: "ama yine de", ex: "The glass is thin, yet very strong." },
        { en: "still", tr: "yine de", ex: "It was expensive. Still, it was worth it." }
      ],
      exercises: [
        { type: "mcq", q: "___ the shipment was delayed, the client didn't complain.",
          options: ["However", "But", "Although", "Despite"], answer: 2,
          explain: "Özne + fiil içeren yan cümle → 'Although'. 'Despite' isimle kullanılır." },
        { type: "mcq", q: "The price is a bit high. ___, the quality is excellent.",
          options: ["However", "Although", "Even though", "While"], answer: 0,
          explain: "Yeni cümle başında + virgül → 'However,'." },
        { type: "fill", q: "I like the design, ___ the colour is too dark.",
          answers: ["but", "although", "though"], explain: "İki cümleyi ortadan bağlayan basit zıtlık: 'but'." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["Although it was late, but we kept working.", "Although it was late, we kept working.", "However it was late, we kept working.", "It was late, however we kept working."], answer: 1,
          explain: "'Although' ile 'but' birlikte kullanılmaz; 'however' iki cümleyi virgülle bağlayamaz." },
        { type: "order", answer: "Even though we were busy, we answered every email.",
          tr: "Meşgul olmamıza rağmen her e-postayı yanıtladık.",
          explain: "'Even though + cümle', ardından virgül ve ana cümle." },
        { type: "match", pairs: [["but", "ama"], ["although", "-e rağmen"], ["however", "ancak (yeni cümle)"], ["while", "oysa (karşılaştırma)"], ["though", "ama (cümle sonu, konuşma)"]],
          explain: "Zıtlık bağlaçlarının anlamları ve kullanımları." },
        { type: "fill", q: "The hotel was lovely. The breakfast wasn't great, ___.",
          answers: ["though"], hint: "cümle sonu, konuşma",
          explain: "Konuşmada cümle sonunda 'though' = ama." },
        { type: "mcq", q: "My brother loves football, ___ I prefer basketball.",
          options: ["however", "although of", "despite", "while"], answer: 3,
          explain: "İki kişiyi karşılaştırırken 'while' kullanılır." },
        { type: "listen", text: "Although the glass is thin, it is very strong.",
          tr: "Cam ince olmasına rağmen çok sağlamdır." },
        { type: "fill", q: "___ though I had studied a lot, the exam was hard.",
          answers: ["Even"], explain: "'Even though' güçlü zıtlık bildirir." },
        { type: "order", answer: "The sample looks good. However, the edges are rough.",
          tr: "Numune iyi görünüyor. Ancak kenarları pürüzlü.",
          explain: "'However' yeni cümle başlatır ve virgül alır." },
        { type: "mcq", q: "\"Did you like the film?\" — \"Yes, it was a bit long, ___.\"",
          options: ["though", "even though", "although", "despite"], answer: 0,
          explain: "Cümle sonunda 'ama' anlamında en doğal seçenek 'though'." },
        { type: "listen", text: "We missed the deadline, but the customer understood.",
          tr: "Son tarihi kaçırdık ama müşteri anlayışla karşıladı." }
      ]
    },
    // ───────────────────────── WEEK 2 ─────────────────────────
    {
      id: "connectors-03",
      title: "Zıtlık II: despite, whereas, nevertheless",
      level: "B1+",
      week: 2,
      intro: {
        tr: "Türklerin en sık yaptığı hatalardan biri 'despite' ile 'although'u karıştırmaktır. 'Despite / in spite of' arkasından İSİM veya -ING alır; 'although' arkasından CÜMLE (özne + fiil) alır. 'Whereas' iki şeyi resmi olarak karşılaştırır. 'Nevertheless / nonetheless' 'yine de' anlamında cümle başında kullanılır.",
        points: [
          "despite / in spite of + isim / -ing: Despite the delay… / Despite being late…",
          "despite the fact that + cümle (= although).",
          "'despite of' YANLIŞ; 'in spite of' veya 'despite' doğru.",
          "whereas → resmi karşılaştırma: Type A is tempered, whereas Type B is laminated.",
          "Nevertheless, / Nonetheless, → yine de (resmi), yeni cümle + virgül.",
          "On the one hand… On the other hand… → iki tarafı tartmak."
        ],
        examples: [
          { en: "Despite the storm, the vessel arrived on time.", tr: "Fırtınaya rağmen gemi zamanında vardı." },
          { en: "In spite of having a cold, she came to the meeting.", tr: "Soğuk algınlığı olmasına rağmen toplantıya geldi." },
          { en: "Laminated glass holds together when broken, whereas ordinary glass shatters.", tr: "Lamine cam kırıldığında bir arada kalır, oysa normal cam paramparça olur." },
          { en: "The test was difficult. Nevertheless, our glass passed.", tr: "Test zordu. Yine de camımız geçti." }
        ]
      },
      cards: [
        { en: "despite", tr: "-e rağmen (+isim/-ing)", ex: "Despite the high price, they placed the order." },
        { en: "in spite of", tr: "-e rağmen (+isim/-ing)", ex: "In spite of the traffic, we arrived early." },
        { en: "despite the fact that", tr: "…olmasına rağmen (+cümle)", ex: "Despite the fact that it rained, we had fun." },
        { en: "whereas", tr: "oysa, -diği halde (karşılaştırma)", ex: "We use 10 mm glass, whereas they use 8 mm." },
        { en: "nevertheless", tr: "yine de, buna rağmen", ex: "It was risky. Nevertheless, we accepted the order." },
        { en: "nonetheless", tr: "yine de (resmi)", ex: "The results were mixed. Nonetheless, we are optimistic." },
        { en: "on the other hand", tr: "öte yandan", ex: "Steel is strong. On the other hand, it's heavy." },
        { en: "on the one hand", tr: "bir yandan", ex: "On the one hand, the job pays well." },
        { en: "even so", tr: "öyle bile olsa", ex: "The hotel was full. Even so, they found us a room." }
      ],
      exercises: [
        { type: "mcq", q: "___ the delay, the customer placed another order.",
          options: ["Although", "Even though", "Despite", "Whereas"], answer: 2,
          explain: "Arkasından isim (the delay) geldiği için 'Despite'." },
        { type: "mcq", q: "___ it was expensive, we bought the tickets.",
          options: ["In spite of", "Although", "Despite", "Nevertheless"], answer: 1,
          explain: "Arkasından cümle (it was expensive) geldiği için 'Although'." },
        { type: "fill", q: "In ___ of the bad weather, the shipment left on time.",
          answers: ["spite"], explain: "'in spite of + isim' = -e rağmen." },
        { type: "mcq", q: "Which is correct?",
          options: ["Despite of the cost, we chose it.", "Despite the cost was high, we chose it.", "Despite the cost, we chose it.", "In spite the cost, we chose it."], answer: 2,
          explain: "'despite' + isim; 'despite of' ve 'in spite' (of olmadan) yanlış." },
        { type: "fill", q: "Despite ___ (work) late every night, he never felt tired.",
          answers: ["working"], explain: "'despite' sonrası fiil -ing alır." },
        { type: "order", answer: "Despite the high price, they placed a large order.",
          tr: "Yüksek fiyata rağmen büyük bir sipariş verdiler.",
          explain: "'Despite + isim öbeği', virgül, ana cümle." },
        { type: "mcq", q: "Tempered glass breaks into small pieces, ___ laminated glass stays in one piece.",
          options: ["whereas", "despite", "nevertheless", "in spite of"], answer: 0,
          explain: "İki türü karşılaştıran bağlaç: 'whereas'." },
        { type: "match", pairs: [["despite", "+ isim / -ing"], ["although", "+ özne + fiil"], ["nevertheless", "yine de (yeni cümle)"], ["whereas", "oysa (karşılaştırma)"], ["on the other hand", "öte yandan"]],
          explain: "Bağlacın arkasından ne geldiğini ve anlamını eşleştir." },
        { type: "listen", text: "In spite of the rain, we enjoyed the picnic.",
          tr: "Yağmura rağmen pikniğin tadını çıkardık." },
        { type: "mcq", q: "The flat is small. ___, it's very close to the city centre.",
          options: ["Whereas", "Despite", "Although", "On the other hand"], answer: 3,
          explain: "Yeni cümle başında karşı tarafı göstermek: 'On the other hand,'." },
        { type: "order", answer: "The test was hard. Nevertheless, our glass passed it.",
          tr: "Test zordu. Yine de camımız testi geçti.",
          explain: "'Nevertheless' yeni cümle başında, virgülle." },
        { type: "fill", q: "Despite the fact ___ the glass was thin, it passed the impact test.",
          answers: ["that"], explain: "'despite the fact that + cümle'." },
        { type: "listen", text: "The results were mixed. Nonetheless, we are optimistic.",
          tr: "Sonuçlar karışıktı. Yine de iyimseriz." }
      ]
    },
    {
      id: "connectors-04",
      title: "Sebep: because, since, due to…",
      level: "B1+",
      week: 2,
      intro: {
        tr: "Sebep bildirirken iki grup vardır: 'because, since, as' arkasından CÜMLE alır; 'because of, due to, owing to, thanks to' arkasından İSİM alır. 'Since' ve 'as' genelde bilinen bir sebebi belirtir ve cümle başında sık kullanılır. 'Thanks to' olumlu bir sonucun sebebidir.",
        points: [
          "because / since / as + özne + fiil: Since you are here, let's start.",
          "because of / due to / owing to + isim: The delay was due to a strike.",
          "'due to' resmidir ve 'be' fiilinden sonra rahat kullanılır: The delay is due to…",
          "thanks to → olumlu sebep (bazen ironik): Thanks to your help, we finished on time.",
          "Cümle başında 'Because…' yazıda tek başına bırakılmaz; ana cümle gelmeli."
        ],
        examples: [
          { en: "We couldn't load the glass because the crane was broken.", tr: "Vinç bozuk olduğu için camı yükleyemedik." },
          { en: "The shipment was delayed due to bad weather.", tr: "Sevkiyat kötü hava nedeniyle gecikti." },
          { en: "As it's your birthday, dinner is on me.", tr: "Doğum günün olduğu için yemek benden." },
          { en: "Thanks to the new furnace, production is faster.", tr: "Yeni fırın sayesinde üretim daha hızlı." }
        ]
      },
      cards: [
        { en: "because", tr: "çünkü, -diği için (+cümle)", ex: "We chose them because they are reliable." },
        { en: "because of", tr: "…yüzünden, …nedeniyle (+isim)", ex: "We were late because of the traffic." },
        { en: "since", tr: "-diği için, madem (bilinen sebep)", ex: "Since you're busy, I'll call later." },
        { en: "as", tr: "-diği için", ex: "As the port was closed, the ship waited." },
        { en: "due to", tr: "…nedeniyle (resmi, +isim)", ex: "The delay was due to a technical problem." },
        { en: "owing to", tr: "…yüzünden (resmi, +isim)", ex: "Owing to high demand, prices have risen." },
        { en: "thanks to", tr: "…sayesinde", ex: "Thanks to your quick reply, we met the deadline." },
        { en: "the reason why", tr: "…nedeni", ex: "The reason why I'm calling is the invoice." },
        { en: "on account of", tr: "…yüzünden (resmi)", ex: "The meeting was cancelled on account of the strike." }
      ],
      exercises: [
        { type: "mcq", q: "The ship was delayed ___ the storm.",
          options: ["because", "because of", "since", "as"], answer: 1,
          explain: "Arkasından isim (the storm) → 'because of'." },
        { type: "mcq", q: "We stayed at home ___ it was raining.",
          options: ["because of", "due to", "owing to", "because"], answer: 3,
          explain: "Arkasından cümle (it was raining) → 'because'." },
        { type: "fill", q: "The delay was ___ to a problem at the port.",
          answers: ["due"], explain: "'be due to + isim' = …den kaynaklanmak." },
        { type: "mcq", q: "___ your help, we finished the project early.",
          options: ["Since", "Because", "Thanks to", "As"], answer: 2,
          explain: "Olumlu sonuç + isim → 'Thanks to'." },
        { type: "order", answer: "Since you are here, let's start the meeting.",
          tr: "Madem buradasın, toplantıya başlayalım.",
          explain: "'Since' cümle başında bilinen sebep bildirir." },
        { type: "match", pairs: [["because", "+ cümle"], ["because of", "+ isim (genel)"], ["thanks to", "…sayesinde"], ["owing to", "…yüzünden (resmi)"], ["since", "madem, -diği için"]],
          explain: "Sebep bağlaçları ve arkalarından gelen yapı." },
        { type: "fill", q: "I'm tired ___ I didn't sleep well last night.",
          answers: ["because", "as", "since"], explain: "Arkasından cümle geldiği için because / as / since." },
        { type: "mcq", q: "___ high demand, delivery times are now eight weeks.",
          options: ["Owing to", "Because", "Since", "As"], answer: 0,
          explain: "'high demand' isim öbeği → 'Owing to'." },
        { type: "listen", text: "We couldn't ship the glass because of the strike.",
          tr: "Grev yüzünden camı sevk edemedik." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["Because of the crane was broken, we waited.", "As the crane was broken, we waited.", "Due to the crane was broken, we waited.", "Owing to the crane was broken, we waited."], answer: 1,
          explain: "'the crane was broken' bir cümle → 'As'. Diğerleri isim ister." },
        { type: "order", answer: "The order was cancelled due to a pricing error.",
          tr: "Sipariş bir fiyatlandırma hatası nedeniyle iptal edildi.",
          explain: "'due to + isim öbeği'." },
        { type: "listen", text: "As it's your birthday, dinner is on me.",
          tr: "Doğum günün olduğu için yemek benden." }
      ]
    },
    // ───────────────────────── WEEK 3 ─────────────────────────
    {
      id: "connectors-05",
      title: "Sonuç: so, therefore, as a result…",
      level: "B2",
      week: 3,
      intro: {
        tr: "Sonuç bildiren bağlaçlar, bir olayın ne doğurduğunu gösterir. 'so' konuşmada en yaygın olanıdır ve iki cümleyi virgülle bağlar. 'Therefore, as a result, consequently' daha resmidir ve genellikle yeni cümle başlatır. 'so + sıfat + that' ve 'such + (a) + sıfat + isim + that' yapıları 'o kadar … ki' anlamı verir.",
        points: [
          "so → , so + cümle: The crane broke, so we couldn't load the ship.",
          "Therefore, / As a result, / Consequently, → yeni cümle başında + virgül (resmi).",
          "therefore cümle içinde de olabilir: We were, therefore, unable to ship.",
          "thus / hence → çok resmi; 'hence' çoğu zaman isimle: hence the delay.",
          "so + sıfat/zarf + that: It was so heavy that we needed a crane.",
          "such + a + sıfat + tekil isim + that: It was such a good offer that we accepted."
        ],
        examples: [
          { en: "The port was closed, so the ship waited outside.", tr: "Liman kapalıydı, bu yüzden gemi dışarıda bekledi." },
          { en: "The furnace broke down. As a result, production stopped for two days.", tr: "Fırın bozuldu. Sonuç olarak üretim iki gün durdu." },
          { en: "The film was so boring that I fell asleep.", tr: "Film o kadar sıkıcıydı ki uyuyakaldım." },
          { en: "It was such a nice day that we had lunch outside.", tr: "O kadar güzel bir gündü ki öğle yemeğini dışarıda yedik." }
        ]
      },
      cards: [
        { en: "so", tr: "bu yüzden, o yüzden", ex: "It was late, so we took a taxi." },
        { en: "therefore", tr: "bu nedenle (resmi)", ex: "The glass failed the test. Therefore, we rejected the batch." },
        { en: "as a result", tr: "sonuç olarak", ex: "As a result, the delivery was two weeks late." },
        { en: "consequently", tr: "dolayısıyla (resmi)", ex: "Prices rose. Consequently, sales fell." },
        { en: "thus", tr: "böylece, bu şekilde (çok resmi)", ex: "The panes are thicker, thus offering better insulation." },
        { en: "hence", tr: "bu yüzden, …den dolayı (çok resmi)", ex: "The materials arrived late; hence the delay." },
        { en: "so … that", tr: "o kadar … ki", ex: "The order was so big that we hired extra staff." },
        { en: "such … that", tr: "öyle bir … ki", ex: "It was such a long meeting that I missed lunch." },
        { en: "that's why", tr: "işte bu yüzden (konuşma)", ex: "I missed the bus. That's why I'm late." }
      ],
      exercises: [
        { type: "mcq", q: "The customer needed the glass urgently, ___ we sent it by air.",
          options: ["as a result of", "therefore", "because", "so"], answer: 3,
          explain: "Virgülden sonra iki cümleyi bağlayan sonuç bağlacı: 'so'. 'therefore' virgülle cümle bağlayamaz." },
        { type: "mcq", q: "The batch failed the impact test. ___, it was not shipped.",
          options: ["Therefore", "So that", "Because", "Due to"], answer: 0,
          explain: "Yeni cümle başında resmi sonuç → 'Therefore,'." },
        { type: "fill", q: "It was ___ a heavy pane that four people had to lift it.",
          answers: ["such"], explain: "such + a + sıfat + isim + that." },
        { type: "fill", q: "The glass was ___ thick that we needed a special saw.",
          answers: ["so"], explain: "so + sıfat + that." },
        { type: "mcq", q: "Choose the correct sentence.",
          options: ["It was so a good offer that we accepted.", "It was such good offer that we accepted.", "It was such a good offer that we accepted.", "It was so good an offer what we accepted."], answer: 2,
          explain: "'such a + sıfat + tekil isim + that'." },
        { type: "order", answer: "The port was closed. As a result, the ship waited.",
          tr: "Liman kapalıydı. Sonuç olarak gemi bekledi.",
          explain: "'As a result,' yeni cümle başında, virgülle." },
        { type: "match", pairs: [["so", "bu yüzden (konuşma)"], ["consequently", "dolayısıyla (resmi)"], ["hence", "bu yüzden (çok resmi)"], ["that's why", "işte bu yüzden"], ["such … that", "öyle bir … ki"]],
          explain: "Sonuç bağlaçları ve üslupları." },
        { type: "mcq", q: "Raw material costs increased by 20%; ___ the new price list.",
          options: ["so that", "hence", "because", "although"], answer: 1,
          explain: "'hence + isim' = bu yüzden (yeni fiyat listesi). Çok resmi." },
        { type: "listen", text: "I missed the bus. That's why I'm late.",
          tr: "Otobüsü kaçırdım. İşte bu yüzden geç kaldım." },
        { type: "mcq", q: "The meeting ran late. ___, I missed my train.",
          options: ["Since", "Because of", "Consequently", "So as"], answer: 2,
          explain: "Yeni cümle başında sonuç → 'Consequently,'." },
        { type: "order", answer: "It was so cold that we stayed inside.",
          tr: "O kadar soğuktu ki içeride kaldık.",
          explain: "so + sıfat + that + sonuç." },
        { type: "fill", q: "We had a problem with the furnace. As a ___, production stopped.",
          answers: ["result"], explain: "'As a result' = sonuç olarak." },
        { type: "listen", text: "The order was so large that we hired extra staff.",
          tr: "Sipariş o kadar büyüktü ki ekstra personel aldık." }
      ]
    },
    {
      id: "connectors-06",
      title: "Amaç: to, in order to, so that, in case",
      level: "B2",
      week: 3,
      intro: {
        tr: "Amaç bildirirken 'to / in order to / so as to' arkasından YALIN FİİL gelir. 'so that' arkasından CÜMLE gelir ve genellikle can/could/will/would içerir. 'in case' ise amaç değil, 'olur da … diye' (önlem) anlamındadır; arkasından şimdiki/geçmiş zaman gelir, 'will' gelmez.",
        points: [
          "to / in order to / so as to + fiil: We called them (in order) to confirm the date.",
          "Olumsuz amaç: in order not to / so as not to + fiil (\"not to\" tek başına daha az doğal).",
          "so that + özne + can/could/will/would: I'll send it today so that you can check it.",
          "in case + şimdiki zaman (will YOK): Take an umbrella in case it rains.",
          "'for + fiil' amaç için YANLIŞ: ✗ I came for discuss → ✓ I came to discuss.",
          "for + isim / -ing: amaç-işlev: This tool is for cutting glass."
        ],
        examples: [
          { en: "We visited the shipyard to discuss the new project.", tr: "Yeni projeyi görüşmek için tersaneyi ziyaret ettik." },
          { en: "Please reply by Friday so that we can plan production.", tr: "Üretimi planlayabilmemiz için lütfen cuma gününe kadar yanıt verin." },
          { en: "I left early so as not to miss the flight.", tr: "Uçağı kaçırmamak için erken çıktım." },
          { en: "Take my number in case you get lost.", tr: "Olur da kaybolursan diye numaramı al." }
        ]
      },
      cards: [
        { en: "to", tr: "-mek için", ex: "I'm calling to confirm the order." },
        { en: "in order to", tr: "-mek amacıyla", ex: "We test every pane in order to guarantee safety." },
        { en: "so as to", tr: "-mek için (resmi)", ex: "We packed it carefully so as to avoid damage." },
        { en: "in order not to", tr: "-memek için", ex: "We left early in order not to miss the ferry." },
        { en: "so that", tr: "-sin diye, -ebilmesi için", ex: "I'll email the drawings so that you can review them." },
        { en: "in case", tr: "olur da … diye", ex: "Bring a jacket in case it gets cold." },
        { en: "for + -ing", tr: "…mek için (araç/işlev)", ex: "This machine is for cutting curved glass." },
        { en: "with the aim of", tr: "…amacıyla", ex: "We opened an office with the aim of reaching new markets." },
        { en: "just in case", tr: "ne olur ne olmaz", ex: "I'll bring some extra samples, just in case." }
      ],
      exercises: [
        { type: "mcq", q: "I'm writing ___ confirm the delivery date.",
          options: ["to", "for", "so that", "in case"], answer: 0,
          explain: "Amaç + yalın fiil → 'to'. 'for confirm' yanlış." },
        { type: "mcq", q: "I'll send you the drawings today ___ you can check them before the meeting.",
          options: ["in order to", "so as to", "for", "so that"], answer: 3,
          explain: "Arkasından cümle (you can check) → 'so that'." },
        { type: "fill", q: "Take an umbrella in ___ it rains.",
          answers: ["case"], explain: "'in case' = olur da … diye (önlem)." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["Take a jacket in case it will be cold.", "Take a jacket in case it is cold.", "Take a jacket so as it is cold.", "Take a jacket for it is cold."], answer: 1,
          explain: "'in case' sonrasında 'will' kullanılmaz; şimdiki zaman gelir." },
        { type: "fill", q: "We wrapped the glass carefully so as not ___ damage it.",
          answers: ["to"], explain: "'so as not to + fiil' = -memek için." },
        { type: "order", answer: "We test every pane in order to guarantee safety.",
          tr: "Güvenliği garanti etmek için her levhayı test ediyoruz.",
          explain: "'in order to + yalın fiil'." },
        { type: "match", pairs: [["in order to", "+ yalın fiil"], ["so that", "+ özne + can/could"], ["in case", "olur da … diye"], ["for + -ing", "işlev (…mek için kullanılır)"], ["just in case", "ne olur ne olmaz"]],
          explain: "Amaç yapıları ve arkalarından gelenler." },
        { type: "mcq", q: "She's learning Spanish ___ she can talk to her new colleagues.",
          options: ["so as to", "in order to", "for", "so that"], answer: 3,
          explain: "Arkasından özne + can → 'so that'." },
        { type: "listen", text: "I'm calling to confirm the order.",
          tr: "Siparişi teyit etmek için arıyorum." },
        { type: "mcq", q: "This machine is used ___ curved glass.",
          options: ["to cutting", "for cut", "for cutting", "so that cut"], answer: 2,
          explain: "İşlev: 'for + -ing' (veya 'to cut')." },
        { type: "order", answer: "Please reply soon so that we can plan production.",
          tr: "Üretimi planlayabilmemiz için lütfen yakında yanıt verin.",
          explain: "'so that + özne + can'." },
        { type: "fill", q: "I'll bring a few extra samples, just in ___.",
          answers: ["case"], explain: "'just in case' = ne olur ne olmaz." },
        { type: "listen", text: "Write down my number in case you get lost.",
          tr: "Olur da kaybolursan diye numaramı not al." }
      ]
    },
    // ───────────────────────── WEEK 4 ─────────────────────────
    {
      id: "connectors-07",
      title: "Sıralama & zaman: first, then, eventually…",
      level: "B2",
      week: 4,
      intro: {
        tr: "Bir süreci, hikâyeyi veya talimatı anlatırken sıralama bağlaçları akıcılık kazandırır. 'First of all, then, after that, finally' adımları sıralar. 'Meanwhile' aynı anda olanı, 'eventually' uzun bir sürecin sonunu anlatır. 'As soon as' ve 'once' ise 'yapar yapmaz' anlamındadır ve gelecek anlamında şimdiki zamanla kullanılır.",
        points: [
          "First (of all), → Then / Next / After that, → Finally,",
          "afterwards = daha sonra (tek başına, zarf); after + isim/-ing: after the meeting.",
          "eventually = sonunda (uzun bir süreç/zorluktan sonra); finally = son adım veya nihayet.",
          "meanwhile / in the meantime = bu arada (aynı zamanda).",
          "as soon as / once + şimdiki zaman (gelecek için): As soon as the glass arrives, we'll call you.",
          "'at the end' (yerin/olayın sonunda) ≠ 'in the end' (sonunda, sonuçta)."
        ],
        examples: [
          { en: "First, we cut the glass. Then we temper it.", tr: "Önce camı keseriz. Sonra temperleriz." },
          { en: "As soon as we receive payment, we'll ship the order.", tr: "Ödemeyi alır almaz siparişi sevk edeceğiz." },
          { en: "We negotiated for weeks. Eventually, they signed the contract.", tr: "Haftalarca pazarlık ettik. Sonunda sözleşmeyi imzaladılar." },
          { en: "I'll cook dinner. Meanwhile, you can set the table.", tr: "Ben yemeği yapacağım. Bu arada sen sofrayı kurabilirsin." }
        ]
      },
      cards: [
        { en: "first of all", tr: "her şeyden önce, ilk olarak", ex: "First of all, thank you for coming." },
        { en: "then", tr: "sonra", ex: "We cut the glass, then we polish the edges." },
        { en: "after that", tr: "ondan sonra", ex: "After that, the panes go into the furnace." },
        { en: "afterwards", tr: "sonradan, daha sonra", ex: "We had a meeting and went to dinner afterwards." },
        { en: "meanwhile", tr: "bu arada (aynı anda)", ex: "The glass is cooling. Meanwhile, we prepare the frames." },
        { en: "eventually", tr: "sonunda (uzun süreçten sonra)", ex: "Eventually, the customs released our container." },
        { en: "finally", tr: "son olarak; nihayet", ex: "Finally, we pack the panes in wooden crates." },
        { en: "as soon as", tr: "-ir -mez", ex: "Call me as soon as you land." },
        { en: "once", tr: "-dikten sonra, bir kere … -ince", ex: "Once the contract is signed, we can start production." },
        { en: "in the end", tr: "sonunda, nihayetinde", ex: "In the end, we chose the cheaper option." }
      ],
      exercises: [
        { type: "mcq", q: "___ the glass arrives, we'll inspect it.",
          options: ["As soon as", "Afterwards", "Meanwhile", "Eventually"], answer: 0,
          explain: "'As soon as + cümle' = -ir -mez. Diğerleri bağımsız zarftır." },
        { type: "mcq", q: "Which is correct?",
          options: ["Once the payment will arrive, we will ship.", "Once the payment arrives, we will ship.", "Once the payment arrived, we will ship.", "Once the payment arriving, we will ship."], answer: 1,
          explain: "Zaman bağlaçlarından sonra gelecek anlamında şimdiki zaman kullanılır." },
        { type: "fill", q: "The glass is cooling down. ___, we prepare the frames.",
          answers: ["Meanwhile", "In the meantime"], explain: "Aynı anda yapılan iş → 'Meanwhile'." },
        { type: "mcq", q: "We waited at customs for three weeks. ___, they released the container.",
          options: ["Meanwhile", "As soon as", "First of all", "Eventually"], answer: 3,
          explain: "Uzun ve zor bir süreçten sonra → 'Eventually'." },
        { type: "order", answer: "First, we cut the glass. Then we temper it.",
          tr: "Önce camı keseriz. Sonra temperleriz.",
          explain: "Süreç anlatımı: First → Then." },
        { type: "match", pairs: [["first of all", "her şeyden önce"], ["meanwhile", "bu arada"], ["eventually", "sonunda (uzun süreçten sonra)"], ["as soon as", "-ir -mez"], ["afterwards", "daha sonra"]],
          explain: "Sıralama ve zaman bağlaçları." },
        { type: "mcq", q: "We had lunch with the client and went back to the office ___.",
          options: ["afterwards", "after", "as soon as", "once"], answer: 0,
          explain: "Cümle sonunda tek başına 'afterwards' kullanılır; 'after' arkasından isim ister." },
        { type: "fill", q: "Call me as soon as you ___ (land).",
          answers: ["land"], explain: "'as soon as' sonrası gelecek anlamı için şimdiki zaman." },
        { type: "listen", text: "Once the contract is signed, we can start production.",
          tr: "Sözleşme imzalandıktan sonra üretime başlayabiliriz." },
        { type: "mcq", q: "We stood in a long queue ___ of the concert hall.",
          options: ["in the end", "eventually", "at the end", "finally"], answer: 2,
          explain: "Fiziksel bir yerin sonu: 'at the end of'." },
        { type: "order", answer: "After that, the panes are packed in wooden crates.",
          tr: "Ondan sonra levhalar ahşap sandıklara paketlenir.",
          explain: "'After that,' cümle başında, virgülle." },
        { type: "fill", q: "We discussed several options, but in the ___ we chose the cheaper one.",
          answers: ["end"], explain: "'in the end' = sonunda, nihayetinde." },
        { type: "listen", text: "I'll cook dinner. Meanwhile, you can set the table.",
          tr: "Ben yemeği yapacağım. Bu arada sen sofrayı kurabilirsin." }
      ]
    },
    {
      id: "connectors-08",
      title: "Konuşma işaretleri: well, actually, anyway…",
      level: "B2",
      week: 4,
      intro: {
        tr: "Akıcı konuşmanın sırrı 'discourse marker' denen küçük kelimelerdir. Düşünmek için zaman kazandırır, konu değiştirir, düzeltme yapar veya kibar bir şekilde karşı çıkarlar. 'Well' yanıt vermeden önce düşünmeyi, 'actually' düzeltme veya beklenmedik bilgiyi, 'anyway' konuya dönmeyi, 'by the way' konu değiştirmeyi gösterir.",
        points: [
          "Well, … → düşünürken / yumuşak bir cevap: Well, it depends.",
          "Actually, … → düzeltme, beklenmedik bilgi (≠ 'şu anda'! 'currently' kullan).",
          "Anyway, … → konuya dönme veya konuşmayı bitirme.",
          "By the way, … → yeni konu açma (aklıma gelmişken).",
          "I mean, … → kendini düzeltme/açıklama; You know, … → ortak bilgiye gönderme.",
          "To be honest, / Basically, / Right, / So, → dürüstlük, özetleme, yeni aşamaya geçiş."
        ],
        examples: [
          { en: "Well, I'm not sure we can do it by Friday.", tr: "Şey, cuma gününe kadar yapabileceğimizden emin değilim." },
          { en: "Actually, the order was for twenty panes, not ten.", tr: "Aslında sipariş on değil yirmi levhaydı." },
          { en: "Anyway, let's get back to the price.", tr: "Neyse, fiyata dönelim." },
          { en: "By the way, how was your holiday?", tr: "Bu arada, tatilin nasıldı?" }
        ]
      },
      cards: [
        { en: "well", tr: "şey, yani (düşünürken)", ex: "Well, it depends on the thickness." },
        { en: "actually", tr: "aslında, doğrusu", ex: "Actually, I've never been to Germany." },
        { en: "anyway", tr: "neyse, her neyse", ex: "Anyway, I should go now." },
        { en: "by the way", tr: "bu arada, aklıma gelmişken", ex: "By the way, did you get my email?" },
        { en: "you know", tr: "bilirsin, hani", ex: "It's that new café, you know, near the station." },
        { en: "I mean", tr: "yani, demek istediğim", ex: "It's good. I mean, it's not perfect, but it's good." },
        { en: "so", tr: "peki, eee (konuya giriş)", ex: "So, what do you do for a living?" },
        { en: "right", tr: "tamam, peki (geçiş)", ex: "Right, let's look at the next item." },
        { en: "basically", tr: "kısacası, temelde", ex: "Basically, we need more time." },
        { en: "to be honest", tr: "açıkçası, dürüst olmak gerekirse", ex: "To be honest, the price is a bit high for us." }
      ],
      exercises: [
        { type: "mcq", q: "\"Can you deliver by Monday?\" — \"___, it might be difficult, but I'll check.\"",
          options: ["By the way", "Well", "Afterwards", "Moreover"], answer: 1,
          explain: "Yumuşak, düşünerek cevap vermeye başlarken 'Well'." },
        { type: "mcq", q: "\"So you're from Ankara?\" — \"___, I'm from Izmir. But I live in Ankara.\"",
          options: ["Anyway", "By the way", "Actually", "Right"], answer: 2,
          explain: "Yanlış bir bilgiyi düzeltirken 'Actually'." },
        { type: "fill", q: "By the ___, did you get my email about the invoice?",
          answers: ["way"], explain: "'By the way' = bu arada (yeni konu)." },
        { type: "mcq", q: "Turkish speakers often say 'actually' for 'şu anda'. Which word is correct for 'Şu anda Bursa'da çalışıyorum'?",
          options: ["Currently, I work in Bursa.", "Actually, I work in Bursa.", "Anyway, I work in Bursa.", "Basically, I work in Bursa."], answer: 0,
          explain: "'actually' = aslında; 'şu anda' = currently / at the moment." },
        { type: "order", answer: "Anyway, let's get back to the price.",
          tr: "Neyse, fiyata dönelim.",
          explain: "'Anyway' konuya geri dönmek için kullanılır." },
        { type: "match", pairs: [["by the way", "konu değiştirme"], ["actually", "düzeltme / beklenmedik bilgi"], ["anyway", "konuya dönme"], ["I mean", "kendini açıklama"], ["to be honest", "açık sözlülük"]],
          explain: "Konuşma işaretlerinin işlevleri." },
        { type: "fill", q: "To be ___, the price is a bit high for us.",
          answers: ["honest", "frank"], explain: "'To be honest' = açıkçası." },
        { type: "mcq", q: "\"It's a nice restaurant. I ___, the food isn't amazing, but the view is great.\"",
          options: ["said", "know", "think so", "mean"], answer: 3,
          explain: "'I mean' söylediğini açıklarken/düzeltirken kullanılır." },
        { type: "listen", text: "By the way, how was your holiday?",
          tr: "Bu arada, tatilin nasıldı?" },
        { type: "mcq", q: "At the start of a meeting: \"___, let's look at the first item on the agenda.\"",
          options: ["Actually", "Right", "Though", "Besides"], answer: 1,
          explain: "Yeni bir aşamaya geçerken 'Right,' / 'OK,' / 'So,' kullanılır." },
        { type: "order", answer: "Basically, we need two more weeks.",
          tr: "Kısacası, iki hafta daha zamana ihtiyacımız var.",
          explain: "'Basically' özetlemek için kullanılır." },
        { type: "fill", q: "___, what do you do for a living?",
          answers: ["So"], hint: "iki harf, sohbete giriş",
          explain: "'So,' sohbet başlatırken veya soru sorarken doğal bir giriştir." },
        { type: "listen", text: "Well, it depends on the thickness of the glass.",
          tr: "Şey, camın kalınlığına bağlı." }
      ]
    },
    // ───────────────────────── WEEK 5 ─────────────────────────
    {
      id: "connectors-09",
      title: "Koşul: unless, as long as, otherwise…",
      level: "B2+",
      week: 5,
      intro: {
        tr: "Koşul bildirmek için 'if' dışında pek çok bağlaç vardır. 'Unless' = 'if … not' (-medikçe). 'As long as / provided (that)' = '… şartıyla'. 'Otherwise / or else' = 'aksi takdirde'. 'Even if' = '… olsa bile'. Bu bağlaçlardan sonra gelecek anlamında şimdiki zaman kullanılır.",
        points: [
          "unless = if not: We can't ship unless you pay (= if you don't pay). 'unless' sonrası olumsuz fiil genelde YOK.",
          "as long as / so long as / provided (that) / providing + şimdiki zaman: …şartıyla.",
          "Otherwise, / or else → aksi takdirde: Pay today; otherwise, the order will be cancelled.",
          "even if → olsa bile (koşul gerçekleşse de sonuç değişmez) ≠ even though (gerçek durum).",
          "in case → önlem (… diye) ≠ if (koşul).",
          "Gelecek anlamında: unless/as long as + şimdiki zaman (will YOK)."
        ],
        examples: [
          { en: "We can't start production unless you approve the drawings.", tr: "Çizimleri onaylamadıkça üretime başlayamayız." },
          { en: "You can borrow my car as long as you drive carefully.", tr: "Dikkatli sürdüğün sürece arabamı ödünç alabilirsin." },
          { en: "Please confirm today; otherwise, we may lose the booking.", tr: "Lütfen bugün teyit edin; aksi takdirde rezervasyonu kaybedebiliriz." },
          { en: "Even if it rains, we'll have the barbecue.", tr: "Yağmur yağsa bile mangal yapacağız." }
        ]
      },
      cards: [
        { en: "unless", tr: "-medikçe, -mezse", ex: "We won't ship unless we receive the deposit." },
        { en: "as long as", tr: "…sürece, …şartıyla", ex: "You can stay as long as you like." },
        { en: "provided (that)", tr: "…şartıyla (resmi)", ex: "We can offer a 5% discount provided that you order 500 panes." },
        { en: "providing", tr: "…şartıyla", ex: "Providing the weather is good, the ship will sail tomorrow." },
        { en: "otherwise", tr: "aksi takdirde, yoksa", ex: "Book now; otherwise, there won't be any seats." },
        { en: "or else", tr: "yoksa (konuşma)", ex: "Hurry up, or else we'll miss the train." },
        { en: "even if", tr: "…olsa bile", ex: "Even if we work all weekend, we won't finish." },
        { en: "on condition that", tr: "…koşuluyla (resmi)", ex: "They agreed on condition that we cover the freight." },
        { en: "suppose / supposing", tr: "diyelim ki, farz et ki", ex: "Supposing the glass breaks in transit, who pays?" },
        { en: "in case", tr: "olur da … diye", ex: "Keep a copy of the certificate in case customs ask for it." }
      ],
      exercises: [
        { type: "mcq", q: "We can't ship the order ___ we receive the payment.",
          options: ["even if", "if", "as long as", "unless"], answer: 3,
          explain: "'unless' = if … not: Ödemeyi almadıkça sevk edemeyiz." },
        { type: "mcq", q: "You can use my laptop ___ you don't install anything.",
          options: ["unless", "otherwise", "as long as", "in case"], answer: 2,
          explain: "'as long as' = …şartıyla. 'unless' + olumsuz cümle anlamı bozar." },
        { type: "fill", q: "Please confirm by Friday; ___, the price may change.",
          answers: ["otherwise"], explain: "'otherwise' = aksi takdirde." },
        { type: "mcq", q: "___ it rains tomorrow, the match will still take place. It's indoors.",
          options: ["Even if", "Unless", "Provided that", "As long as"], answer: 0,
          explain: "Koşul gerçekleşse de sonuç değişmiyor → 'Even if'." },
        { type: "fill", q: "We can give you a 5% discount provided ___ you order at least 500 panes.",
          answers: ["that"], explain: "'provided that' = …şartıyla." },
        { type: "order", answer: "We won't start production unless you approve the drawings.",
          tr: "Çizimleri onaylamadıkça üretime başlamayacağız.",
          explain: "'unless + olumlu fiil' = …medikçe." },
        { type: "match", pairs: [["unless", "-medikçe"], ["provided that", "…şartıyla (resmi)"], ["otherwise", "aksi takdirde"], ["even if", "…olsa bile"], ["or else", "yoksa (konuşma)"]],
          explain: "Koşul bağlaçlarının anlamları." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["Unless you will pay, we won't ship.", "Unless you pay, we won't ship.", "Unless you don't pay, we won't ship.", "Unless you paid, we won't ship."], answer: 1,
          explain: "'unless' sonrası gelecek anlamı için şimdiki zaman, olumlu fiil." },
        { type: "listen", text: "Hurry up, or else we'll miss the train.",
          tr: "Acele et, yoksa treni kaçıracağız." },
        { type: "mcq", q: "Take a copy of the certificate ___ the customs officer asks for it.",
          options: ["unless", "otherwise", "provided", "in case"], answer: 3,
          explain: "Önlem (olur da isterse diye) → 'in case'." },
        { type: "order", answer: "You can stay with us as long as you like.",
          tr: "İstediğin kadar bizimle kalabilirsin.",
          explain: "'as long as you like' = istediğin sürece." },
        { type: "fill", q: "I'll come to the party ___ I finish work early. Otherwise, I'll stay home.",
          answers: ["if", "provided", "providing", "as long as", "so long as", "provided that", "providing that"],
          explain: "Koşul: if / as long as / provided." },
        { type: "listen", text: "Even if we work all weekend, we won't finish.",
          tr: "Bütün hafta sonu çalışsak bile bitiremeyeceğiz." }
      ]
    },
    {
      id: "connectors-10",
      title: "Örnek & açıklama: for instance, in other words…",
      level: "B2+",
      week: 5,
      intro: {
        tr: "Bir fikri örneklerle desteklemek veya başka sözcüklerle açıklamak, hem toplantıda hem e-postada çok işe yarar. 'For example / for instance' bir cümle başlatır; 'such as' ise arkasından isim listesi alır. 'In other words / that is to say' tekrar ifade eder; 'namely' tam olarak hangisi olduğunu söyler; 'in particular / especially' öne çıkarır.",
        points: [
          "For example, / For instance, + cümle (başta virgül).",
          "such as + isim(ler): marine products such as portholes and windscreens.",
          "like = such as (daha gündelik).",
          "In other words, / That is to say, / That is, → yeniden ifade.",
          "namely → yani, şöyle ki (tam liste/isim): two problems, namely cost and time.",
          "in particular / especially / particularly → özellikle. e.g. = örneğin, i.e. = yani (yazıda)."
        ],
        examples: [
          { en: "We supply marine glass such as portholes and wheelhouse windows.", tr: "Lomboz ve köprüüstü camları gibi denizcilik camları tedarik ediyoruz." },
          { en: "The order is late. In other words, we need to apologise.", tr: "Sipariş gecikti. Başka bir deyişle, özür dilememiz gerekiyor." },
          { en: "I love Italian food, in particular pasta.", tr: "İtalyan yemeklerini, özellikle makarnayı çok severim." },
          { en: "We have two concerns, namely price and lead time.", tr: "İki endişemiz var: fiyat ve teslim süresi." }
        ]
      },
      cards: [
        { en: "for example", tr: "örneğin", ex: "For example, our 12 mm panes weigh 30 kg per square metre." },
        { en: "for instance", tr: "mesela, örneğin", ex: "Some hobbies, for instance chess, need patience." },
        { en: "such as", tr: "…gibi (+isim)", ex: "We serve ports such as Rotterdam and Hamburg." },
        { en: "like", tr: "gibi (gündelik)", ex: "I enjoy outdoor sports like cycling." },
        { en: "in other words", tr: "başka bir deyişle", ex: "In other words, the deadline is impossible." },
        { en: "that is to say", tr: "yani, demek ki", ex: "We need it by the 5th, that is to say, next Tuesday." },
        { en: "namely", tr: "yani, şöyle ki", ex: "One country, namely Norway, ordered twice." },
        { en: "in particular", tr: "özellikle", ex: "We liked the edge finish in particular." },
        { en: "e.g.", tr: "örn. (yazıda)", ex: "Safety glass (e.g. tempered or laminated) is required." },
        { en: "i.e.", tr: "yani (yazıda)", ex: "Payment is due in 30 days, i.e. by 10 May." }
      ],
      exercises: [
        { type: "mcq", q: "We produce marine glass ___ portholes and bridge windows.",
          options: ["such as", "for example,", "in other words", "namely that"], answer: 0,
          explain: "Arkasından doğrudan isim listesi geliyor → 'such as'." },
        { type: "mcq", q: "The deadline is in two days. ___, we have to work this weekend.",
          options: ["Such as", "Namely", "In other words", "For instance of"], answer: 2,
          explain: "Durumu başka sözcüklerle ifade etmek → 'In other words,'." },
        { type: "fill", q: "There are many ways to relax. For ___, you can try yoga.",
          answers: ["example", "instance"], explain: "'For example / For instance' + cümle." },
        { type: "mcq", q: "The client raised two issues, ___ the price and the delivery time.",
          options: ["such as", "namely", "in other words", "for instance"], answer: 1,
          explain: "Tam olarak hangi iki konu olduğunu belirtmek → 'namely'." },
        { type: "order", answer: "I love Italian food, in particular pasta.",
          tr: "İtalyan yemeklerini, özellikle makarnayı çok severim.",
          explain: "'in particular' = özellikle." },
        { type: "match", pairs: [["e.g.", "örneğin (yazıda)"], ["i.e.", "yani (yazıda)"], ["namely", "şöyle ki (tam isim)"], ["in other words", "başka bir deyişle"], ["in particular", "özellikle"]],
          explain: "Örnek ve açıklama ifadeleri." },
        { type: "mcq", q: "Payment is due within 30 days, ___ by the end of May.",
          options: ["e.g.", "such as", "i.e.", "for instance"], answer: 2,
          explain: "Aynı şeyi netleştirme (yani) → 'i.e.'. 'e.g.' örnek verir." },
        { type: "fill", q: "We need the glass by the 5th, that is to ___, next Tuesday.",
          answers: ["say"], explain: "'that is to say' = yani." },
        { type: "listen", text: "In other words, we need more time.",
          tr: "Başka bir deyişle, daha fazla zamana ihtiyacımız var." },
        { type: "mcq", q: "I enjoy outdoor activities, ___ hiking and cycling.",
          options: ["like", "namely that", "in other words", "otherwise"], answer: 0,
          explain: "Gündelik dilde örnek isimler için 'like' (= such as)." },
        { type: "order", answer: "Safety glass, for example laminated glass, is required.",
          tr: "Güvenlik camı, örneğin lamine cam, gereklidir.",
          explain: "'for example' araya da girebilir." },
        { type: "fill", q: "We have customers in many countries, ___ as Norway, Greece and Korea.",
          answers: ["such"], explain: "'such as + isim listesi'." },
        { type: "listen", text: "We liked the edge finish in particular.",
          tr: "Özellikle kenar işçiliğini beğendik." }
      ]
    },
    // ───────────────────────── WEEK 6 ─────────────────────────
    {
      id: "connectors-11",
      title: "Vurgu & tutum: in fact, clearly, admittedly…",
      level: "B2+",
      week: 6,
      intro: {
        tr: "Konuşmacının tutumunu gösteren zarflar ('stance markers') İngilizcede çok doğaldır. 'In fact / as a matter of fact' önceki bilgiyi güçlendirir ya da düzeltir. 'Indeed' resmi vurgudur. 'Clearly / obviously' apaçık bir şeyi, 'admittedly' kabul ettiğin bir zayıflığı, 'surprisingly' beklenmedik olanı, 'to be fair' karşı tarafa hak vermeyi gösterir.",
        points: [
          "In fact, / As a matter of fact, → aslında, hatta (güçlendirme veya düzeltme).",
          "Indeed → gerçekten de (resmi onay/vurgu): It was indeed a difficult year.",
          "Clearly, / Obviously, → açıkça; dikkat: 'obviously' karşı tarafı küçümseyici olabilir.",
          "Admittedly, → kabul etmek gerekir ki (zayıf noktayı kabul).",
          "Surprisingly, / Not surprisingly, / Interestingly, → beklenti hakkında yorum.",
          "To be fair, → hakkını vermek gerekirse (karşı tarafa adil olmak)."
        ],
        examples: [
          { en: "The test wasn't difficult. In fact, it was quite easy.", tr: "Test zor değildi. Aslında oldukça kolaydı." },
          { en: "Admittedly, our price is higher, but our quality is better.", tr: "Kabul etmek gerekir ki fiyatımız daha yüksek, ama kalitemiz daha iyi." },
          { en: "Surprisingly, the ferry left on time.", tr: "Şaşırtıcı bir şekilde feribot zamanında kalktı." },
          { en: "To be fair, he did warn us about the delay.", tr: "Hakkını vermek lazım, gecikme konusunda bizi uyarmıştı." }
        ]
      },
      cards: [
        { en: "indeed", tr: "gerçekten de (resmi)", ex: "It was indeed a successful year for our exports." },
        { en: "in fact", tr: "aslında, hatta", ex: "I don't mind. In fact, I'd love to help." },
        { en: "as a matter of fact", tr: "aslına bakarsan", ex: "As a matter of fact, I've just finished the report." },
        { en: "clearly", tr: "açıkça, belli ki", ex: "Clearly, the packaging was not strong enough." },
        { en: "obviously", tr: "tabii ki, belli ki", ex: "Obviously, we'll replace the broken panes." },
        { en: "admittedly", tr: "kabul etmek gerekir ki", ex: "Admittedly, we made a mistake with the invoice." },
        { en: "surprisingly", tr: "şaşırtıcı biçimde", ex: "Surprisingly, the restaurant was empty." },
        { en: "to be fair", tr: "hakkını vermek gerekirse", ex: "To be fair, the weather was terrible." },
        { en: "frankly", tr: "açıkçası", ex: "Frankly, I don't think that's a good idea." },
        { en: "naturally", tr: "doğal olarak", ex: "Naturally, the customer asked for a discount." }
      ],
      exercises: [
        { type: "mcq", q: "\"Are you tired?\" — \"Not at all. ___, I feel great.\"",
          options: ["To be fair", "Admittedly", "Otherwise", "In fact"], answer: 3,
          explain: "Önceki ifadeyi güçlendirmek → 'In fact'." },
        { type: "mcq", q: "___, our price is a little higher, but our glass lasts twice as long.",
          options: ["Surprisingly", "Admittedly", "Indeed", "As a result"], answer: 1,
          explain: "Kendi zayıf noktanı kabul edip sonra savunma → 'Admittedly'." },
        { type: "fill", q: "As a matter of ___, I've just sent you the certificates.",
          answers: ["fact"], explain: "'As a matter of fact' = aslına bakarsan." },
        { type: "mcq", q: "The supplier was late again, but, to be ___, the storm closed the port for three days.",
          options: ["right", "true", "clear", "fair"], answer: 3,
          explain: "Karşı tarafa hak vermek → 'to be fair'." },
        { type: "order", answer: "Surprisingly, the ferry left on time.",
          tr: "Şaşırtıcı bir şekilde feribot zamanında kalktı.",
          explain: "Tutum zarfı cümle başında, virgülle." },
        { type: "match", pairs: [["admittedly", "kabul etmek gerekir ki"], ["indeed", "gerçekten de (resmi)"], ["to be fair", "hakkını vermek gerekirse"], ["clearly", "belli ki, açıkça"], ["surprisingly", "şaşırtıcı biçimde"]],
          explain: "Tutum ve vurgu ifadeleri." },
        { type: "mcq", q: "Five panes arrived broken. ___, the packaging was not strong enough.",
          options: ["To be fair", "Admittedly", "Clearly", "Surprisingly"], answer: 2,
          explain: "Kanıttan çıkan apaçık sonuç → 'Clearly'." },
        { type: "fill", q: "It was ___ a difficult year, but our exports still grew.",
          answers: ["indeed"], explain: "Resmi vurgu: 'indeed' = gerçekten de." },
        { type: "listen", text: "To be fair, he did warn us about the delay.",
          tr: "Hakkını vermek lazım, gecikme konusunda bizi uyarmıştı." },
        { type: "mcq", q: "\"I thought you didn't like jazz.\" — \"___, I've been to three concerts this year!\"",
          options: ["As a matter of fact", "Obviously", "Admittedly", "Naturally"], answer: 0,
          explain: "Yanlış bir varsayımı düzeltmek → 'As a matter of fact'." },
        { type: "order", answer: "Admittedly, we made a mistake with the invoice.",
          tr: "Kabul ediyoruz, faturada bir hata yaptık.",
          explain: "'Admittedly' hatayı kabul ederken kullanılır." },
        { type: "fill", q: "We expected a lot of complaints, but, ___, nobody complained.",
          answers: ["surprisingly", "amazingly", "interestingly"], explain: "Beklenmedik sonuç → 'surprisingly'." },
        { type: "listen", text: "In fact, I'd be happy to help.",
          tr: "Aslında yardım etmekten memnuniyet duyarım." }
      ]
    },
    {
      id: "connectors-12",
      title: "Özetleme & sonuç: to sum up, all in all…",
      level: "B2+",
      week: 6,
      intro: {
        tr: "Bir sunumu, toplantıyı veya e-postayı toparlarken özetleme ifadeleri kullanılır. Resmi yazıda 'In conclusion, To sum up, To summarise, Overall'; konuşmada ise 'All in all, At the end of the day, So basically, Long story short' daha doğaldır. Üslubu (register) bağlama göre seçmek C1 seviyesinin önemli bir göstergesidir.",
        points: [
          "Resmi: In conclusion, / To summarise, / To sum up, / In summary, → rapor, sunum.",
          "Overall, / On the whole, → genel değerlendirme (hem resmi hem gündelik).",
          "All in all, → her şey düşünüldüğünde (yarı resmi).",
          "Gündelik: At the end of the day, / Long story short, / So basically, → konuşma.",
          "'In conclusion' yalnızca gerçekten SON paragrafta/sözde kullanılır, konuşmada ağır kaçar.",
          "Özetlerken yeni bilgi eklenmez; ana fikirler kısaca tekrarlanır."
        ],
        examples: [
          { en: "In conclusion, laminated glass is the safest option for the bridge.", tr: "Sonuç olarak, köprüüstü için en güvenli seçenek lamine camdır." },
          { en: "All in all, it was a great holiday.", tr: "Her şey düşünüldüğünde harika bir tatildi." },
          { en: "At the end of the day, the customer decides.", tr: "Nihayetinde kararı müşteri verir." },
          { en: "Long story short, we missed the flight.", tr: "Uzun lafın kısası, uçağı kaçırdık." }
        ]
      },
      cards: [
        { en: "in conclusion", tr: "sonuç olarak (resmi)", ex: "In conclusion, we recommend option B." },
        { en: "to sum up", tr: "özetle", ex: "To sum up, sales rose by 12% this year." },
        { en: "to summarise", tr: "özetlemek gerekirse", ex: "To summarise, there are three main risks." },
        { en: "overall", tr: "genel olarak", ex: "Overall, the customer was happy with the delivery." },
        { en: "on the whole", tr: "genel olarak, bütünüyle", ex: "On the whole, the trip went well." },
        { en: "all in all", tr: "her şey düşünüldüğünde", ex: "All in all, it was a productive meeting." },
        { en: "at the end of the day", tr: "nihayetinde, sonuçta", ex: "At the end of the day, it's your decision." },
        { en: "long story short", tr: "uzun lafın kısası", ex: "Long story short, I got the job." },
        { en: "in short", tr: "kısacası", ex: "In short, we need a new supplier." },
        { en: "in a nutshell", tr: "özetle, kısaca", ex: "In a nutshell, the project was a success." }
      ],
      exercises: [
        { type: "mcq", q: "Which is the most suitable to end a formal report?",
          options: ["Long story short, option B is better.", "In conclusion, option B offers the best value.", "So basically, B is the one.", "At the end of the day, whatever."], answer: 1,
          explain: "Resmi rapor sonu → 'In conclusion,'." },
        { type: "mcq", q: "Chatting with a friend: \"I lost my passport, missed the ferry, and slept at the port. ___, it was a disaster!\"",
          options: ["In conclusion", "To summarise", "Hereby", "Long story short"], answer: 3,
          explain: "Arkadaşla sohbet → gündelik 'Long story short'." },
        { type: "fill", q: "All in ___, it was a very productive meeting.",
          answers: ["all"], explain: "'All in all' = her şey düşünüldüğünde." },
        { type: "mcq", q: "\"We can recommend a solution, but at the end of the ___, it's the shipowner's decision.\"",
          options: ["day", "time", "end", "line"], answer: 0,
          explain: "Kalıp: 'at the end of the day' = nihayetinde." },
        { type: "order", answer: "To sum up, sales rose by twelve percent this year.",
          tr: "Özetle, bu yıl satışlar yüzde on iki arttı.",
          explain: "'To sum up,' cümle başında + virgül." },
        { type: "match", pairs: [["in conclusion", "resmi sonuç"], ["long story short", "gündelik özet"], ["on the whole", "genel olarak"], ["in a nutshell", "kısaca, özetle"], ["at the end of the day", "nihayetinde"]],
          explain: "Özetleme ifadeleri ve üslupları." },
        { type: "fill", q: "On the ___, the trip went well, apart from the weather.",
          answers: ["whole"], explain: "'On the whole' = genel olarak." },
        { type: "mcq", q: "___, the customer was satisfied with both the glass and the service.",
          options: ["Unless", "Meanwhile", "Overall", "Whereas"], answer: 2,
          explain: "Genel değerlendirme → 'Overall,'." },
        { type: "listen", text: "In short, we need a new supplier.",
          tr: "Kısacası, yeni bir tedarikçiye ihtiyacımız var." },
        { type: "mcq", q: "Which phrase sounds TOO formal in a casual chat?",
          options: ["All in all", "In conclusion", "Basically", "Anyway"], answer: 1,
          explain: "'In conclusion' sohbet için fazla resmidir." },
        { type: "order", answer: "At the end of the day, it's your decision.",
          tr: "Sonuçta karar senin.",
          explain: "'At the end of the day' gündelik bir sonuç ifadesidir." },
        { type: "fill", q: "In a ___, the project was a success.",
          answers: ["nutshell"], explain: "'In a nutshell' = özetle, kısaca." },
        { type: "listen", text: "All in all, it was a great holiday.",
          tr: "Her şey düşünüldüğünde harika bir tatildi." }
      ]
    },
    // ───────────────────────── WEEK 7 ─────────────────────────
    {
      id: "connectors-13",
      title: "C1 tavizi: albeit, granted, be that as it may",
      level: "C1",
      week: 7,
      intro: {
        tr: "C1 seviyesinde zıtlık ve taviz (concession) için daha incelikli yapılar kullanılır. 'Albeit' (= although it is/was) sıfat veya zarf öbeği alır. 'Notwithstanding' çok resmi bir 'despite'tir. 'Even so' ve 'be that as it may' karşı argümanı kabul edip kendi görüşüne döner. 'Granted' ve 'while it is true that' karşı tarafa önce hak verir. 'Much as' = 'ne kadar … de'.",
        points: [
          "albeit + sıfat/zarf/isim öbeği (fiil yok): a slow, albeit steady, improvement.",
          "notwithstanding + isim (çok resmi, hukuki): Notwithstanding the delay, the contract remains valid.",
          "Even so, / Be that as it may, → 'öyle olsa bile' (yeni cümle başında).",
          "Granted, … but … → 'Kabul, … ama …' (önce taviz, sonra karşı görüş).",
          "Much as I + like/admire/want…, → 'Ne kadar … sem de': Much as I'd like to help, I can't.",
          "While it is true that…, → resmi tartışmada karşı görüşü kabul etme."
        ],
        examples: [
          { en: "Sales improved, albeit slowly.", tr: "Satışlar yavaş da olsa iyileşti." },
          { en: "Granted, the price is high, but the glass will last for decades.", tr: "Kabul, fiyat yüksek ama cam onlarca yıl dayanacak." },
          { en: "Much as I love Istanbul, the traffic drives me crazy.", tr: "İstanbul'u ne kadar sevsem de trafiği beni çıldırtıyor." },
          { en: "The delay was not our fault. Be that as it may, we apologise.", tr: "Gecikme bizim hatamız değildi. Öyle olsa bile özür dileriz." }
        ]
      },
      cards: [
        { en: "albeit", tr: "…olsa da (+sıfat/zarf)", ex: "It was a profitable, albeit difficult, year." },
        { en: "notwithstanding", tr: "…e rağmen (çok resmi)", ex: "Notwithstanding the strike, the vessel sailed on time." },
        { en: "even so", tr: "öyle olsa bile", ex: "The offer was low. Even so, we accepted it." },
        { en: "be that as it may", tr: "her ne olursa olsun, öyle olsa bile", ex: "Be that as it may, the deadline cannot change." },
        { en: "granted", tr: "kabul, doğru", ex: "Granted, it's expensive, but it's worth it." },
        { en: "much as", tr: "ne kadar … se de", ex: "Much as I'd like to stay, I have to go." },
        { en: "while it is true that", tr: "…doğru olsa da", ex: "While it is true that steel is cheaper, glass looks better." },
        { en: "that said", tr: "bununla birlikte", ex: "The design is great. That said, it's hard to install." },
        { en: "all the same", tr: "yine de", ex: "I know it's late. All the same, I'd like to call him." },
        { en: "regardless of", tr: "…den bağımsız olarak, …e bakmaksızın", ex: "We test every pane, regardless of size." }
      ],
      exercises: [
        { type: "mcq", q: "The market recovered, ___ slowly.",
          options: ["despite", "although of", "albeit", "notwithstanding that"], answer: 2,
          explain: "'albeit + zarf' = yavaş da olsa." },
        { type: "mcq", q: "___ the force majeure clause, the buyer must pay the deposit.",
          options: ["Notwithstanding", "Much as", "Albeit", "Granted"], answer: 0,
          explain: "Çok resmi + isim öbeği → 'Notwithstanding'." },
        { type: "fill", q: "___ as I'd like to help, I really don't have time this week.",
          answers: ["Much"], explain: "'Much as + özne + fiil' = ne kadar … se de." },
        { type: "mcq", q: "\"The delay wasn't really our fault.\" — \"___, the client expects compensation.\"",
          options: ["Much as", "Albeit", "Notwithstanding", "Be that as it may"], answer: 3,
          explain: "Karşı argümanı kabul edip devam etmek → 'Be that as it may,'." },
        { type: "order", answer: "Granted, it's expensive, but it's worth every penny.",
          tr: "Kabul, pahalı ama her kuruşuna değer.",
          explain: "'Granted, …, but …' taviz yapısıdır." },
        { type: "match", pairs: [["albeit", "…olsa da (+sıfat/zarf)"], ["notwithstanding", "…e rağmen (çok resmi)"], ["much as", "ne kadar … se de"], ["granted", "kabul, doğru"], ["be that as it may", "öyle olsa bile"]],
          explain: "C1 taviz yapıları." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["It was a successful albeit it was a tiring trip.", "It was a successful, albeit tiring, trip.", "It was albeit successful, tiring trip.", "Albeit it was tiring, it was successful."], answer: 1,
          explain: "'albeit' sonrası fiil gelmez; sıfat öbeği alır." },
        { type: "fill", q: "The offer was quite low. Even ___, we decided to accept it.",
          answers: ["so"], explain: "'Even so' = öyle olsa bile." },
        { type: "listen", text: "Much as I love Istanbul, the traffic drives me crazy.",
          tr: "İstanbul'u ne kadar sevsem de trafiği beni çıldırtıyor." },
        { type: "mcq", q: "___ steel frames are cheaper, aluminium frames resist corrosion much better.",
          options: ["Albeit", "Be that as it may", "Notwithstanding", "While it is true that"], answer: 3,
          explain: "Arkasından cümle geliyor ve karşı görüş kabul ediliyor → 'While it is true that'." },
        { type: "order", answer: "Sales improved this year, albeit slowly.",
          tr: "Satışlar bu yıl yavaş da olsa arttı.",
          explain: "'albeit + zarf' cümle sonunda." },
        { type: "fill", q: "We test every single pane, regardless ___ its size.",
          answers: ["of"], explain: "'regardless of + isim' = …e bakmaksızın." },
        { type: "listen", text: "The delay was not our fault. Be that as it may, we apologise.",
          tr: "Gecikme bizim hatamız değildi. Öyle olsa bile özür dileriz." }
      ]
    },
    {
      id: "connectors-14",
      title: "E-posta & rapor dili: regarding, further to…",
      level: "C1",
      week: 7,
      intro: {
        tr: "İş yazışmalarında belirli bağlantı ifadeleri profesyonel ve net bir ton sağlar. 'With reference to / regarding / further to' e-postanın konusunu önceki bir iletişime bağlar. 'As per' bir talimata veya anlaşmaya uygunluğu, 'in light of' yeni bir bilgiye dayanarak karar vermeyi, 'accordingly' buna uygun eylemi, 'subsequently' ise sonradan olanı ifade eder.",
        points: [
          "With reference to / Regarding / Concerning + isim → konu: Regarding your order No. 245, …",
          "Further to + isim → önceki iletişime ek: Further to our call yesterday, …",
          "as per + isim → …e göre/uyarınca: as per your request / as per the contract.",
          "in light of / in view of + isim → …ışığında, göz önüne alındığında.",
          "accordingly → buna göre, buna uygun olarak (genelde cümle sonunda veya başında).",
          "subsequently → daha sonra (resmi, olay sırası); 'consequently' (sonuç olarak) ile karıştırma!"
        ],
        examples: [
          { en: "Further to our phone call, please find attached the updated quotation.", tr: "Telefon görüşmemize ek olarak, güncel teklifi ekte bulabilirsiniz." },
          { en: "As per your request, we have changed the glass thickness to 12 mm.", tr: "Talebiniz üzerine cam kalınlığını 12 mm olarak değiştirdik." },
          { en: "In light of the recent price increases, we must revise our offer.", tr: "Son fiyat artışları ışığında teklifimizi revize etmeliyiz." },
          { en: "The specifications have changed, and we will adjust the price accordingly.", tr: "Teknik özellikler değişti; fiyatı buna göre ayarlayacağız." }
        ]
      },
      cards: [
        { en: "with reference to", tr: "…e istinaden", ex: "With reference to your email of 3 March, …" },
        { en: "regarding", tr: "…ile ilgili olarak", ex: "Regarding the delivery date, we need two more weeks." },
        { en: "further to", tr: "…e ek olarak, …in devamı olarak", ex: "Further to our meeting, I attach the minutes." },
        { en: "as per", tr: "…uyarınca, …e göre", ex: "As per the contract, payment is due in 30 days." },
        { en: "in light of", tr: "…ışığında", ex: "In light of the test results, we will change the supplier." },
        { en: "accordingly", tr: "buna göre, buna uygun olarak", ex: "Please update the drawings accordingly." },
        { en: "subsequently", tr: "daha sonra, akabinde", ex: "The glass was inspected and subsequently approved." },
        { en: "in view of", tr: "…göz önüne alındığında", ex: "In view of the delay, we will offer a discount." },
        { en: "with regard to", tr: "…konusunda", ex: "With regard to the invoice, there is an error." },
        { en: "prior to", tr: "…den önce (resmi)", ex: "Please inspect the crates prior to unloading." }
      ],
      exercises: [
        { type: "mcq", q: "___ our phone call this morning, please find attached the revised quotation.",
          options: ["Subsequently", "Accordingly", "Further to", "Albeit"], answer: 2,
          explain: "Önceki iletişime atıf → 'Further to'." },
        { type: "mcq", q: "___ your request, we have increased the glass thickness to twelve millimetres.",
          options: ["As per", "Accordingly", "Subsequently", "In spite of"], answer: 0,
          explain: "Talebe uygun olarak → 'As per your request'." },
        { type: "fill", q: "The specifications have changed, so we will adjust the price ___.",
          answers: ["accordingly"], explain: "'accordingly' = buna göre, buna uygun olarak." },
        { type: "mcq", q: "The panes were inspected on Monday and ___ shipped on Wednesday.",
          options: ["consequently", "subsequently", "accordingly", "regarding"], answer: 1,
          explain: "Zaman sırası (daha sonra) → 'subsequently'. 'consequently' sonuç bildirir." },
        { type: "order", answer: "In light of the test results, we will change the design.",
          tr: "Test sonuçları ışığında tasarımı değiştireceğiz.",
          explain: "'In light of + isim' = …ışığında." },
        { type: "match", pairs: [["further to", "önceki iletişime ek olarak"], ["as per", "…uyarınca"], ["in light of", "…ışığında"], ["subsequently", "daha sonra"], ["accordingly", "buna uygun olarak"]],
          explain: "İş yazışması bağlantı ifadeleri." },
        { type: "fill", q: "With ___ to your email of the third of May, we can confirm the order.",
          answers: ["reference", "regard", "respect"], explain: "'With reference to / With regard to' = …e istinaden." },
        { type: "mcq", q: "Which opening is most appropriate for a formal email?",
          options: ["About that glass thing you asked…", "Anyway, the order is ready.", "So, your order, right?", "Regarding your order No. 245, we are pleased to confirm shipment."], answer: 3,
          explain: "Resmi e-postada konu 'Regarding + isim' ile açılır." },
        { type: "listen", text: "Please inspect the crates prior to unloading.",
          tr: "Lütfen boşaltmadan önce sandıkları kontrol edin." },
        { type: "mcq", q: "___ the ongoing port strike, we expect a delay of about one week.",
          options: ["In view of", "Accordingly", "Further", "As per"], answer: 0,
          explain: "Bir durumu göz önüne alarak → 'In view of'." },
        { type: "order", answer: "Further to our meeting, I attach the minutes.",
          tr: "Toplantımızın devamı olarak tutanakları ekte gönderiyorum.",
          explain: "'Further to' e-posta açılışında sık kullanılır." },
        { type: "fill", q: "As ___ the contract, payment is due within thirty days.",
          answers: ["per"], explain: "'as per the contract' = sözleşme uyarınca." },
        { type: "listen", text: "Regarding the delivery date, we need two more weeks.",
          tr: "Teslim tarihiyle ilgili olarak iki haftaya daha ihtiyacımız var." }
      ]
    },
    // ───────────────────────── WEEK 8 ─────────────────────────
    {
      id: "connectors-15",
      title: "Tartışmada bağlama: let alone, having said that…",
      level: "C1",
      week: 8,
      intro: {
        tr: "Doğal bir tartışmada veya sohbette, ana dili İngilizce olanlar fikirlerini güçlendirmek ve dengelemek için kalıplaşmış ifadeler kullanır. 'On top of that / not to mention' ek bir sorunu vurgular. 'Let alone' olumsuz bir cümleden sonra 'bırak …'yı' anlamındadır. 'Having said that / That being said' az önce söylenene denge getirir. 'Mind you' sonradan akla gelen bir kısıtlamadır.",
        points: [
          "On top of that, → üstüne üstlük (genelde olumsuz şeyler eklenir).",
          "not to mention + isim/-ing → …den bahsetmiyorum bile.",
          "let alone → OLUMSUZ cümleden sonra: I can't afford a car, let alone a boat.",
          "Having said that, / That being said, → bununla birlikte, yine de (denge).",
          "Mind you, → gerçi, ama şunu da söyleyeyim (konuşma, İngiliz İngilizcesi).",
          "Not only … but also … → sadece … değil, aynı zamanda … (başta 'Not only' → devrik yapı)."
        ],
        examples: [
          { en: "The delivery was late. On top of that, three panes were broken.", tr: "Teslimat gecikti. Üstüne üstlük üç levha kırıktı." },
          { en: "I can't even boil an egg, let alone cook a whole dinner.", tr: "Yumurta bile haşlayamam, bırak koca bir akşam yemeği pişirmeyi." },
          { en: "The hotel was expensive. Having said that, the view was amazing.", tr: "Otel pahalıydı. Bununla birlikte manzara harikaydı." },
          { en: "Not only is the glass lighter, but it is also stronger.", tr: "Cam sadece daha hafif değil, aynı zamanda daha sağlam." }
        ]
      },
      cards: [
        { en: "on top of that", tr: "üstüne üstlük", ex: "It rained all day. On top of that, I lost my keys." },
        { en: "not to mention", tr: "…den bahsetmiyorum bile", ex: "The glass is light, not to mention cheap." },
        { en: "let alone", tr: "bırak …yı, şöyle dursun", ex: "We can't deliver in four weeks, let alone two." },
        { en: "having said that", tr: "bununla birlikte, yine de", ex: "It's a long flight. Having said that, it's worth it." },
        { en: "that being said", tr: "bununla birlikte", ex: "The price is fair. That being said, we need a better lead time." },
        { en: "mind you", tr: "gerçi, ama şunu da belirteyim", ex: "It's a nice flat. Mind you, it's a bit small." },
        { en: "not only … but also", tr: "sadece … değil, aynı zamanda", ex: "We not only produce the glass but also install it." },
        { en: "as well as", tr: "…nın yanı sıra", ex: "We supply frames as well as glass." },
        { en: "to make matters worse", tr: "işleri daha da kötüleştiren", ex: "To make matters worse, the crane broke down." },
        { en: "after all", tr: "ne de olsa", ex: "Let's give them a chance. After all, they're new." }
      ],
      exercises: [
        { type: "mcq", q: "I can't afford a new car, ___ a yacht!",
          options: ["having said that", "not to mention", "let alone", "on top of that"], answer: 2,
          explain: "Olumsuz cümleden sonra daha uç örnek → 'let alone'." },
        { type: "mcq", q: "The shipment was late. ___, two crates were damaged.",
          options: ["Having said that", "On top of that", "Mind you", "Let alone"], answer: 1,
          explain: "Ek bir olumsuzluk eklemek → 'On top of that,'." },
        { type: "fill", q: "The hotel was expensive. Having ___ that, the service was excellent.",
          answers: ["said"], explain: "'Having said that' = bununla birlikte." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["I can swim well, let alone dive.", "Let alone I can't swim.", "I can't swim, let alone dive.", "I can't swim, let alone I dive well."], answer: 2,
          explain: "'let alone' olumsuz cümleden sonra gelir ve daha zor bir şeyi gösterir." },
        { type: "order", answer: "Not only is the glass lighter, but it is also stronger.",
          tr: "Cam sadece daha hafif değil, aynı zamanda daha sağlam.",
          explain: "Başta 'Not only' → devrik yapı (is the glass)." },
        { type: "match", pairs: [["let alone", "bırak …yı"], ["not to mention", "…den bahsetmiyorum bile"], ["having said that", "bununla birlikte"], ["mind you", "gerçi (konuşma)"], ["after all", "ne de olsa"]],
          explain: "Tartışma ve sohbet bağlantıları." },
        { type: "fill", q: "Our glass is stronger, not to ___ much lighter.",
          answers: ["mention"], explain: "'not to mention' = …den bahsetmiyorum bile." },
        { type: "mcq", q: "\"It's a lovely flat. ___, it's a bit far from the metro.\"",
          options: ["Mind you", "Let alone", "Not to mention", "As well as"], answer: 0,
          explain: "Sonradan akla gelen küçük bir kısıtlama → 'Mind you,'." },
        { type: "listen", text: "We can't deliver in four weeks, let alone two.",
          tr: "Dört haftada teslim edemeyiz, iki hafta şöyle dursun." },
        { type: "mcq", q: "Let's give the new supplier a chance. ___, everyone makes mistakes at the beginning.",
          options: ["Mind you", "Let alone", "On top of that", "After all"], answer: 3,
          explain: "Gerekçe hatırlatmak → 'After all' (ne de olsa)." },
        { type: "order", answer: "That being said, we still need a better lead time.",
          tr: "Bununla birlikte, yine de daha iyi bir teslim süresine ihtiyacımız var.",
          explain: "'That being said' önceki olumlu fikre denge getirir." },
        { type: "fill", q: "It rained all day, and to make matters ___, I lost my umbrella.",
          answers: ["worse"], explain: "'to make matters worse' = işleri daha da kötüleştiren." },
        { type: "listen", text: "Having said that, the view was amazing.",
          tr: "Bununla birlikte manzara harikaydı." }
      ]
    },
    {
      id: "connectors-16",
      title: "C1 bütünlük: the former/the latter & noktalama",
      level: "C1",
      week: 8,
      intro: {
        tr: "C1 seviyesinde metin bütünlüğü (cohesion) sadece bağlaç bilmekle değil, tekrar etmeden geri göndermeyle de sağlanır. 'The former' (ilki) ve 'the latter' (sonuncusu) iki şeyden birine işaret eder. 'This / such / these' önceki fikri özetler. Ayrıca noktalama kritik: 'however, therefore' gibi zarflar iki cümleyi virgülle bağlayamaz; noktalı virgül (;) veya nokta gerekir.",
        points: [
          "the former = iki şeyden ilki; the latter = ikincisi: We offer tempered and laminated glass; the latter is safer.",
          "this + isim (this problem, this approach) → önceki fikrin tamamını özetler.",
          "such + isim → 'bu tür': Such delays are unacceptable.",
          "Noktalama: Cümle; however, cümle.  ✗ Cümle, however, cümle (comma splice).",
          "Tekrardan kaçın: do so, one(s), the same, it/they kullan: We asked them to sign, and they did so.",
          "and/but/so → virgül yeterli; however/therefore/moreover → nokta veya noktalı virgül."
        ],
        examples: [
          { en: "We offer tempered and laminated glass; the latter is safer for bridge windows.", tr: "Temperli ve lamine cam sunuyoruz; ikincisi köprüüstü camları için daha güvenlidir." },
          { en: "Two panes arrived cracked. This problem must not happen again.", tr: "İki levha çatlak geldi. Bu sorun bir daha yaşanmamalı." },
          { en: "The price is competitive; however, the lead time is too long.", tr: "Fiyat rekabetçi; ancak teslim süresi çok uzun." },
          { en: "I invited Tom and Anna; the former came, but the latter didn't.", tr: "Tom ve Anna'yı davet ettim; ilki geldi ama ikincisi gelmedi." }
        ]
      },
      cards: [
        { en: "the former", tr: "(ikisinden) ilki", ex: "Between Rotterdam and Hamburg, we prefer the former." },
        { en: "the latter", tr: "(ikisinden) sonuncusu", ex: "Tea or coffee? I'll have the latter." },
        { en: "this + noun", tr: "bu (önceki fikri özetler)", ex: "This decision will reduce our costs." },
        { en: "such + noun", tr: "bu tür, böyle", ex: "Such problems are rare in our factory." },
        { en: "do so", tr: "bunu yapmak (tekrarı önler)", ex: "If you wish to cancel, please do so in writing." },
        { en: "the same", tr: "aynısı", ex: "Thank you for the offer. We'd like the same next year." },
        { en: "; however,", tr: "; ancak, (noktalı virgülle)", ex: "The sample is good; however, the colour is wrong." },
        { en: "; therefore,", tr: "; bu nedenle, (noktalı virgülle)", ex: "The crane is broken; therefore, loading is delayed." },
        { en: "respectively", tr: "sırasıyla", ex: "Types A and B are 8 mm and 10 mm thick, respectively." },
        { en: "the above", tr: "yukarıdaki (yazıda)", ex: "Please confirm the above by Friday." }
      ],
      exercises: [
        { type: "mcq", q: "We offer two options: tempered and laminated glass. ___ is safer, as it holds together when broken.",
          options: ["The former", "The latter", "Such", "The above"], answer: 1,
          explain: "Kırıldığında bir arada kalan lamine camdır (ikincisi) → 'The latter'." },
        { type: "mcq", q: "Which sentence is punctuated correctly?",
          options: ["The price is good, however, delivery is slow.", "The price is good, however delivery is slow.", "The price is good however delivery is slow.", "The price is good; however, delivery is slow."], answer: 3,
          explain: "'however' iki cümleyi bağlarken önünde noktalı virgül/nokta, arkasında virgül olur." },
        { type: "fill", q: "I invited Tom and Anna. The ___ came, but the latter stayed at home.",
          answers: ["former"], explain: "İki kişiden ilki → 'the former'." },
        { type: "mcq", q: "Two panes arrived cracked last month. ___ delays and damage are unacceptable for our clients.",
          options: ["Same", "So", "Such", "Latter"], answer: 2,
          explain: "'such + çoğul isim' = bu tür …" },
        { type: "fill", q: "If you wish to cancel the order, please do ___ in writing.",
          answers: ["so"], explain: "'do so' fiili tekrar etmeden geri gönderir." },
        { type: "order", answer: "The crane is broken; therefore, loading is delayed.",
          tr: "Vinç bozuk; bu nedenle yükleme gecikti.",
          explain: "'; therefore,' noktalaması." },
        { type: "match", pairs: [["the former", "ilki"], ["the latter", "sonuncusu"], ["respectively", "sırasıyla"], ["do so", "bunu yapmak"], ["such + noun", "bu tür"]],
          explain: "Geri gönderme ve bütünlük araçları." },
        { type: "mcq", q: "Types A and B are eight and ten millimetres thick, ___.",
          options: ["respectively", "accordingly", "subsequently", "namely"], answer: 0,
          explain: "Sıralı eşleştirme → 'respectively' (sırasıyla)." },
        { type: "listen", text: "Tea or coffee? I'll have the latter, please.",
          tr: "Çay mı kahve mi? İkincisini alayım, lütfen." },
        { type: "mcq", q: "Mixed review: ___ the high cost, the shipowner chose laminated glass, ___ it is much safer.",
          options: ["Although / because of", "Despite / since", "Despite / due to", "However / as"], answer: 1,
          explain: "'Despite + isim' ve 'since + cümle'. 'due to' ve 'because of' cümle almaz." },
        { type: "fill", q: "Mixed review: ___ you confirm by Friday, we can't guarantee the delivery date.",
          answers: ["Unless"], explain: "'Unless' = if … not: Cumaya kadar teyit etmezseniz…" },
        { type: "order", answer: "This decision will reduce our costs and save time.",
          tr: "Bu karar maliyetlerimizi düşürecek ve zaman kazandıracak.",
          explain: "'This + isim' önceki fikri özetler." },
        { type: "mcq", q: "Mixed review: The glass is light; ___, it is extremely strong.",
          options: ["albeit", "despite", "in case", "in addition"], answer: 3,
          explain: "Noktalı virgülden sonra ekleme bağlacı → '; in addition,'." },
        { type: "listen", text: "Such problems are very rare in our factory.",
          tr: "Bu tür sorunlar fabrikamızda çok nadirdir." }
      ]
    }
  ]
});
