window.EA_MODULES = window.EA_MODULES || [];
window.EA_MODULES.push({
  id: "conversation",
  title: "Günlük Konuşma",
  icon: "💬",
  color: "#ff8a3d",
  description: "Yeni insanlarla tanışma, small talk, sohbeti sürdürme ve yabancı müşterilerle sosyalleşme için doğal konuşma kalıpları.",
  units: [
    // ───────────────────────── WEEK 1 ─────────────────────────
    {
      id: "conversation-01",
      title: "Yeni biriyle tanışmak",
      level: "B1+",
      week: 1,
      intro: {
        tr: "Tanışmada 'Nice to meet you' sadece başlangıçtır. Sohbeti açmak için hemen kısa, açık uçlu bir soru sor: kişiyi oraya ne getirdi, ev sahibini nereden tanıyor, ne iş yapıyor. Adı duyduğunda tekrar etmek hem hatırlamanı sağlar hem de samimi görünür.",
        points: [
          "Adı tekrar et: 'Nice to meet you, Mark.' — kişi kendini önemli hisseder.",
          "Tanışmadan sonra hemen bir soru sor: 'So what brings you here?' / 'How do you know Sarah?'",
          "Adı unuttuysan: 'Sorry, I didn't catch your name.' — çok doğal ve kibar.",
          "Konuşma açabileceğin sorular: 'Is this your first time here?', 'Have you come far?', 'How are you finding the event so far?'",
          "Kendini tanıtırken sadece adını değil, küçük bir bilgi ekle: 'I'm Oğuz — I work with Sarah.'"
        ],
        examples: [
          { en: "Hi, I'm Oğuz. I don't think we've met.", tr: "Merhaba, ben Oğuz. Sanırım tanışmadık." },
          { en: "So what brings you here tonight?", tr: "Peki bu akşam seni buraya ne getirdi?" },
          { en: "How do you know the host?", tr: "Ev sahibini nereden tanıyorsun?" },
          { en: "Sorry, I didn't catch your name.", tr: "Pardon, adınızı tam duyamadım." },
          { en: "You must be Mr. Jensen from the shipyard. Welcome to Istanbul!", tr: "Tersaneden Bay Jensen olmalısınız. İstanbul'a hoş geldiniz!" }
        ]
      },
      cards: [
        { en: "I don't think we've met.", tr: "Sanırım tanışmadık.", ex: "Hi, I don't think we've met. I'm Oğuz." },
        { en: "What brings you here?", tr: "Seni buraya ne getirdi?", ex: "So what brings you to the trade fair?" },
        { en: "How do you know...?", tr: "...'i nereden tanıyorsun?", ex: "How do you know Sarah?" },
        { en: "I didn't catch your name.", tr: "Adınızı tam duyamadım.", ex: "Sorry, I didn't catch your name." },
        { en: "Is this your first time here?", tr: "Buraya ilk gelişin mi?", ex: "Is this your first time in Istanbul?" },
        { en: "I've heard a lot about you.", tr: "Senden çok bahsedildi / Hakkında çok şey duydum.", ex: "Nice to finally meet you — I've heard a lot about you." },
        { en: "Let me introduce you to...", tr: "Seni ...'e tanıştırayım.", ex: "Let me introduce you to our production manager." },
        { en: "Have you two met?", tr: "Siz ikiniz tanışıyor musunuz?", ex: "Anna, have you two met? This is Mark." },
        { en: "Nice to put a face to the name.", tr: "Sonunda yüz yüze görüşmek ne güzel (e-postalardan tanıdığımız biri için).", ex: "After all those emails, it's nice to put a face to the name." },
        { en: "How are you finding it so far?", tr: "Şimdiye kadar nasıl buldun?", ex: "How are you finding the conference so far?" },
        { en: "Have you come far?", tr: "Uzaktan mı geldiniz?", ex: "Welcome! Have you come far?" }
      ],
      exercises: [
        { type: "mcq", q: "A: ‘Hi, I'm Lena.’ — What's the most natural reply?",
          options: ["Nice to meet you, Lena. I'm Oğuz.", "I am fine, thank you.", "Yes, I am Oğuz.", "Meeting you is nice."],
          answer: 0, explain: "Adı tekrar edip kendini tanıtmak en doğal karşılıktır." },
        { type: "mcq", q: "You meet someone at a friend's party. Which question best opens the conversation?",
          options: ["What is your salary?", "How old are you?", "So how do you know Tom?", "Are you married?"],
          answer: 2, explain: "Ev sahibini nereden tanıdığını sormak güvenli ve klasik bir açılıştır." },
        { type: "fill", q: "Sorry, I didn't ___ your name.", answers: ["catch"], hint: "duymak / yakalamak",
          explain: "'I didn't catch your name' = adınızı tam duyamadım." },
        { type: "order", answer: "So what brings you to Istanbul?", tr: "Peki seni İstanbul'a ne getirdi?",
          explain: "'What brings you to...?' = Seni ...'e ne getirdi?" },
        { type: "mcq", q: "You finally meet a client you've emailed for months. What do you say?",
          options: ["Nice to meet you for the first time ever.", "It's nice to put a face to the name.", "Finally you have a face.", "I know your email."],
          answer: 1, explain: "'Put a face to the name' — yazıştığın biriyle ilk kez yüz yüze görüşünce kullanılır." },
        { type: "match", pairs: [["Have you come far?", "Uzaktan mı geldiniz?"], ["Have you two met?", "Siz tanışıyor musunuz?"], ["I've heard a lot about you.", "Hakkında çok şey duydum."], ["Let me introduce you to...", "Seni ...'e tanıştırayım."]],
          explain: "Tanışma kalıplarını eşleştir." },
        { type: "fill", q: "How are you ___ the conference so far?", answers: ["finding"], hint: "find + -ing",
          explain: "'How are you finding X?' = X'i nasıl buluyorsun? (deneyim sorusu)" },
        { type: "listen", text: "I don't think we've met before.", tr: "Daha önce tanıştığımızı sanmıyorum." },
        { type: "mcq", q: "A: ‘I'm here with the Norwegian shipyard delegation.’ — Best follow-up?",
          options: ["OK.", "Norway is cold.", "Why?", "Oh, nice! Is this your first time in Turkey?"],
          answer: 3, explain: "Bilgiye ilgi gösterip ilgili bir soruyla devam etmek sohbeti açar." },
        { type: "order", answer: "Let me introduce you to our sales director", tr: "Sizi satış direktörümüzle tanıştırayım.",
          explain: "'Let me introduce you to...' resmi tanıştırma kalıbıdır." },
        { type: "fill", q: "Nice to finally meet you. I've ___ a lot about you.", answers: ["heard"], hint: "hear (V3)",
          explain: "Present perfect: I've heard." },
        { type: "listen", text: "How do you know the host?", tr: "Ev sahibini nereden tanıyorsun?" }
      ]
    },
    {
      id: "conversation-02",
      title: "Kendinden bahsetmek",
      level: "B1+",
      week: 1,
      intro: {
        tr: "'Where are you from?' veya 'What do you do?' sorusuna tek kelimeyle cevap verme. Bir cümle bilgi + bir küçük detay ver, sonra soruyu geri sor: 'How about you?'. Böylece sohbet top gibi iki taraf arasında gider.",
        points: [
          "Memleket: 'I'm originally from Trabzon, but I've lived in Istanbul for ten years.'",
          "İş: 'I work in sales for a marine glass manufacturer.' — 'I work for + şirket', 'I work in + alan'.",
          "İşini basitçe açıkla: 'We make windows for ships and yachts.'",
          "Soruyu geri çevir: 'How about you?' / 'What about you?' / 'And yourself?'",
          "Konuşma açabileceğin sorular: 'What do you do?', 'Where's home for you?', 'How long have you been in your job?'"
        ],
        examples: [
          { en: "I'm originally from Izmir, but I live in Istanbul now.", tr: "Aslen İzmirliyim ama şimdi İstanbul'da yaşıyorum." },
          { en: "I work for a company that makes glass for ships.", tr: "Gemiler için cam üreten bir şirkette çalışıyorum." },
          { en: "I've been in the industry for about six years.", tr: "Yaklaşık altı yıldır bu sektördeyim." },
          { en: "Basically, I deal with our international clients.", tr: "Kısacası, uluslararası müşterilerimizle ilgileniyorum." },
          { en: "What about you? What do you do?", tr: "Peki ya sen? Ne iş yapıyorsun?" }
        ]
      },
      cards: [
        { en: "I'm originally from...", tr: "Aslen ...'liyim.", ex: "I'm originally from Bursa." },
        { en: "I work in sales.", tr: "Satışta çalışıyorum.", ex: "I work in sales for a glass manufacturer." },
        { en: "I work for...", tr: "...'de/için çalışıyorum (şirket).", ex: "I work for a marine glass company." },
        { en: "I'm in charge of...", tr: "...'den sorumluyum.", ex: "I'm in charge of export orders." },
        { en: "I deal with...", tr: "...ile ilgileniyorum.", ex: "I mostly deal with shipyards in Europe." },
        { en: "I grew up in...", tr: "...'de büyüdüm.", ex: "I grew up in a small town near the coast." },
        { en: "How about you?", tr: "Peki ya sen?", ex: "I'm from Turkey. How about you?" },
        { en: "Where's home for you?", tr: "Nerelisin / Evin neresi?", ex: "So where's home for you?" },
        { en: "I've been doing it for...", tr: "...dır bunu yapıyorum.", ex: "I've been doing it for about five years." },
        { en: "In my free time, I...", tr: "Boş zamanlarımda ...", ex: "In my free time, I like hiking." },
        { en: "Basically, ...", tr: "Kısacası / Temelde ...", ex: "Basically, we make windows for ships." }
      ],
      exercises: [
        { type: "mcq", q: "A: ‘So, what do you do?’ — Most natural answer?",
          options: ["I am doing work.", "I work in sales for a marine glass company.", "I do sales job.", "My job is work."],
          answer: 1, explain: "'I work in + alan / for + şirket' doğal kalıptır." },
        { type: "fill", q: "I'm ___ from Trabzon, but I live in Istanbul now.", answers: ["originally"], hint: "aslen",
          explain: "'Originally from' = aslen ...'li." },
        { type: "mcq", q: "Choose the correct sentence.",
          options: ["I work for a glass company.", "I work in a glass company's for.", "I work at sales a company.", "I am work for a company."],
          answer: 0, explain: "work for + şirket; work in + alan (sales, IT)." },
        { type: "order", answer: "I'm in charge of our export orders", tr: "İhracat siparişlerimizden sorumluyum.",
          explain: "'Be in charge of' = sorumlu olmak." },
        { type: "fill", q: "I've been in this industry ___ about six years.", answers: ["for"], hint: "süre",
          explain: "Süre bildirirken 'for' kullanılır." },
        { type: "mcq", q: "You've just told someone where you're from. How do you keep the ball rolling?",
          options: ["Goodbye.", "OK, that's all.", "And yourself? Where's home for you?", "Do you understand?"],
          answer: 2, explain: "Soruyu karşı tarafa geri çevirmek sohbeti sürdürür." },
        { type: "match", pairs: [["I grew up in...", "...'de büyüdüm"], ["I deal with...", "...ile ilgilenirim"], ["I'm in charge of...", "...'den sorumluyum"], ["Where's home for you?", "Nerelisin?"], ["Basically", "Kısacası"]],
          explain: "Kendini anlatma kalıpları." },
        { type: "listen", text: "Basically, we make windows for ships and yachts.", tr: "Kısacası, gemiler ve yatlar için pencere yapıyoruz." },
        { type: "mcq", q: "A client asks: ‘What exactly does your company make?’ — Best simple explanation?",
          options: ["Glass.", "We are glass.", "Production of glass is ours.", "We make toughened and laminated windows for ships."],
          answer: 3, explain: "Kısa ama somut bir açıklama en iyisidir." },
        { type: "order", answer: "What about you? What do you do?", tr: "Peki ya sen? Ne iş yaparsın?",
          explain: "Soruyu geri çevirme kalıbı." },
        { type: "fill", q: "I ___ up in a small town near the Black Sea.", answers: ["grew"], hint: "grow (V2)",
          explain: "'Grow up' = büyümek; geçmiş: grew up." },
        { type: "listen", text: "I'm originally from Izmir, but I live here now.", tr: "Aslen İzmirliyim ama şimdi burada yaşıyorum." }
      ]
    },
    // ───────────────────────── WEEK 2 ─────────────────────────
    {
      id: "conversation-03",
      title: "Güvenli small talk konuları",
      level: "B1+",
      week: 2,
      intro: {
        tr: "Small talk; hava, yolculuk, yemek, hafta sonu ve bulunduğun mekan gibi herkesin rahatça konuşabileceği konulardır. Amaç bilgi değil, bağ kurmaktır. İlk tanışmada siyaset, din, maaş, yaş ve kilo gibi konulardan kaçın.",
        points: [
          "Hava: 'Lovely weather today, isn't it?' / 'Can you believe this rain?'",
          "Yolculuk: 'How was your flight?' / 'Did you find the place OK?'",
          "Mekan / etkinlik: 'This place is great, isn't it?' / 'Have you tried the food yet?'",
          "Hafta sonu: 'Got any plans for the weekend?' / 'Did you do anything nice at the weekend?'",
          "Kaçın: politika, din, maaş ('How much do you earn?'), yaş, kilo, medeni durum.",
          "Konuşma açabileceğin konular: hava, yolculuk, yemek, mekan, hafta sonu planları, tatil, şehir önerileri."
        ],
        examples: [
          { en: "Lovely day, isn't it?", tr: "Güzel bir gün, değil mi?" },
          { en: "How was your flight? Not too long, I hope.", tr: "Uçuşunuz nasıldı? Umarım çok uzun sürmemiştir." },
          { en: "Have you tried the baklava yet? It's amazing.", tr: "Baklavayı denedin mi? Harika." },
          { en: "Got any plans for the weekend?", tr: "Hafta sonu için planın var mı?" },
          { en: "It's a great venue — have you been here before?", tr: "Harika bir mekan — daha önce gelmiş miydin?" }
        ]
      },
      cards: [
        { en: "Lovely weather, isn't it?", tr: "Hava çok güzel, değil mi?", ex: "Lovely weather today, isn't it?" },
        { en: "Can you believe this rain?", tr: "Şu yağmura inanabiliyor musun?", ex: "Can you believe this rain? It hasn't stopped all week." },
        { en: "How was your flight?", tr: "Uçuşun nasıldı?", ex: "Welcome! How was your flight?" },
        { en: "Did you find the place OK?", tr: "Yeri kolay buldun mu?", ex: "Did you find the place OK? It's a bit hidden." },
        { en: "Got any plans for the weekend?", tr: "Hafta sonu için planın var mı?", ex: "Got any plans for the weekend?" },
        { en: "Have you tried the...?", tr: "...'i denedin mi?", ex: "Have you tried the grilled fish?" },
        { en: "It's a bit chilly.", tr: "Biraz serin / soğuk.", ex: "It's a bit chilly out there today." },
        { en: "Is it always this busy?", tr: "Hep bu kadar kalabalık mı?", ex: "Is it always this busy here on Fridays?" },
        { en: "Did you do anything nice?", tr: "Güzel bir şey yaptın mı?", ex: "Did you do anything nice at the weekend?" },
        { en: "How are you settling in?", tr: "Alışabildin mi / Yerleşebildin mi?", ex: "You arrived on Monday — how are you settling in?" },
        { en: "Not too bad, thanks.", tr: "Fena değil, teşekkürler.", ex: "How's your week going? — Not too bad, thanks." }
      ],
      exercises: [
        { type: "mcq", q: "Which topic is SAFE for small talk with someone you just met?",
          options: ["Their salary", "Their religion", "The food at the event", "Who they voted for"],
          answer: 2, explain: "Yemek, hava, mekan gibi konular güvenlidir." },
        { type: "mcq", q: "A: ‘Lovely weather today, isn't it?’ — Most natural reply?",
          options: ["Yes, the weather is.", "Isn't it? Perfect for a walk.", "No.", "Weather is a topic."],
          answer: 1, explain: "Kısa onay + küçük bir yorum sohbeti sürdürür." },
        { type: "fill", q: "Got any ___ for the weekend?", answers: ["plans"], hint: "planlar",
          explain: "'Got any plans for the weekend?' gündelik, kısaltılmış soru." },
        { type: "order", answer: "Did you find the place OK?", tr: "Yeri kolayca bulabildin mi?",
          explain: "Mekana gelen birine sorulan klasik soru." },
        { type: "mcq", q: "You pick up a client at the airport. What's the best first question?",
          options: ["How was your flight?", "How much was your ticket?", "Why are you late?", "Are you tired of work?"],
          answer: 0, explain: "Havaalanında ilk soru: uçuş nasıldı." },
        { type: "match", pairs: [["chilly", "serin / soğuk"], ["settle in", "alışmak, yerleşmek"], ["venue", "mekan, etkinlik yeri"], ["busy", "kalabalık / yoğun"]],
          explain: "Small talk kelimeleri." },
        { type: "fill", q: "Have you ___ the baklava yet? It's amazing.", answers: ["tried"], hint: "try (V3)",
          explain: "'Have you tried...?' = ...'i denedin mi?" },
        { type: "listen", text: "Can you believe this rain?", tr: "Şu yağmura inanabiliyor musun?" },
        { type: "mcq", q: "Which question should you AVOID with a new business contact?",
          options: ["Is this your first time in Turkey?", "How's your hotel?", "Have you tried Turkish coffee?", "How much do you earn?"],
          answer: 3, explain: "Maaş sormak özel ve kaba kabul edilir." },
        { type: "order", answer: "Did you do anything nice at the weekend?", tr: "Hafta sonu güzel bir şey yaptın mı?",
          explain: "Pazartesi sabahı ofiste klasik small talk." },
        { type: "fill", q: "You arrived on Monday — how are you ___ in?", answers: ["settling"], hint: "settle + -ing",
          explain: "'Settle in' = yeni yere alışmak." },
        { type: "listen", text: "Is it always this busy here?", tr: "Burası hep bu kadar kalabalık mı?" }
      ]
    },
    {
      id: "conversation-04",
      title: "Sohbeti sürdürmek",
      level: "B1+",
      week: 2,
      intro: {
        tr: "İyi bir sohbetçi çok konuşan değil, iyi soru soran ve ilgi gösteren kişidir. Karşındaki bir şey anlattığında kısa bir tepki ver (Really? / That sounds great!) ve ardından bir takip sorusu sor (How come? / What was that like?). Bu 'tepki + soru' formülü sohbeti canlı tutar.",
        points: [
          "Tepki ver: 'Really?', 'Oh, nice!', 'That sounds amazing / tough / interesting.'",
          "Takip sorusu sor: 'How come?', 'What was that like?', 'How did that happen?', 'What made you decide to...?'",
          "Detay iste: 'Tell me more about it.' / 'In what way?'",
          "Ortak nokta bul: 'Me too!' / 'Same here.' / 'Oh, I've always wanted to go there.'",
          "Kapalı (Yes/No) yerine açık uçlu sorular sor: 'Do you like it?' yerine 'What do you like about it?'"
        ],
        examples: [
          { en: "A: I just got back from Japan. B: Really? What was that like?", tr: "A: Japonya'dan yeni döndüm. B: Gerçekten mi? Nasıldı?" },
          { en: "That sounds exhausting! How did you manage?", tr: "Kulağa çok yorucu geliyor! Nasıl başa çıktın?" },
          { en: "How come you moved to Rotterdam?", tr: "Nasıl oldu da Rotterdam'a taşındın?" },
          { en: "What made you decide to become an engineer?", tr: "Mühendis olmaya seni ne karar verdirdi?" },
          { en: "Oh, same here! I love sailing too.", tr: "Ben de öyle! Ben de yelkenciliği çok severim." }
        ]
      },
      cards: [
        { en: "How come?", tr: "Nasıl yani? / Neden?", ex: "You quit your job? How come?" },
        { en: "What was that like?", tr: "Nasıldı (deneyim olarak)?", ex: "You lived in Norway? What was that like?" },
        { en: "That sounds...", tr: "Kulağa ... geliyor.", ex: "That sounds amazing!" },
        { en: "Tell me more about it.", tr: "Biraz daha anlat.", ex: "A new project? Tell me more about it." },
        { en: "What made you decide to...?", tr: "Seni ...'e ne karar verdirdi?", ex: "What made you decide to move here?" },
        { en: "Same here.", tr: "Bende de öyle / Ben de.", ex: "I hate early flights. — Same here." },
        { en: "In what way?", tr: "Ne açıdan?", ex: "It was different. — In what way?" },
        { en: "I've always wanted to...", tr: "Hep ...'mak istemişimdir.", ex: "I've always wanted to visit Iceland." },
        { en: "How did that happen?", tr: "Bu nasıl oldu?", ex: "You met the CEO on a plane? How did that happen?" },
        { en: "No way!", tr: "Olamaz! / Yok artık!", ex: "No way! That's a crazy coincidence." },
        { en: "What do you like most about it?", tr: "En çok neyini seviyorsun?", ex: "What do you like most about living in Oslo?" },
        { en: "Oh, really?", tr: "Aa, gerçekten mi?", ex: "Oh, really? I didn't know that." }
      ],
      exercises: [
        { type: "mcq", q: "A: ‘I spent two years working in Singapore.’ — Best response?",
          options: ["OK.", "Singapore is in Asia.", "Really? What was that like?", "I didn't."],
          answer: 2, explain: "Tepki + takip sorusu formülü sohbeti sürdürür." },
        { type: "fill", q: "You moved to Hamburg? How ___?", answers: ["come"], hint: "Neden? (gündelik)",
          explain: "'How come?' = Neden / nasıl oldu? (gündelik)" },
        { type: "mcq", q: "A: ‘We sailed from Bodrum to Greece last summer.’ — Which reply shows the most interest?",
          options: ["Nice.", "That sounds amazing! How long did it take?", "Yes.", "Greece is near."],
          answer: 1, explain: "Coşkulu tepki + soru en iyi ilgi göstergesidir." },
        { type: "order", answer: "What made you decide to become an engineer?", tr: "Mühendis olmaya nasıl karar verdin?",
          explain: "'What made you decide to...?' motivasyon sorusu." },
        { type: "match", pairs: [["How come?", "Neden ki?"], ["Same here.", "Ben de öyle."], ["In what way?", "Ne açıdan?"], ["Tell me more.", "Biraz daha anlat."], ["No way!", "Yok artık!"]],
          explain: "İlgi gösterme kalıpları." },
        { type: "mcq", q: "Which is an OPEN question that keeps the conversation going?",
          options: ["Do you like your job?", "Is it hard?", "Are you happy?", "What do you enjoy most about your job?"],
          answer: 3, explain: "Açık uçlu sorular uzun cevaplar getirir." },
        { type: "fill", q: "That ___ exhausting! How did you manage?", answers: ["sounds"], hint: "kulağa geliyor",
          explain: "'That sounds + sıfat' = kulağa ... geliyor." },
        { type: "listen", text: "Really? Tell me more about it.", tr: "Gerçekten mi? Biraz daha anlat." },
        { type: "mcq", q: "A client says: ‘I love sailing — I go almost every weekend.’ You love it too. What do you say?",
          options: ["Oh, same here! Where do you usually sail?", "Good for you.", "I see.", "Sailing is a sport."],
          answer: 0, explain: "Ortak noktayı belirtip soru sormak bağ kurar." },
        { type: "order", answer: "I've always wanted to go there", tr: "Oraya hep gitmek istemişimdir.",
          explain: "'I've always wanted to...' ilgi ve ortak nokta göstermek için." },
        { type: "fill", q: "You lived in Norway? What was that ___?", answers: ["like"], hint: "nasıldı",
          explain: "'What was it/that like?' = Nasıldı?" },
        { type: "listen", text: "How did that happen?", tr: "Bu nasıl oldu?" },
        { type: "mcq", q: "A: ‘The project was really different from what I expected.’ — Best follow-up?",
          options: ["Different is good.", "Oh? In what way?", "I expected it.", "Yes, projects."],
          answer: 1, explain: "'In what way?' detay ister ve konuşmayı derinleştirir." }
      ]
    },
    // ───────────────────────── WEEK 3 ─────────────────────────
    {
      id: "conversation-05",
      title: "Hobiler, spor, dizi ve müzik",
      level: "B2",
      week: 3,
      intro: {
        tr: "Hobiler sohbetin en kolay derinleşen konusudur. 'I like...' yerine daha zengin ifadeler kullan: 'I'm really into...', 'I'm a big fan of...', 'It's not really my thing.' Tercih belirtirken 'I'd rather...' ve 'I prefer X to Y' kalıplarını kullan.",
        points: [
          "Sevdiğin şey: 'I'm really into hiking.' / 'I'm a big fan of jazz.' / 'I'm hooked on this series.'",
          "Sevmediğin şey (kibar): 'It's not really my thing.' / 'I'm not a big fan of...'",
          "Tercih: 'I prefer football to basketball.' / 'I'd rather stay in than go out tonight.'",
          "Öneri iste/ver: 'Are you watching anything good at the moment?' / 'You should check out...'",
          "Konuşma açabileceğin sorular: 'What do you do to unwind?', 'Do you follow any sports?', 'Read anything good lately?', 'What kind of music are you into?'"
        ],
        examples: [
          { en: "I'm really into sailing at the moment.", tr: "Şu sıralar yelkene çok sardım." },
          { en: "Football's not really my thing, to be honest.", tr: "Açıkçası futbol pek bana göre değil." },
          { en: "Are you watching anything good at the moment?", tr: "Şu sıralar güzel bir şey izliyor musun?" },
          { en: "You should definitely check it out.", tr: "Kesinlikle bir göz atmalısın." },
          { en: "I'd rather watch a match live than on TV.", tr: "Maçı televizyondan izlemektense canlı izlemeyi tercih ederim." }
        ]
      },
      cards: [
        { en: "I'm really into...", tr: "...'e çok meraklıyım / sardım.", ex: "I'm really into photography these days." },
        { en: "I'm a big fan of...", tr: "...'in büyük hayranıyım.", ex: "I'm a big fan of Turkish films." },
        { en: "It's not really my thing.", tr: "Pek bana göre değil.", ex: "Golf? It's not really my thing." },
        { en: "I'm hooked on...", tr: "...'e bağımlı oldum (dizi vb.).", ex: "I'm hooked on this new crime series." },
        { en: "I'd rather...", tr: "...'yı tercih ederim.", ex: "I'd rather stay in tonight." },
        { en: "I prefer X to Y.", tr: "X'i Y'ye tercih ederim.", ex: "I prefer tea to coffee." },
        { en: "to unwind", tr: "rahatlamak, kafa dağıtmak", ex: "What do you do to unwind after work?" },
        { en: "You should check out...", tr: "...'e bir göz atmalısın.", ex: "You should check out that new podcast." },
        { en: "Do you follow any sports?", tr: "Herhangi bir sporu takip ediyor musun?", ex: "Do you follow any sports? Football, maybe?" },
        { en: "binge-watch", tr: "dizi maratonu yapmak", ex: "I binge-watched the whole season in two days." },
        { en: "I used to... but...", tr: "Eskiden ...'dım ama ...", ex: "I used to play basketball, but I stopped after university." },
        { en: "take up (a hobby)", tr: "(bir hobiye) başlamak", ex: "I took up swimming last year." }
      ],
      exercises: [
        { type: "mcq", q: "A: ‘Do you play golf?’ You don't like it. Most natural polite answer?",
          options: ["No, golf is bad.", "I hate it.", "Not really — it's not really my thing.", "Never ever."],
          answer: 2, explain: "'It's not really my thing' kibar ve doğal bir reddetmedir." },
        { type: "fill", q: "I'm really ___ hiking at the moment.", answers: ["into"], hint: "be into",
          explain: "'Be into something' = bir şeye meraklı olmak." },
        { type: "fill", q: "I prefer football ___ basketball.", answers: ["to"], hint: "prefer X ... Y",
          explain: "'Prefer X to Y' — 'than' değil 'to'." },
        { type: "order", answer: "What do you do to unwind after work?", tr: "İşten sonra kafa dağıtmak için ne yaparsın?",
          explain: "'Unwind' = rahatlamak; hobi sormanın doğal yolu." },
        { type: "mcq", q: "Choose the correct sentence.",
          options: ["I'd rather to stay home.", "I'd rather stay home tonight.", "I'd rather staying home.", "I rather stay home."],
          answer: 1, explain: "'I'd rather + yalın fiil' (to yok)." },
        { type: "match", pairs: [["take up", "(hobiye) başlamak"], ["binge-watch", "dizi maratonu yapmak"], ["unwind", "rahatlamak"], ["be hooked on", "bağımlı olmak"], ["check out", "göz atmak"]],
          explain: "Hobi kelimeleri." },
        { type: "mcq", q: "A client from Italy says he loves football. Best follow-up?",
          options: ["Football is popular.", "OK, me no.", "Which team do you support?", "Why?"],
          answer: 2, explain: "'Which team do you support?' futbol sohbetini açar." },
        { type: "listen", text: "Are you watching anything good at the moment?", tr: "Şu sıralar güzel bir şey izliyor musun?" },
        { type: "fill", q: "I ___ up swimming last year and I love it.", answers: ["took"], hint: "take up (geçmiş)",
          explain: "'Take up' geçmiş zaman: took up." },
        { type: "order", answer: "You should definitely check out this series", tr: "Bu diziye kesinlikle bir göz atmalısın.",
          explain: "Öneri: 'You should check out...'" },
        { type: "mcq", q: "A: ‘Read anything good lately?’ — Most natural reply?",
          options: ["Yes, I'm halfway through a great thriller, actually.", "Yes, I read.", "Reading is good.", "Lately yes."],
          answer: 0, explain: "Somut detay vermek sohbeti besler." },
        { type: "listen", text: "I used to play tennis, but I stopped.", tr: "Eskiden tenis oynardım ama bıraktım." }
      ]
    },
    {
      id: "conversation-06",
      title: "Seyahat, şehirler ve Türk kültürü",
      level: "B2",
      week: 3,
      intro: {
        tr: "Yabancı misafirler Türkiye'ye geldiğinde sana mutlaka yer, yemek ve kültür soracaklar. Öneri yaparken 'You should...', 'It's well worth a visit', 'Make sure you try...' gibi kalıplar kullan. Türk yemeklerini ve geleneklerini basit benzetmelerle açıkla: 'It's a bit like...'",
        points: [
          "Öneri: 'You should definitely visit...' / 'It's well worth a visit.' / 'Make sure you try...'",
          "Uyarı: 'Avoid it at rush hour.' / 'It can get pretty crowded.' / 'It's a bit of a tourist trap.'",
          "Açıklama: 'It's a bit like... but...' / 'It's basically...' / 'It's made with...'",
          "Kültür: 'In Turkey, we usually...' / 'It's a tradition to...' / 'It's considered polite to...'",
          "Konuşma açabileceğin sorular: 'Where's the best place you've ever travelled to?', 'Have you had a chance to look around?', 'What's your hometown famous for?'"
        ],
        examples: [
          { en: "If you have time, the Bosphorus ferry is well worth it.", tr: "Vaktin olursa Boğaz vapuru kesinlikle değer." },
          { en: "Make sure you try simit — it's a bit like a sesame bagel.", tr: "Simidi mutlaka dene — susamlı bir bagele benziyor." },
          { en: "Turkish breakfast is basically a huge spread of small dishes.", tr: "Türk kahvaltısı temelde birçok küçük tabaktan oluşan büyük bir sofradır." },
          { en: "Grand Bazaar is great, but it's a bit of a tourist trap.", tr: "Kapalıçarşı harika ama biraz turist tuzağı." },
          { en: "In Turkey, it's common to offer guests tea.", tr: "Türkiye'de misafirlere çay ikram etmek yaygındır." }
        ]
      },
      cards: [
        { en: "It's well worth a visit.", tr: "Görmeye kesinlikle değer.", ex: "Cappadocia is well worth a visit." },
        { en: "Make sure you try...", tr: "...'i mutlaka dene.", ex: "Make sure you try the künefe." },
        { en: "It's a bit like...", tr: "Biraz ...'e benziyor.", ex: "Ayran is a bit like a salty yoghurt drink." },
        { en: "a tourist trap", tr: "turist tuzağı (pahalı, turistik yer)", ex: "That restaurant is a bit of a tourist trap." },
        { en: "off the beaten track", tr: "turistik olmayan, keşfedilmemiş", ex: "If you want something off the beaten track, try Şirince." },
        { en: "It can get pretty crowded.", tr: "Epey kalabalık olabiliyor.", ex: "Taksim can get pretty crowded at weekends." },
        { en: "It's famous for...", tr: "...ile ünlüdür.", ex: "Gaziantep is famous for its baklava." },
        { en: "Have you had a chance to look around?", tr: "Etrafı gezme fırsatın oldu mu?", ex: "Have you had a chance to look around Istanbul yet?" },
        { en: "It's considered polite to...", tr: "...mak kibar kabul edilir.", ex: "It's considered polite to take your shoes off at home." },
        { en: "If I were you, I'd...", tr: "Senin yerinde olsam ...'rdım.", ex: "If I were you, I'd take the ferry instead of a taxi." },
        { en: "rush hour", tr: "trafiğin yoğun olduğu saat", ex: "Avoid the bridge at rush hour." }
      ],
      exercises: [
        { type: "mcq", q: "A visiting client asks: ‘Any tips for my free afternoon?’ — Best answer?",
          options: ["Istanbul is big.", "If I were you, I'd take a Bosphorus ferry — it's well worth it.", "I don't know.", "Go somewhere."],
          answer: 1, explain: "Somut öneri + 'well worth it' doğal ve yardımcı." },
        { type: "fill", q: "Make ___ you try the baklava while you're here.", answers: ["sure"], hint: "mutlaka",
          explain: "'Make sure you...' = mutlaka ...'" },
        { type: "mcq", q: "How do you explain ‘ayran’ to a foreigner?",
          options: ["It's ayran.", "It's Turkish milk.", "It's a bit like a salty yoghurt drink.", "It's white."],
          answer: 2, explain: "'It's a bit like...' bilinen bir şeye benzeterek açıklar." },
        { type: "order", answer: "It can get pretty crowded at weekends", tr: "Hafta sonları epey kalabalık olabiliyor.",
          explain: "'Can get + sıfat' = ...olabiliyor." },
        { type: "match", pairs: [["tourist trap", "turist tuzağı"], ["off the beaten track", "turistik olmayan"], ["rush hour", "yoğun trafik saati"], ["well worth a visit", "görülmeye değer"]],
          explain: "Seyahat ifadeleri." },
        { type: "fill", q: "Gaziantep is famous ___ its baklava.", answers: ["for"], hint: "edat",
          explain: "'Famous for' = ...ile ünlü." },
        { type: "mcq", q: "A: ‘Is it rude to refuse tea in Turkey?’ — Best answer?",
          options: ["Not at all, but it's considered polite to accept at least one glass.", "Yes, very rude!", "Tea is tea.", "I don't drink."],
          answer: 0, explain: "Kültürü nazikçe açıklar: 'It's considered polite to...'" },
        { type: "listen", text: "Have you had a chance to look around?", tr: "Etrafı gezme fırsatın oldu mu?" },
        { type: "order", answer: "If I were you, I'd avoid the bridge at rush hour", tr: "Senin yerinde olsam yoğun saatte köprüden kaçınırdım.",
          explain: "Tavsiye: 'If I were you, I'd...'" },
        { type: "mcq", q: "A: ‘I want to see the real Turkey, not just tourist places.’ — Best reply?",
          options: ["Then stay at the hotel.", "Turkey is real.", "Real places are far.", "Then try somewhere off the beaten track, like Şirince."],
          answer: 3, explain: "'Off the beaten track' turistik olmayan yerler için." },
        { type: "fill", q: "Turkish breakfast is ___ a huge spread of small dishes.", answers: ["basically"], hint: "temelde",
          explain: "'Basically' bir şeyi basitçe açıklarken kullanılır." },
        { type: "listen", text: "Cappadocia is well worth a visit.", tr: "Kapadokya görülmeye kesinlikle değer." }
      ]
    },
    // ───────────────────────── WEEK 4 ─────────────────────────
    {
      id: "conversation-07",
      title: "Fikir belirtmek, katılmak, kibarca karşı çıkmak",
      level: "B2",
      week: 4,
      intro: {
        tr: "İngilizcede doğrudan 'You're wrong' demek kaba kaçar. Karşı çıkarken önce karşı tarafın fikrini kabul et, sonra 'but' ile kendi görüşünü yumuşakça ekle. Fikir belirtirken 'I think' dışında 'If you ask me', 'The way I see it', 'Personally, ...' gibi ifadeleri kullan.",
        points: [
          "Fikir: 'Personally, I think...' / 'If you ask me...' / 'The way I see it...' / 'I'd say...'",
          "Katılma: 'Absolutely.' / 'I couldn't agree more.' / 'That's a good point.' / 'Exactly!'",
          "Kısmen katılma: 'I see your point, but...' / 'That's true to some extent, but...'",
          "Kibar karşı çıkma: 'I'm not so sure about that.' / 'I see it a bit differently.' / 'I know what you mean, but...'",
          "İş ortamında: 'I take your point, but from our side...' — müşteriyle tartışmadan görüş bildirme."
        ],
        examples: [
          { en: "If you ask me, Istanbul is the best city in the world.", tr: "Bana sorarsan, İstanbul dünyanın en iyi şehri." },
          { en: "I see your point, but I think it's a bit more complicated.", tr: "Ne demek istediğini anlıyorum ama bence biraz daha karmaşık." },
          { en: "I couldn't agree more.", tr: "Sonuna kadar katılıyorum." },
          { en: "I'm not so sure about that.", tr: "Bundan pek emin değilim." },
          { en: "I take your point, but laminated glass is safer in this case.", tr: "Haklısınız ama bu durumda lamine cam daha güvenli." }
        ]
      },
      cards: [
        { en: "If you ask me, ...", tr: "Bana sorarsan, ...", ex: "If you ask me, the food here is overrated." },
        { en: "The way I see it, ...", tr: "Benim gördüğüm kadarıyla, ...", ex: "The way I see it, remote work is here to stay." },
        { en: "I couldn't agree more.", tr: "Sonuna kadar katılıyorum.", ex: "Quality matters more than price. — I couldn't agree more." },
        { en: "I see your point, but...", tr: "Ne demek istediğini anlıyorum ama ...", ex: "I see your point, but it's too expensive." },
        { en: "I'm not so sure about that.", tr: "Bundan pek emin değilim.", ex: "Electric ships everywhere by 2030? I'm not so sure about that." },
        { en: "That's a good point.", tr: "İyi bir nokta.", ex: "That's a good point — I hadn't thought of that." },
        { en: "I see it a bit differently.", tr: "Ben biraz farklı görüyorum.", ex: "Actually, I see it a bit differently." },
        { en: "To some extent", tr: "Bir dereceye kadar", ex: "I agree to some extent." },
        { en: "I know what you mean, but...", tr: "Ne demek istediğini biliyorum ama ...", ex: "I know what you mean, but it's worth trying." },
        { en: "Fair enough.", tr: "Haklısın / Makul.", ex: "Fair enough — let's do it your way." },
        { en: "I take your point.", tr: "Anlıyorum / Haklısınız (resmi).", ex: "I take your point, but the deadline is fixed." }
      ],
      exercises: [
        { type: "mcq", q: "A colleague says: ‘We should cut the price by twenty percent.’ You disagree. Most polite reply?",
          options: ["You're wrong.", "No way, that's stupid.", "I see your point, but that might hurt our margins.", "Never."],
          answer: 2, explain: "Önce kabul, sonra 'but' ile yumuşak karşı çıkma." },
        { type: "fill", q: "I couldn't agree ___.", answers: ["more"], hint: "daha fazla",
          explain: "'I couldn't agree more' = tamamen katılıyorum." },
        { type: "order", answer: "I'm not so sure about that, actually", tr: "Açıkçası bundan pek emin değilim.",
          explain: "Kibar şüphe/karşı çıkma ifadesi." },
        { type: "mcq", q: "What does ‘I couldn't agree more’ mean?",
          options: ["I disagree completely.", "I agree completely.", "I can't decide.", "I agree a little."],
          answer: 1, explain: "Daha fazla katılamam = tamamen katılıyorum." },
        { type: "match", pairs: [["Fair enough.", "Makul / Haklısın."], ["Exactly!", "Aynen!"], ["To some extent", "Bir dereceye kadar"], ["If you ask me", "Bana sorarsan"], ["I see it differently.", "Ben farklı görüyorum."]],
          explain: "Fikir ve katılma ifadeleri." },
        { type: "fill", q: "The way I ___ it, quality matters more than price.", answers: ["see"], hint: "görmek",
          explain: "'The way I see it' = benim gördüğüm kadarıyla." },
        { type: "mcq", q: "A shipyard client says: ‘Tempered glass is enough for the bridge windows.’ You think laminated is safer. Best reply?",
          options: ["No, tempered is wrong.", "You don't know glass.", "OK, whatever you say.", "I take your point, but for bridge windows we'd recommend laminated for safety."],
          answer: 3, explain: "Resmi ortamda 'I take your point, but...' profesyonel karşı çıkıştır." },
        { type: "listen", text: "That's a good point. I hadn't thought of that.", tr: "İyi bir nokta. Bunu düşünmemiştim." },
        { type: "order", answer: "I agree with you to some extent", tr: "Sana bir dereceye kadar katılıyorum.",
          explain: "Kısmi katılma." },
        { type: "mcq", q: "Which phrase gives an opinion?",
          options: ["Personally, I'd say it's worth it.", "Fair enough.", "Exactly!", "I couldn't agree more."],
          answer: 0, explain: "'Personally, I'd say...' kişisel görüş bildirir; diğerleri tepki ifadesidir." },
        { type: "fill", q: "I know what you ___, but I think it's worth trying.", answers: ["mean"], hint: "demek istemek",
          explain: "'I know what you mean' = ne demek istediğini anlıyorum." },
        { type: "listen", text: "If you ask me, it's a bit overrated.", tr: "Bana sorarsan, biraz abartılıyor." }
      ]
    },
    {
      id: "conversation-08",
      title: "Müşterilerle iş sohbeti",
      level: "B2",
      week: 4,
      intro: {
        tr: "Yabancı tersane müşterileriyle ilişkiler toplantı odasından çok akşam yemeğinde, havaalanından otele giderken veya fabrika turunda kurulur. Bu anlarda sıcak ama profesyonel ol: misafirperverlik göster, işten biraz uzaklaş, kişisel ama özel olmayan sorular sor.",
        points: [
          "Havaalanı: 'Welcome to Istanbul! Let me help you with your bags.' / 'The car's just outside.'",
          "Fabrika ziyareti: 'Let me show you around.' / 'This is where we temper the glass.' / 'Feel free to ask any questions.'",
          "Yemek: 'Is there anything you don't eat?' / 'Shall I order a few things to share?' / 'This one's on us.'",
          "Kahve molası: 'How's business on your side?' / 'Busy time of year for you?'",
          "Konuşma açabileceğin konular: yolculuk, otel, Türk yemeği, şehirleri, sektör trendleri, tatil planları, aile (genel)."
        ],
        examples: [
          { en: "Welcome! How was the flight from Oslo?", tr: "Hoş geldiniz! Oslo'dan uçuş nasıldı?" },
          { en: "Let me show you around the factory.", tr: "Size fabrikayı gezdireyim." },
          { en: "Is there anything you don't eat?", tr: "Yemediğiniz bir şey var mı?" },
          { en: "Please, this one's on us.", tr: "Lütfen, bu bizden." },
          { en: "How's business been on your side this year?", tr: "Sizin tarafta bu yıl işler nasıl gidiyor?" }
        ]
      },
      cards: [
        { en: "Let me show you around.", tr: "Size etrafı gezdireyim.", ex: "Welcome to our plant — let me show you around." },
        { en: "Feel free to...", tr: "Çekinmeden ...", ex: "Feel free to ask any questions." },
        { en: "Is there anything you don't eat?", tr: "Yemediğiniz bir şey var mı?", ex: "Before we order — is there anything you don't eat?" },
        { en: "This one's on us.", tr: "Bu bizden (hesap bizde).", ex: "Please, put your wallet away — this one's on us." },
        { en: "Help yourself.", tr: "Buyurun, alın (kendinize servis yapın).", ex: "There's coffee and tea — help yourself." },
        { en: "How's business on your side?", tr: "Sizin tarafta işler nasıl?", ex: "How's business on your side these days?" },
        { en: "Shall we order a few things to share?", tr: "Paylaşmak için birkaç şey sipariş edelim mi?", ex: "Shall we order a few meze to share?" },
        { en: "Make yourself at home.", tr: "Kendi evinizdeymiş gibi rahat olun.", ex: "Come in, make yourself at home." },
        { en: "I'll pick you up from...", tr: "Sizi ...'den alırım.", ex: "I'll pick you up from the hotel at nine." },
        { en: "It's been a pleasure having you.", tr: "Sizi ağırlamak bir zevkti.", ex: "It's been a pleasure having you here this week." },
        { en: "Cheers! / To our partnership!", tr: "Şerefe! / Ortaklığımıza!", ex: "Cheers — to a successful partnership!" },
        { en: "Busy time of year for you?", tr: "Sizin için yoğun bir dönem mi?", ex: "Busy time of year for you, with the new builds?" }
      ],
      exercises: [
        { type: "mcq", q: "You meet a client at arrivals. What's the best thing to say first?",
          options: ["You're the client?", "Welcome to Istanbul! How was your flight?", "Give me your bags.", "We have a meeting at three."],
          answer: 1, explain: "Sıcak karşılama + uçuş sorusu ideal başlangıç." },
        { type: "fill", q: "Welcome to our plant. Let me show you ___.", answers: ["around"], hint: "show sb ___",
          explain: "'Show someone around' = birine bir yeri gezdirmek." },
        { type: "mcq", q: "At dinner, before ordering for a guest, what should you ask?",
          options: ["Are you hungry or not?", "Do you eat everything I order?", "Is there anything you don't eat?", "What's your diet weight?"],
          answer: 2, explain: "Diyet/yemek kısıtlamasını kibarca sormak önemlidir." },
        { type: "order", answer: "Please put your wallet away, this one's on us", tr: "Lütfen cüzdanınızı kaldırın, bu bizden.",
          explain: "'This one's on us' = hesap bizden." },
        { type: "match", pairs: [["Help yourself.", "Buyurun, alın."], ["Make yourself at home.", "Rahatınıza bakın."], ["Feel free to ask.", "Çekinmeden sorun."], ["This one's on us.", "Bu bizden."]],
          explain: "Misafirperverlik ifadeleri." },
        { type: "fill", q: "I'll pick you ___ from the hotel at nine tomorrow.", answers: ["up"], hint: "pick ___",
          explain: "'Pick someone up' = birini (arabayla) almak." },
        { type: "mcq", q: "During a coffee break with a Dutch shipyard manager, which is the best small talk?",
          options: ["How's business been on your side this year?", "Why is your price so low?", "How much do you earn?", "Our competitor is bad."],
          answer: 0, explain: "Genel iş durumu sormak profesyonel ve güvenli." },
        { type: "listen", text: "Feel free to ask any questions.", tr: "Çekinmeden soru sorabilirsiniz." },
        { type: "mcq", q: "On the factory tour, how do you naturally explain a process?",
          options: ["Here glass is.", "This is where we temper the glass.", "Temper glass here we.", "Glass tempered is this."],
          answer: 1, explain: "'This is where we...' tur sırasında yer anlatmak için ideal." },
        { type: "order", answer: "It's been a real pleasure having you here", tr: "Sizi burada ağırlamak gerçekten bir zevkti.",
          explain: "Ziyaretin sonunda veda cümlesi." },
        { type: "fill", q: "Shall we order a few meze to ___?", answers: ["share"], hint: "paylaşmak",
          explain: "Türk sofrasında mezeleri paylaşmayı önermek." },
        { type: "listen", text: "Cheers to a successful partnership!", tr: "Başarılı bir ortaklığa şerefe!" },
        { type: "mcq", q: "The client thanks you at the end of the dinner. Best reply?",
          options: ["Yes, it was expensive.", "OK.", "No problem, you pay next time.", "My pleasure — I'm glad you enjoyed it."],
          answer: 3, explain: "'My pleasure' + memnuniyet ifadesi zarif bir kapanış." }
      ]
    },
    // ───────────────────────── WEEK 5 ─────────────────────────
    {
      id: "conversation-09",
      title: "Günlük konuşmada phrasal verb'ler",
      level: "B2+",
      week: 5,
      intro: {
        tr: "Ana dili İngilizce olanlar günlük konuşmada 'meet by chance' yerine 'run into', 'postpone' yerine 'put off' der. Phrasal verb kullanmak seni anında daha doğal gösterir. En sık kullanılanları cümle içinde öğren; tek başına ezberleme.",
        points: [
          "catch up (with sb) = biriyle hasret gidermek, haberleşmek: 'Let's catch up soon!'",
          "run into sb = birine tesadüfen rastlamak; come across = bir şeye rastlamak, ... gibi görünmek",
          "get along (with) = iyi geçinmek; look forward to + -ing = dört gözle beklemek",
          "put off = ertelemek; call off = iptal etmek; turn down = (teklifi) reddetmek",
          "figure out = çözmek, anlamak; end up = sonunda kendini ... bulmak; hang out = takılmak"
        ],
        examples: [
          { en: "We should catch up over coffee sometime.", tr: "Bir ara kahve içip hasret gidermeliyiz." },
          { en: "I ran into an old client at the airport.", tr: "Havaalanında eski bir müşteriye rastladım." },
          { en: "They had to put off the sea trials until next month.", tr: "Deniz testlerini gelecek aya ertelemek zorunda kaldılar." },
          { en: "We ended up staying until midnight.", tr: "Sonunda gece yarısına kadar kaldık." },
          { en: "I get along really well with their purchasing team.", tr: "Onların satın alma ekibiyle çok iyi anlaşıyorum." }
        ]
      },
      cards: [
        { en: "catch up", tr: "hasret gidermek, haberleşmek", ex: "It's been ages — let's catch up next week." },
        { en: "run into", tr: "tesadüfen rastlamak", ex: "I ran into Mark at the trade fair." },
        { en: "come across", tr: "rastlamak; ... izlenimi vermek", ex: "He comes across as a bit shy." },
        { en: "get along with", tr: "iyi geçinmek", ex: "Do you get along with your colleagues?" },
        { en: "put off", tr: "ertelemek", ex: "Don't put off the meeting again." },
        { en: "call off", tr: "iptal etmek", ex: "They called off the visit because of the storm." },
        { en: "turn down", tr: "reddetmek", ex: "She turned down the job offer." },
        { en: "figure out", tr: "çözmek, anlamak", ex: "I can't figure out how this app works." },
        { en: "end up", tr: "sonunda ... olmak", ex: "We ended up eating at a tiny fish restaurant." },
        { en: "hang out", tr: "takılmak, vakit geçirmek", ex: "Where do people usually hang out around here?" },
        { en: "look forward to", tr: "dört gözle beklemek", ex: "I'm looking forward to meeting you in person." },
        { en: "drop by", tr: "uğramak", ex: "Feel free to drop by the office anytime." }
      ],
      exercises: [
        { type: "mcq", q: "‘I met an old friend by chance at the mall.’ — Which is more natural?",
          options: ["I ran into an old friend at the mall.", "I ran out an old friend at the mall.", "I ran over an old friend at the mall.", "I ran off an old friend at the mall."],
          answer: 0, explain: "'Run into' = tesadüfen rastlamak. ('Run over' = ezmek!)" },
        { type: "fill", q: "It's been ages! We should ___ up over coffee.", answers: ["catch"], hint: "hasret gidermek",
          explain: "'Catch up' = birbirinin haberlerini almak." },
        { type: "fill", q: "The client visit was ___ off because of the storm.", answers: ["called"], hint: "iptal edildi",
          explain: "'Call off' = iptal etmek; pasif: was called off." },
        { type: "match", pairs: [["put off", "ertelemek"], ["turn down", "reddetmek"], ["figure out", "çözmek"], ["hang out", "takılmak"], ["drop by", "uğramak"], ["end up", "sonunda ... olmak"]],
          explain: "Sık kullanılan phrasal verb'ler." },
        { type: "order", answer: "I'm really looking forward to meeting you", tr: "Sizinle tanışmayı gerçekten dört gözle bekliyorum.",
          explain: "'Look forward to + -ing' (to'dan sonra -ing!)." },
        { type: "mcq", q: "Choose the correct sentence.",
          options: ["I look forward to see you.", "I look forward to seeing you.", "I look forward seeing you.", "I look forward for seeing you."],
          answer: 1, explain: "'Look forward to' + V-ing." },
        { type: "mcq", q: "A: ‘How do you find the new project manager?’ — Most natural reply?",
          options: ["He comes across as very friendly.", "He comes over as very friendly.", "He comes into very friendly.", "He comes up friendly."],
          answer: 0, explain: "'Come across as' = ... izlenimi vermek." },
        { type: "fill", q: "We were only going for one drink, but we ___ up staying till midnight.", answers: ["ended"], hint: "end up (geçmiş)",
          explain: "'End up + -ing' = sonunda ... yapmış olmak." },
        { type: "listen", text: "Do you get along with your colleagues?", tr: "İş arkadaşlarınla iyi geçinir misin?" },
        { type: "mcq", q: "‘She refused the job offer.’ — Which phrasal verb fits?",
          options: ["She turned up the offer.", "She turned off the offer.", "She turned down the offer.", "She turned in the offer."],
          answer: 2, explain: "'Turn down' = reddetmek." },
        { type: "order", answer: "Feel free to drop by the office anytime", tr: "İstediğin zaman ofise uğrayabilirsin.",
          explain: "'Drop by' = kısa ziyaret, uğramak." },
        { type: "listen", text: "I can't figure out how this works.", tr: "Bunun nasıl çalıştığını çözemiyorum." },
        { type: "mcq", q: "‘Let's postpone the meeting.’ — More conversational?",
          options: ["Let's put on the meeting.", "Let's put up the meeting.", "Let's put away the meeting.", "Let's put the meeting off."],
          answer: 3, explain: "'Put off' = ertelemek; nesne araya girebilir: put the meeting off." }
      ]
    },
    {
      id: "conversation-10",
      title: "Deyimler ve doğal ifadeler",
      level: "B2+",
      week: 5,
      intro: {
        tr: "Deyimler konuşmana renk katar, ama doğru yerde ve abartmadan kullanılmalı. Bir sohbette bir-iki deyim yeterli. Bu ünitedeki deyimler hem günlük hayatta hem iş ortamında çok sık duyulur.",
        points: [
          "the ball is in your court = karar/sıra sende; on the same page = aynı fikirde, aynı noktada",
          "ring a bell = tanıdık gelmek; piece of cake = çok kolay; cost an arm and a leg = çok pahalı olmak",
          "break the ice = buzları eritmek; get the hang of it = alışmak, işi kapmak",
          "under the weather = biraz hasta; call it a day = günü bitirmek; touch base = haberleşmek",
          "Deyimi anlamadıysan sormaktan çekinme: 'Sorry, what does that mean exactly?'"
        ],
        examples: [
          { en: "We've sent our best offer — the ball's in your court now.", tr: "En iyi teklifimizi gönderdik — karar artık sizde." },
          { en: "Just to make sure we're on the same page: delivery is in March?", tr: "Aynı noktada olduğumuzdan emin olmak için: teslimat Mart'ta mı?" },
          { en: "His name rings a bell, but I can't remember where we met.", tr: "Adı tanıdık geliyor ama nerede tanıştığımızı hatırlayamıyorum." },
          { en: "A little joke always helps to break the ice.", tr: "Küçük bir şaka her zaman buzları eritmeye yardımcı olur." },
          { en: "I'm feeling a bit under the weather today.", tr: "Bugün kendimi biraz rahatsız hissediyorum." }
        ]
      },
      cards: [
        { en: "The ball is in your court.", tr: "Top sende / Karar senin.", ex: "We've made our offer; the ball is in your court." },
        { en: "on the same page", tr: "aynı fikirde / aynı noktada", ex: "Let's make sure we're all on the same page." },
        { en: "ring a bell", tr: "tanıdık gelmek", ex: "Does the name Hansen ring a bell?" },
        { en: "a piece of cake", tr: "çocuk oyuncağı, çok kolay", ex: "The installation was a piece of cake." },
        { en: "cost an arm and a leg", tr: "çok pahalıya mal olmak", ex: "Hotels in Oslo cost an arm and a leg." },
        { en: "break the ice", tr: "buzları eritmek", ex: "He told a funny story to break the ice." },
        { en: "get the hang of it", tr: "işi kapmak, alışmak", ex: "It's tricky at first, but you'll get the hang of it." },
        { en: "under the weather", tr: "biraz hasta, keyifsiz", ex: "Sorry, I'm a bit under the weather today." },
        { en: "call it a day", tr: "günü bitirmek, paydos etmek", ex: "It's seven o'clock — let's call it a day." },
        { en: "touch base", tr: "kısaca haberleşmek", ex: "Let's touch base next week about the order." },
        { en: "hit it off", tr: "hemen anlaşmak, kaynaşmak", ex: "We hit it off straight away." },
        { en: "once in a blue moon", tr: "kırk yılda bir", ex: "I only eat fast food once in a blue moon." }
      ],
      exercises: [
        { type: "mcq", q: "‘We've sent our final offer. The ball is in your court.’ This means:",
          options: ["Let's play tennis.", "It's your turn to decide.", "The game is over.", "You have lost."],
          answer: 1, explain: "'The ball is in your court' = sıra/karar sende." },
        { type: "fill", q: "His name rings a ___, but I can't remember his face.", answers: ["bell"], hint: "zil",
          explain: "'Ring a bell' = tanıdık gelmek." },
        { type: "match", pairs: [["piece of cake", "çok kolay"], ["under the weather", "biraz hasta"], ["call it a day", "paydos etmek"], ["hit it off", "hemen kaynaşmak"], ["once in a blue moon", "kırk yılda bir"]],
          explain: "Yaygın deyimler." },
        { type: "mcq", q: "Before ending a meeting with a client, you want to confirm everyone agrees. You say:",
          options: ["Just to make sure we're all on the same page...", "Just to make sure we're all in the same book...", "Let's break the ice...", "It's a piece of cake..."],
          answer: 0, explain: "'On the same page' = aynı anlayışta olmak." },
        { type: "order", answer: "It's late, so let's call it a day", tr: "Geç oldu, hadi bugünlük paydos edelim.",
          explain: "'Call it a day' = o günlük işi bitirmek." },
        { type: "fill", q: "It's tricky at first, but you'll get the ___ of it.", answers: ["hang"], hint: "get the ___ of it",
          explain: "'Get the hang of it' = bir işi kapmak." },
        { type: "mcq", q: "A: ‘How was the driving test?’ B: ‘___’ (It was very easy.)",
          options: ["A piece of pie!", "A slice of bread!", "A piece of cake!", "A cup of tea!"],
          answer: 2, explain: "'A piece of cake' = çok kolay." },
        { type: "listen", text: "Let's touch base next week.", tr: "Gelecek hafta haberleşelim." },
        { type: "mcq", q: "‘Hotels in London cost an arm and a leg.’ means they are:",
          options: ["dangerous", "very cheap", "far away", "very expensive"],
          answer: 3, explain: "'Cost an arm and a leg' = çok pahalı." },
        { type: "order", answer: "We hit it off straight away", tr: "Hemen kaynaştık / anlaştık.",
          explain: "'Hit it off' = birisiyle hemen anlaşmak." },
        { type: "fill", q: "A funny story is a great way to break the ___ at a dinner.", answers: ["ice"], hint: "buz",
          explain: "'Break the ice' = ilk gerginliği gidermek." },
        { type: "listen", text: "Sorry, I'm a bit under the weather today.", tr: "Kusura bakma, bugün biraz rahatsızım." }
      ]
    },
    // ───────────────────────── WEEK 6 ─────────────────────────
    {
      id: "conversation-11",
      title: "Hikaye anlatmak ve tepki vermek",
      level: "B2+",
      week: 6,
      intro: {
        tr: "İyi bir anekdot sohbetin en akılda kalan kısmıdır. Hikayeyi bir girişle başlat ('You'll never guess what happened...'), zaman bağlaçlarıyla ilerlet ('So anyway', 'Then all of a sudden', 'In the end') ve kısa tut. Dinleyen olarak da güçlü tepkiler ver: 'No way!', 'You're kidding!', 'That must have been awful!'",
        points: [
          "Başlangıç: 'You'll never guess what happened...' / 'Did I ever tell you about the time...?' / 'Funny thing happened...'",
          "İlerletme: 'So anyway...', 'Then, all of a sudden...', 'Before I knew it...', 'It turned out that...'",
          "Bitirme: 'In the end...', 'Long story short...', 'Anyway, that's how...'",
          "Tepki: 'No way!', 'You're kidding!', 'Seriously?', 'Oh no!', 'What happened next?'",
          "Empati: 'That must have been awful / scary / hilarious!' — must have + V3 tahmini."
        ],
        examples: [
          { en: "You'll never guess who I bumped into at the airport.", tr: "Havaalanında kime rastladığımı asla tahmin edemezsin." },
          { en: "So anyway, all of a sudden the lights went out.", tr: "Neyse, birden ışıklar söndü." },
          { en: "It turned out he was the shipyard's new CEO!", tr: "Meğer tersanenin yeni CEO'suymuş!" },
          { en: "Long story short, we missed the flight.", tr: "Uzun lafın kısası, uçağı kaçırdık." },
          { en: "That must have been so embarrassing!", tr: "Bu çok utandırıcı olmuş olmalı!" }
        ]
      },
      cards: [
        { en: "You'll never guess what happened.", tr: "Ne oldu asla tahmin edemezsin.", ex: "You'll never guess what happened at the fair." },
        { en: "Did I ever tell you about the time...?", tr: "Sana hiç ... olduğu zamanı anlattım mı?", ex: "Did I ever tell you about the time I got lost in Tokyo?" },
        { en: "So anyway, ...", tr: "Neyse, ... (hikayeye dönüş)", ex: "So anyway, we finally got to the hotel." },
        { en: "all of a sudden", tr: "birdenbire", ex: "All of a sudden, the engine stopped." },
        { en: "It turned out that...", tr: "Meğer ... çıktı.", ex: "It turned out that the hotel was fully booked." },
        { en: "Long story short, ...", tr: "Uzun lafın kısası, ...", ex: "Long story short, we signed the contract." },
        { en: "Before I knew it, ...", tr: "Ne olduğunu anlamadan, ...", ex: "Before I knew it, it was midnight." },
        { en: "You're kidding!", tr: "Şaka yapıyorsun!", ex: "You met him on the ferry? You're kidding!" },
        { en: "That must have been...", tr: "Bu ... olmuş olmalı.", ex: "That must have been terrifying!" },
        { en: "What happened next?", tr: "Sonra ne oldu?", ex: "Oh no! What happened next?" },
        { en: "bump into", tr: "tesadüfen karşılaşmak", ex: "I bumped into my old teacher yesterday." }
      ],
      exercises: [
        { type: "mcq", q: "A: ‘I left my passport in the taxi on the way to the airport!’ — Best reaction?",
          options: ["OK, and?", "Oh no! That must have been so stressful!", "Passports are important.", "You must be stressful."],
          answer: 1, explain: "'That must have been + sıfat' empati gösterir." },
        { type: "fill", q: "We waited for an hour, and it ___ out that the meeting was cancelled.", answers: ["turned"], hint: "meğer",
          explain: "'It turned out that...' = meğer ..." },
        { type: "order", answer: "You'll never guess who I bumped into", tr: "Kime rastladığımı asla tahmin edemezsin.",
          explain: "Hikayeye merak uyandırarak başlama." },
        { type: "mcq", q: "Which phrase is used to summarise a long story quickly?",
          options: ["Long story short", "Short story long", "Story is long", "Long short story"],
          answer: 0, explain: "'Long story short' = uzun lafın kısası." },
        { type: "match", pairs: [["all of a sudden", "birdenbire"], ["It turned out", "Meğer"], ["Long story short", "Uzun lafın kısası"], ["You're kidding!", "Şaka yapıyorsun!"], ["So anyway", "Neyse"]],
          explain: "Hikaye anlatma kalıpları." },
        { type: "fill", q: "Oh no, that must have ___ awful!", answers: ["been"], hint: "must have + V3",
          explain: "Geçmişle ilgili tahmin: must have been." },
        { type: "mcq", q: "A: ‘I sat next to the CEO of the shipyard on the plane — we talked for three hours!’ — Best reaction?",
          options: ["Planes are long.", "Good.", "No way! What did you talk about?", "Were you tired?"],
          answer: 2, explain: "Güçlü tepki + merak sorusu konuşanı cesaretlendirir." },
        { type: "listen", text: "Then, all of a sudden, the lights went out.", tr: "Sonra birdenbire ışıklar söndü." },
        { type: "order", answer: "Did I ever tell you about the time I missed my flight?", tr: "Sana hiç uçağımı kaçırdığım zamanı anlattım mı?",
          explain: "Anekdota giriş kalıbı." },
        { type: "mcq", q: "You're listening to a story and want the speaker to continue. You say:",
          options: ["Finish.", "That's enough.", "I know.", "Seriously? What happened next?"],
          answer: 3, explain: "'What happened next?' anlatıcıyı devam ettirir." },
        { type: "fill", q: "We started chatting and, before I ___ it, it was two in the morning.", answers: ["knew"], hint: "know (V2)",
          explain: "'Before I knew it' = ne olduğunu anlamadan." },
        { type: "listen", text: "Long story short, we signed the contract.", tr: "Uzun lafın kısası, sözleşmeyi imzaladık." }
      ]
    },
    {
      id: "conversation-12",
      title: "Telefon ve görüntülü görüşmeler",
      level: "B2+",
      week: 6,
      intro: {
        tr: "Telefonda ve Zoom/Teams görüşmelerinde jest ve mimik olmadığından iletişim daha zordur. Bağlantı sorunlarını, ses problemlerini ve ekran paylaşımını anlatan hazır kalıplar seni rahatlatır. Anlamadığında hemen kibarca tekrar iste — tahmin etme.",
        points: [
          "Bağlantı: 'Sorry, you broke up there.' / 'You're breaking up a bit.' / 'I think we lost you for a second.'",
          "Ses: 'You're on mute.' / 'Can you hear me OK?' / 'There's a bit of an echo.'",
          "Tekrar: 'Could you repeat that, please?' / 'Sorry, could you say that again? The line's bad.'",
          "Ekran: 'Let me share my screen.' / 'Can everyone see my screen?' / 'I'll drop the link in the chat.'",
          "Telefon: 'Could I speak to...?' / 'I'll put you through.' / 'Can I call you back in five minutes?' / 'Speaking.'"
        ],
        examples: [
          { en: "Sorry, you broke up there — could you repeat the last part?", tr: "Pardon, sesin kesildi — son kısmı tekrarlar mısın?" },
          { en: "I think you're on mute.", tr: "Sanırım mikrofonun kapalı." },
          { en: "Let me share my screen so you can see the drawings.", tr: "Çizimleri görebilmeniz için ekranımı paylaşayım." },
          { en: "Can I call you back in five minutes? I'm just in a meeting.", tr: "Seni beş dakika sonra arayabilir miyim? Şu an toplantıdayım." },
          { en: "I'll drop the link in the chat.", tr: "Linki sohbete bırakırım." }
        ]
      },
      cards: [
        { en: "You broke up.", tr: "Sesin kesildi / gitti.", ex: "Sorry, you broke up there. Could you say that again?" },
        { en: "You're on mute.", tr: "Mikrofonun kapalı.", ex: "Hans, I think you're on mute." },
        { en: "Can you hear me OK?", tr: "Beni iyi duyabiliyor musun?", ex: "Hello? Can you hear me OK?" },
        { en: "Could you repeat that?", tr: "Tekrar eder misin?", ex: "Sorry, could you repeat that, please?" },
        { en: "Let me share my screen.", tr: "Ekranımı paylaşayım.", ex: "Let me share my screen and show you the quote." },
        { en: "I'll drop the link in the chat.", tr: "Linki sohbete bırakırım.", ex: "I'll drop the link in the chat now." },
        { en: "Can I call you back?", tr: "Seni geri arayabilir miyim?", ex: "Can I call you back in ten minutes?" },
        { en: "I'll put you through.", tr: "Sizi bağlıyorum.", ex: "One moment, I'll put you through to Mr. Demir." },
        { en: "Speaking.", tr: "Benim (telefonda).", ex: "Could I speak to Oğuz? — Speaking." },
        { en: "The line is bad.", tr: "Hat kötü / çekmiyor.", ex: "Sorry, the line is really bad today." },
        { en: "We lost you for a second.", tr: "Bir saniye seni kaybettik.", ex: "I think we lost you for a second there." },
        { en: "Hold on a sec.", tr: "Bir saniye bekle.", ex: "Hold on a sec, let me find the file." }
      ],
      exercises: [
        { type: "mcq", q: "During a Teams call, the client is talking but you hear nothing. You say:",
          options: ["Talk!", "I think you're on mute.", "You are silent person.", "Your voice is closed."],
          answer: 1, explain: "'You're on mute' = mikrofonun kapalı." },
        { type: "fill", q: "Sorry, you broke ___ there. Could you say that again?", answers: ["up"], hint: "break ___",
          explain: "'Break up' = (bağlantıda) sesin kesilmesi." },
        { type: "order", answer: "Let me share my screen so you can see", tr: "Görebilmeniz için ekranımı paylaşayım.",
          explain: "Ekran paylaşma kalıbı." },
        { type: "mcq", q: "Someone calls: ‘Hello, could I speak to Oğuz Ceyhan, please?’ You are Oğuz. You say:",
          options: ["Yes, I am him.", "Me.", "Speaking.", "Oğuz is talking."],
          answer: 2, explain: "Telefonda 'Speaking.' = benim." },
        { type: "match", pairs: [["You're on mute.", "Mikrofonun kapalı."], ["Hold on a sec.", "Bir saniye bekle."], ["I'll put you through.", "Sizi bağlıyorum."], ["The line is bad.", "Hat kötü."], ["Can I call you back?", "Seni geri arayabilir miyim?"]],
          explain: "Telefon/görüntülü görüşme ifadeleri." },
        { type: "fill", q: "I'll drop the link in the ___.", answers: ["chat"], hint: "sohbet kutusu",
          explain: "Online toplantıda 'chat' = yazışma kutusu." },
        { type: "mcq", q: "You didn't understand the delivery date because of noise. Best response?",
          options: ["Sorry, the line's a bit bad — could you repeat the date, please?", "What?", "Say again louder!", "OK, fine."],
          answer: 0, explain: "Nedenini söyleyip kibarca tekrar istemek profesyoneldir." },
        { type: "listen", text: "Can you hear me OK?", tr: "Beni iyi duyabiliyor musun?" },
        { type: "order", answer: "Can I call you back in five minutes?", tr: "Seni beş dakika sonra arayabilir miyim?",
          explain: "Müsait olmadığında kibar erteleme." },
        { type: "mcq", q: "Which sentence asks if everyone sees what you're showing?",
          options: ["Can everyone watch me?", "Is my screen sharing you?", "Do you look my screen?", "Can everyone see my screen?"],
          answer: 3, explain: "'Can everyone see my screen?' standart ifadedir." },
        { type: "fill", q: "I think we ___ you for a second there. Can you hear us now?", answers: ["lost"], hint: "lose (V2)",
          explain: "'We lost you' = bağlantın koptu." },
        { type: "listen", text: "One moment, I'll put you through.", tr: "Bir dakika, sizi bağlıyorum." }
      ]
    },
    // ───────────────────────── WEEK 7 ─────────────────────────
    {
      id: "conversation-13",
      title: "Yanlış anlamalar, netleştirme ve zaman kazanmak",
      level: "C1",
      week: 7,
      intro: {
        tr: "C1 seviyesinde konuşmacı her şeyi anlamak zorunda değildir; anlamadığını zarifçe yönetir. Netleştirme istemek, yanlış anlaşılmayı düzeltmek ve düşünmek için zaman kazanmak akıcılığın parçasıdır. Sessiz kalmak yerine 'doldurucu' ifadeler kullan.",
        points: [
          "Netleştirme: 'What do you mean by...?' / 'Sorry, I'm not sure I follow.' / 'Could you elaborate on that?'",
          "Kontrol: 'So, if I understand you correctly, ...' / 'Are you saying that...?' / 'Just to clarify, ...'",
          "Düzeltme: 'Sorry, that's not quite what I meant.' / 'What I meant was...' / 'Let me put it another way.'",
          "Zaman kazanma: 'Let me think...' / 'That's a good question.' / 'How can I put this?' / 'Off the top of my head...'",
          "Bilmediğinde: 'I'm not a hundred percent sure, but...' / 'I'll have to check and get back to you.'"
        ],
        examples: [
          { en: "Sorry, I'm not sure I follow. Could you elaborate?", tr: "Kusura bakma, tam takip edemedim. Biraz açar mısın?" },
          { en: "So, if I understand you correctly, you need the glass by May?", tr: "Yani doğru anladıysam, camlara Mayıs'a kadar ihtiyacınız var?" },
          { en: "That's not quite what I meant. Let me put it another way.", tr: "Tam olarak bunu kastetmedim. Başka türlü anlatayım." },
          { en: "That's a good question — let me think about that for a second.", tr: "Güzel soru — bir saniye düşüneyim." },
          { en: "Off the top of my head, I'd say around three weeks.", tr: "Aklıma ilk gelen, yaklaşık üç hafta derim." }
        ]
      },
      cards: [
        { en: "I'm not sure I follow.", tr: "Tam takip edemedim / anlayamadım.", ex: "Sorry, I'm not sure I follow. Can you explain again?" },
        { en: "What do you mean by...?", tr: "... derken neyi kastediyorsun?", ex: "What do you mean by 'flexible delivery'?" },
        { en: "Could you elaborate on that?", tr: "Bunu biraz açar mısın?", ex: "Interesting — could you elaborate on that?" },
        { en: "If I understand you correctly, ...", tr: "Doğru anladıysam, ...", ex: "If I understand you correctly, you want a discount." },
        { en: "Just to clarify, ...", tr: "Netleştirmek için, ...", ex: "Just to clarify, is that price per square metre?" },
        { en: "That's not quite what I meant.", tr: "Tam olarak bunu kastetmedim.", ex: "Sorry, that's not quite what I meant." },
        { en: "Let me put it another way.", tr: "Başka türlü ifade edeyim.", ex: "Let me put it another way: quality comes first." },
        { en: "That's a good question.", tr: "Güzel soru (zaman kazanma).", ex: "That's a good question. Let me think." },
        { en: "Off the top of my head, ...", tr: "Aklıma ilk gelen / hemen söylemem gerekirse, ...", ex: "Off the top of my head, about two hundred units." },
        { en: "I'll get back to you on that.", tr: "Bu konuda size döneceğim.", ex: "I'm not sure — I'll get back to you on that." },
        { en: "How can I put this?", tr: "Nasıl desem?", ex: "How can I put this? It's not ideal." },
        { en: "Are you saying that...?", tr: "...'i mi söylüyorsun?", ex: "Are you saying that the order is cancelled?" }
      ],
      exercises: [
        { type: "mcq", q: "A client uses a technical term you don't know. What's the best response?",
          options: ["Pretend you understand.", "Sorry, what do you mean by that exactly?", "Change the subject.", "Say 'Yes, yes.'"],
          answer: 1, explain: "Anlamını sormak profesyoneldir; tahmin etmek risklidir." },
        { type: "fill", q: "So, if I understand you ___, you need the glass by May?", answers: ["correctly", "right"], hint: "doğru",
          explain: "'If I understand you correctly' = doğru anladıysam." },
        { type: "order", answer: "That's not quite what I meant", tr: "Tam olarak bunu kastetmedim.",
          explain: "Yanlış anlaşılmayı yumuşakça düzeltme." },
        { type: "mcq", q: "A client asks a difficult question and you need a few seconds. Best phrase?",
          options: ["Wait.", "I don't know.", "Hmm, that's a good question. Let me think...", "Next question."],
          answer: 2, explain: "'That's a good question' doğal bir zaman kazanma yöntemidir." },
        { type: "match", pairs: [["Just to clarify", "Netleştirmek için"], ["Off the top of my head", "Aklıma ilk gelen"], ["How can I put this?", "Nasıl desem?"], ["Could you elaborate?", "Biraz açar mısın?"], ["I'm not sure I follow.", "Tam takip edemedim."]],
          explain: "Netleştirme ve zaman kazanma ifadeleri." },
        { type: "fill", q: "I'm not sure about the exact price. I'll get ___ to you on that.", answers: ["back"], hint: "dönüş yapmak",
          explain: "'Get back to someone' = birine sonra dönüş yapmak." },
        { type: "mcq", q: "A: ‘We might need to rethink the whole order.’ You're worried. You ask:",
          options: ["Are you saying that you want to cancel?", "You cancel?", "Rethink is good.", "Why you rethink?"],
          answer: 0, explain: "'Are you saying that...?' anlamı kontrol etmenin kibar yolu." },
        { type: "listen", text: "Sorry, I'm not sure I follow.", tr: "Kusura bakma, tam takip edemedim." },
        { type: "order", answer: "Let me put it another way", tr: "Başka türlü ifade edeyim.",
          explain: "Açıklamayı yeniden ifade etmek." },
        { type: "mcq", q: "Which phrase means you're giving an estimate without checking?",
          options: ["To be exact,", "According to the report,", "After checking,", "Off the top of my head,"],
          answer: 3, explain: "'Off the top of my head' = kontrol etmeden, aklıma ilk gelen." },
        { type: "fill", q: "Just to ___, is that price per square metre?", answers: ["clarify"], hint: "netleştirmek",
          explain: "'Just to clarify' = netleştirmek için soruyorum." },
        { type: "listen", text: "Could you elaborate on that a little?", tr: "Bunu biraz açabilir misin?" },
        { type: "mcq", q: "A: ‘So you're saying the price will go up?’ That's wrong. Best reply?",
          options: ["No, wrong.", "You didn't listen.", "Not exactly. What I meant was that raw material costs are rising.", "Yes, maybe, no."],
          answer: 2, explain: "'Not exactly. What I meant was...' kibar düzeltme." }
      ]
    },
    {
      id: "conversation-14",
      title: "Davetler, planlar ve sohbeti kibarca bitirmek",
      level: "C1",
      week: 7,
      intro: {
        tr: "Davet etmek, kabul etmek ve özellikle kibarca reddetmek ilişkileri korumak için çok önemlidir. İngilizcede doğrudan 'No' yerine teşekkür + bahane + alternatif kullanılır. Sohbeti bitirirken de birden kesmek yerine bir 'çıkış cümlesi' ile kapatılır.",
        points: [
          "Davet: 'Would you like to join us for dinner?' / 'Are you free on Friday?' / 'Fancy grabbing a coffee?'",
          "Kabul: 'I'd love to!' / 'Sounds great, count me in.' / 'That would be lovely.'",
          "Kibar ret: 'Thanks so much, but I'm afraid I've got something on.' + 'Maybe another time?' / 'Can I take a rain check?'",
          "Plan: 'What time suits you?' / 'Shall we say seven?' / 'Let's pencil it in for Thursday.'",
          "Sohbeti bitirme: 'Anyway, I'll let you get back to...' / 'It's been great talking to you.' / 'I should probably mingle a bit.' / 'Let's keep in touch.'"
        ],
        examples: [
          { en: "We're having dinner in Bebek tonight — would you like to join us?", tr: "Bu akşam Bebek'te yemek yiyoruz — bize katılmak ister misiniz?" },
          { en: "I'd love to, but I've already got plans. Can I take a rain check?", tr: "Çok isterdim ama zaten planım var. Başka zamana erteleyebilir miyiz?" },
          { en: "Shall we say seven at the hotel lobby?", tr: "Saat yedide otel lobisinde diyelim mi?" },
          { en: "Anyway, I'll let you get back to your guests.", tr: "Neyse, seni misafirlerine bırakayım." },
          { en: "It's been really great talking to you. Let's keep in touch.", tr: "Seninle konuşmak çok güzeldi. Görüşelim / İletişimde kalalım." }
        ]
      },
      cards: [
        { en: "Would you like to join us?", tr: "Bize katılmak ister misiniz?", ex: "We're going for dinner — would you like to join us?" },
        { en: "Fancy grabbing a coffee?", tr: "Bir kahve içmeye ne dersin?", ex: "Fancy grabbing a coffee after the meeting?" },
        { en: "Count me in.", tr: "Ben de varım.", ex: "A boat trip on Saturday? Count me in!" },
        { en: "I've got something on.", tr: "Bir işim / planım var.", ex: "Sorry, I've got something on that evening." },
        { en: "Can I take a rain check?", tr: "Başka bir zamana erteleyebilir miyiz?", ex: "I'm exhausted tonight — can I take a rain check?" },
        { en: "What time suits you?", tr: "Hangi saat sana uyar?", ex: "What time suits you best on Friday?" },
        { en: "Shall we say...?", tr: "... diyelim mi?", ex: "Shall we say seven o'clock?" },
        { en: "pencil it in", tr: "geçici olarak not etmek / ajandaya yazmak", ex: "Let's pencil it in for next Tuesday." },
        { en: "I'll let you get back to...", tr: "Seni ...'e bırakayım (sohbeti bitirme).", ex: "I'll let you get back to work." },
        { en: "It's been great talking to you.", tr: "Seninle konuşmak çok güzeldi.", ex: "It's been great talking to you, Lars." },
        { en: "Let's keep in touch.", tr: "İletişimde kalalım.", ex: "Here's my card — let's keep in touch." },
        { en: "I should probably mingle.", tr: "Biraz diğerleriyle de sohbet etsem iyi olacak.", ex: "I should probably mingle a bit, but let's talk later." }
      ],
      exercises: [
        { type: "mcq", q: "A colleague invites you to dinner but you're busy. Most graceful reply?",
          options: ["No, I'm busy.", "I don't want to.", "Thanks so much, I'd love to, but I've got something on. Maybe next week?", "Maybe, maybe not."],
          answer: 2, explain: "Teşekkür + bahane + alternatif = kibar ret." },
        { type: "fill", q: "I'm really tired tonight — can I take a rain ___?", answers: ["check"], hint: "rain ___",
          explain: "'Take a rain check' = daveti başka zamana ertelemek." },
        { type: "order", answer: "Would you like to join us for dinner tonight?", tr: "Bu akşam yemekte bize katılmak ister misiniz?",
          explain: "Kibar davet kalıbı." },
        { type: "mcq", q: "A friend says: ‘We're going on a boat trip Saturday.’ You want to go. You say:",
          options: ["Count me in!", "Count me out!", "Count on me out.", "I count."],
          answer: 0, explain: "'Count me in' = ben de varım. ('Count me out' = ben yokum.)" },
        { type: "match", pairs: [["Count me in.", "Ben de varım."], ["pencil it in", "geçici olarak not etmek"], ["I've got something on.", "Bir işim var."], ["Let's keep in touch.", "İletişimde kalalım."], ["What time suits you?", "Hangi saat uyar?"]],
          explain: "Plan ve davet ifadeleri." },
        { type: "fill", q: "Shall we ___ seven at the hotel lobby?", answers: ["say"], hint: "... diyelim mi?",
          explain: "'Shall we say + saat?' saat önerme kalıbı." },
        { type: "mcq", q: "At a networking event, you want to end a conversation politely. You say:",
          options: ["Bye, I'm bored.", "OK, finish.", "I'm going now, goodbye forever.", "Anyway, it's been great talking to you — I should probably mingle a bit."],
          answer: 3, explain: "Olumlu bir cümle + bahane ile sohbeti nazikçe bitir." },
        { type: "listen", text: "It's been great talking to you.", tr: "Seninle konuşmak çok güzeldi." },
        { type: "order", answer: "Anyway, I'll let you get back to your guests", tr: "Neyse, seni misafirlerine bırakayım.",
          explain: "Karşı tarafı düşünüyormuş gibi sohbeti bitirme." },
        { type: "mcq", q: "A client in Germany says: ‘Let's meet when you visit Hamburg.’ The date isn't fixed yet. You say:",
          options: ["No date, no meeting.", "Great — let's pencil it in for the week of the twelfth and confirm later.", "I write it with pen.", "Maybe I come, maybe not."],
          answer: 1, explain: "'Pencil it in' = kesinleşmemiş bir plan için." },
        { type: "fill", q: "Fancy ___ a coffee after the meeting?", answers: ["grabbing"], hint: "grab + -ing",
          explain: "'Fancy + V-ing?' = ...'ye ne dersin? (İngiliz, gündelik)" },
        { type: "listen", text: "Here's my card. Let's keep in touch.", tr: "Kartım burada. İletişimde kalalım." }
      ]
    },
    // ───────────────────────── WEEK 8 ─────────────────────────
    {
      id: "conversation-15",
      title: "Güncel konular: nüans ve temkinli dil",
      level: "C1",
      week: 8,
      intro: {
        tr: "C1 seviyesinde teknoloji, iş-yaşam dengesi, çevre gibi konularda görüş bildirirken kesin hükümler yerine nüanslı ve temkinli (hedging) bir dil kullanılır. 'AI will destroy jobs' yerine 'AI could well change a lot of jobs' demek daha olgun ve ikna edici görünür. Bu, tartışmayı kibar tutar ve karşı tarafa alan bırakır.",
        points: [
          "Temkinli ifade: 'It seems to me that...' / 'There's a tendency to...' / 'It could be argued that...' / 'To a certain extent...'",
          "Olasılık: 'It's likely / unlikely that...' / 'could well' / 'There's a good chance that...'",
          "Denge: 'On the one hand..., on the other hand...' / 'Having said that, ...' / 'That said, ...'",
          "Genelleme yumuşatma: 'Generally speaking, ...' / 'By and large, ...' / 'More often than not, ...'",
          "Konuşma açabileceğin konular: yapay zeka ve işler, uzaktan çalışma, iş-yaşam dengesi, denizcilikte yeşil dönüşüm (emisyon, elektrikli gemiler), şehir hayatı ve maliyetler."
        ],
        examples: [
          { en: "It seems to me that remote work suits some people better than others.", tr: "Bana öyle geliyor ki uzaktan çalışma bazı insanlara diğerlerinden daha çok uyuyor." },
          { en: "AI could well change the way we do sales.", tr: "Yapay zeka satış yapma şeklimizi pekala değiştirebilir." },
          { en: "That said, nothing really replaces meeting face to face.", tr: "Bununla birlikte, hiçbir şey yüz yüze görüşmenin yerini tutmuyor." },
          { en: "There's a good chance the new emission rules will push shipyards towards lighter materials.", tr: "Yeni emisyon kurallarının tersaneleri daha hafif malzemelere yöneltme ihtimali yüksek." },
          { en: "By and large, people here work longer hours than in Europe.", tr: "Genel olarak burada insanlar Avrupa'dakinden daha uzun saatler çalışıyor." }
        ]
      },
      cards: [
        { en: "It seems to me that...", tr: "Bana öyle geliyor ki ...", ex: "It seems to me that people are tired of video calls." },
        { en: "could well", tr: "pekala ... olabilir", ex: "Prices could well go up next year." },
        { en: "There's a good chance that...", tr: "... olma ihtimali yüksek.", ex: "There's a good chance that the rules will change." },
        { en: "Having said that, ...", tr: "Bununla birlikte / Öyle dedim ama ...", ex: "It's expensive. Having said that, it lasts for years." },
        { en: "That said, ...", tr: "Yine de, ...", ex: "That said, I see the benefits." },
        { en: "By and large", tr: "Genel olarak", ex: "By and large, the feedback has been positive." },
        { en: "More often than not", tr: "Çoğu zaman", ex: "More often than not, the cheapest option costs more in the end." },
        { en: "It could be argued that...", tr: "... olduğu öne sürülebilir.", ex: "It could be argued that social media makes us lonelier." },
        { en: "work-life balance", tr: "iş-yaşam dengesi", ex: "A four-day week could improve work-life balance." },
        { en: "To a certain extent", tr: "Belli bir ölçüde", ex: "I agree with that to a certain extent." },
        { en: "The jury's still out on...", tr: "... konusunda henüz kesin karar yok.", ex: "The jury's still out on whether hydrogen ships will work." },
        { en: "There's no easy answer.", tr: "Bunun kolay bir cevabı yok.", ex: "Should we ban phones in schools? There's no easy answer." }
      ],
      exercises: [
        { type: "mcq", q: "Which sentence sounds the most nuanced (C1)?",
          options: ["AI will destroy all jobs.", "AI is bad.", "AI could well transform a lot of jobs, although it's hard to say how.", "AI jobs, no."],
          answer: 2, explain: "Temkinli dil (could well, hard to say) C1 konuşmacının özelliğidir." },
        { type: "fill", q: "Remote work saves time. Having ___ that, I miss the office chat.", answers: ["said"], hint: "say (V3)",
          explain: "'Having said that' = bununla birlikte." },
        { type: "order", answer: "It seems to me that people are working longer hours", tr: "Bana öyle geliyor ki insanlar daha uzun saatler çalışıyor.",
          explain: "'It seems to me that' görüşü yumuşatır." },
        { type: "mcq", q: "A Danish client asks: ‘Do you think electric ferries are the future?’ Best C1-style answer?",
          options: ["Yes, 100%.", "I think the jury's still out — battery weight is still a big issue, but there's a good chance for short routes.", "No idea, sorry.", "Electric is the future, definitely, for everything."],
          answer: 1, explain: "Nüanslı cevap: belirsizlik + gerekçe + olasılık." },
        { type: "match", pairs: [["by and large", "genel olarak"], ["more often than not", "çoğu zaman"], ["to a certain extent", "belli bir ölçüde"], ["that said", "yine de"], ["could well", "pekala olabilir"]],
          explain: "Nüans ve hedging ifadeleri." },
        { type: "fill", q: "There's a good ___ that the new rules will push prices up.", answers: ["chance"], hint: "ihtimal",
          explain: "'There's a good chance that...' = ihtimali yüksek." },
        { type: "mcq", q: "What does ‘The jury's still out’ mean?",
          options: ["People haven't decided yet.", "The court is closed.", "Everyone agrees.", "It's illegal."],
          answer: 0, explain: "Henüz kesin bir karar/fikir birliği yok." },
        { type: "listen", text: "By and large, the feedback has been positive.", tr: "Genel olarak geri bildirimler olumlu oldu." },
        { type: "order", answer: "On the other hand, it can be quite isolating", tr: "Öte yandan, oldukça yalnızlaştırıcı olabilir.",
          explain: "'On the other hand' karşı görüşü dengeler." },
        { type: "mcq", q: "Which phrase best introduces a cautious, debatable claim?",
          options: ["Everybody knows that...", "It's a fact that...", "Obviously...", "It could be argued that..."],
          answer: 3, explain: "'It could be argued that' iddiayı tartışmaya açık sunar." },
        { type: "fill", q: "I agree with you to a certain ___, but it's not that simple.", answers: ["extent"], hint: "ölçü",
          explain: "'To a certain extent' = belli bir ölçüde." },
        { type: "listen", text: "There's no easy answer to that.", tr: "Bunun kolay bir cevabı yok." },
        { type: "mcq", q: "A: ‘Is a four-day week realistic in manufacturing?’ — Best balanced reply?",
          options: ["Of course, easy.", "No, impossible.", "Generally speaking, it's harder in factories. That said, some firms have made shift systems work.", "I don't care."],
          answer: 2, explain: "Genelleme + 'That said' ile denge kurmak." }
      ]
    },
    {
      id: "conversation-16",
      title: "C1 akıcılık: doğal konuşmak",
      level: "C1",
      week: 8,
      intro: {
        tr: "Doğal konuşmanın sırrı mükemmel gramer değil; yumuşatıcılar (softeners), belirsiz dil (vague language), doğru ton ve kültürel farkındalıktır. Ana dili İngilizce olanlar 'sort of', 'kind of', 'or so', 'and stuff like that' gibi ifadeleri sürekli kullanır. Ayrıca İngilizlerin ironi ve 'understatement' (olduğundan hafif söyleme) alışkanlığını ve İngiliz-Amerikan farklarını bilmek yanlış anlamaları önler.",
        points: [
          "Yumuşatıcılar: 'a bit', 'slightly', 'I was wondering if...', 'Would you mind...?', 'I'm afraid...'",
          "Belirsiz dil: 'sort of / kind of', 'twenty or so', 'around six-ish', 'and stuff like that', 'or something'",
          "İngiliz understatement'ı: 'Not bad' = çok iyi olabilir; 'That's a bit of a problem' = ciddi sorun; 'Quite good' bazen = idare eder.",
          "Sarkazm farkındalığı: kötü havada 'Lovely weather, isn't it?' büyük ihtimalle ironiktir — ton ve bağlamı dinle.",
          "İngiliz / Amerikan: flat / apartment, lift / elevator, queue / line, holiday / vacation, the bill / the check, mobile / cell phone."
        ],
        examples: [
          { en: "It was sort of a last-minute thing.", tr: "Biraz son dakika bir şeydi." },
          { en: "There were twenty or so people at the dinner.", tr: "Yemekte yirmi kadar kişi vardı." },
          { en: "Let's meet around six-ish?", tr: "Altı gibi buluşalım mı?" },
          { en: "I was wondering if you might be free next week.", tr: "Acaba gelecek hafta müsait olur musunuz diye merak ediyordum." },
          { en: "Could we get the bill, please? (US: the check)", tr: "Hesabı alabilir miyiz lütfen?" }
        ]
      },
      cards: [
        { en: "sort of / kind of", tr: "biraz, bir nevi", ex: "It's sort of hard to explain." },
        { en: "... or so", tr: "... kadar, civarı", ex: "It takes an hour or so to get there." },
        { en: "-ish", tr: "...gibi, ...civarı", ex: "Let's meet at seven-ish." },
        { en: "and stuff like that", tr: "ve bunun gibi şeyler", ex: "We talked about work, travel and stuff like that." },
        { en: "I was wondering if...", tr: "Acaba ... diye merak ediyordum (kibar rica).", ex: "I was wondering if you could send the drawings today." },
        { en: "Would you mind...?", tr: "... sakıncası var mı?", ex: "Would you mind closing the window?" },
        { en: "I'm afraid...", tr: "Maalesef ...", ex: "I'm afraid we can't deliver before June." },
        { en: "Not bad at all.", tr: "Hiç fena değil (çoğu zaman = çok iyi).", ex: "The presentation? Not bad at all!" },
        { en: "a bit of a problem", tr: "küçük bir sorun (çoğu zaman = ciddi sorun)", ex: "The delay is a bit of a problem for us." },
        { en: "flat / apartment", tr: "daire (İng. / Amer.)", ex: "I live in a flat in Kadıköy." },
        { en: "queue / line", tr: "kuyruk, sıra (İng. / Amer.)", ex: "There was a long queue at passport control." },
        { en: "the bill / the check", tr: "hesap (İng. / Amer.)", ex: "Could we have the bill, please?" }
      ],
      exercises: [
        { type: "mcq", q: "Which request sounds the most natural and polite?",
          options: ["Send me the drawings.", "I was wondering if you could send me the drawings today.", "You must send the drawings.", "Drawings, please, now."],
          answer: 1, explain: "'I was wondering if...' kibar ve yumuşak bir rica kalıbıdır." },
        { type: "fill", q: "It takes an hour ___ so to get to the shipyard.", answers: ["or"], hint: "civarı",
          explain: "'An hour or so' = bir saat kadar." },
        { type: "mcq", q: "A British client looks at your offer and says: ‘That's a bit of a problem.’ What does he probably mean?",
          options: ["It's a tiny, unimportant issue.", "He's joking.", "He's happy.", "It's actually a serious issue."],
          answer: 3, explain: "İngiliz understatement'ı: 'a bit of a problem' çoğu zaman ciddi sorun demektir." },
        { type: "order", answer: "It's sort of hard to explain, actually", tr: "Açıkçası anlatması biraz zor.",
          explain: "'Sort of' ifadeyi yumuşatır, doğal kılar." },
        { type: "match", pairs: [["flat", "apartment"], ["lift", "elevator"], ["queue", "line"], ["holiday", "vacation"], ["mobile", "cell phone"]],
          explain: "İngiliz İngilizcesi (sol) – Amerikan İngilizcesi (sağ)." },
        { type: "mcq", q: "It's pouring with rain. Your British colleague says: ‘Lovely weather, isn't it?’ He is being:",
          options: ["sarcastic", "serious", "rude", "confused"],
          answer: 0, explain: "Kötü havada 'lovely' demek İngilizlere özgü ironidir." },
        { type: "fill", q: "Let's meet at seven-___ — I'm not sure exactly when I'll finish.", answers: ["ish"], hint: "civarı",
          explain: "'-ish' sayıya eklenerek 'civarı' anlamı verir." },
        { type: "listen", text: "We talked about work, travel and stuff like that.", tr: "İş, seyahat ve bunun gibi şeyler hakkında konuştuk." },
        { type: "mcq", q: "Which sentence uses a softener to deliver bad news to a client?",
          options: ["We can't deliver before June.", "No delivery before June.", "I'm afraid we won't be able to deliver before June.", "June. Not before."],
          answer: 2, explain: "'I'm afraid...' kötü haberi yumuşatır." },
        { type: "order", answer: "Would you mind if I opened the window?", tr: "Pencereyi açmamın sakıncası var mı?",
          explain: "'Would you mind if I + V2' kibar izin isteme." },
        { type: "fill", q: "There were thirty ___ so people at the reception.", answers: ["or"], hint: "kadar",
          explain: "Yaklaşık sayı: 'thirty or so'." },
        { type: "listen", text: "Could we have the bill, please?", tr: "Hesabı alabilir miyiz lütfen?" },
        { type: "mcq", q: "An American client asks: ‘Can I get the check?’ What does he want?",
          options: ["A bank cheque", "To check his email", "The restaurant bill", "A health check"],
          answer: 2, explain: "Amerikan İngilizcesinde 'the check' = restoran hesabı (İng.: the bill)." }
      ]
    }
  ]
});
