// Grammar module — B1+ → C1, 16 units over 8 weeks (tenses live in a separate module).
window.EA_MODULES = window.EA_MODULES || [];
window.EA_MODULES.push({
  id: "grammar",
  title: "Gramer",
  icon: "📘",
  color: "#4f7cff",
  description: "B1+'tan C1'e 16 ünitelik gramer yolculuğu: artikeller, modallar, koşul cümleleri, edilgen yapı, devrik cümleler ve resmi iş yazışması — gemi camı iş hayatından ve günlük sohbetten örneklerle.",
  units: [
    // ───────────────────────── WEEK 1 ─────────────────────────
    {
      id: "grammar-01",
      title: "Articles & Countable / Uncountable",
      level: "B1+",
      week: 1,
      intro: {
        tr: "İngilizcede 'a/an' sayılabilen tekil isimlerle ve ilk kez bahsedilen şeyler için, 'the' iki tarafın da bildiği belirli şeyler için kullanılır. Genel anlamda konuşurken çoğul ve sayılamayan isimlerde artikel kullanılmaz (zero article). Bazı isimler Türkçede sayılabilir gibi görünse de İngilizcede sayılamaz: equipment, information, advice, furniture, luggage. 'Glass' malzeme olarak sayılamaz; bardak anlamında sayılabilir.",
        points: [
          "a + ünsüz sesi (a window, a university), an + ünlü sesi (an engineer, an hour).",
          "the: ikinci kez bahsedilen, tek olan ya da bağlamdan bilinen şey (the quotation I sent you, the only supplier).",
          "Zero article: genel anlamda çoğul/sayılamayan isimler (Glass is fragile. Customers want fast delivery.)",
          "Sayılamayanlar: information, equipment, advice, feedback, luggage, furniture → çoğul -s almaz; 'some' veya 'a piece of' ile kullanılır. 'news' -s ile bitse de tekildir: The news is good.",
          "glass (malzeme, sayılamaz) / a glass (bardak) / glasses (gözlük)."
        ],
        examples: [
          { en: "We produce laminated glass for bridge windows.", tr: "Kaptan köşkü pencereleri için lamine cam üretiyoruz." },
          { en: "Could you send me some information about the delivery?", tr: "Teslimat hakkında biraz bilgi gönderebilir misiniz?" },
          { en: "I'd love a glass of water, thanks.", tr: "Bir bardak su çok iyi olur, teşekkürler." },
          { en: "She's an engineer at a shipyard in Korea.", tr: "Kore'deki bir tersanede mühendis." },
          { en: "The quotation I sent you is valid for thirty days.", tr: "Size gönderdiğim teklif otuz gün geçerlidir." }
        ]
      },
      cards: [
        { en: "equipment", tr: "ekipman (sayılamaz)", ex: "All our testing equipment is calibrated every year." },
        { en: "a piece of advice", tr: "bir tavsiye", ex: "Let me give you a piece of advice: book early." },
        { en: "information", tr: "bilgi (sayılamaz)", ex: "Thank you for the information about the vessel." },
        { en: "feedback", tr: "geri bildirim (sayılamaz)", ex: "We appreciate your feedback on the last delivery." },
        { en: "a glass of", tr: "bir bardak ...", ex: "Would you like a glass of tea?" },
        { en: "luggage", tr: "bagaj (sayılamaz)", ex: "I only have one piece of luggage." }
      ],
      exercises: [
        { type: "mcq", q: "We need ___ information about the heated glass you offer.",
          options: ["some", "an", "a few", "many"], answer: 0,
          explain: "information sayılamaz; 'an', 'a few', 'many' sayılabilen isimlerle kullanılır." },
        { type: "mcq", q: "She works as ___ engineer at a shipyard in Busan.",
          options: ["a", "— (artikel yok)", "the", "an"], answer: 3,
          explain: "Meslek söylerken a/an kullanılır; 'engineer' ünlü sesle başladığı için 'an'." },
        { type: "mcq", q: "Could you give me ___ advice about visiting Istanbul?",
          options: ["an", "a few", "a piece of", "many"], answer: 2,
          explain: "advice sayılamaz: 'an / a few / many advice' yanlış. Tek bir tavsiye için 'a piece of advice' (ya da 'some advice')." },
        { type: "fill", q: "I have a meeting with ___ CEO of a Greek shipping company tomorrow.",
          answers: ["the"], hint: "şirketin tek CEO'su",
          explain: "Bir şirketin tek bir CEO'su vardır → belirli → 'the'." },
        { type: "fill", q: "All our testing ___ (equipment) is calibrated every year.",
          answers: ["equipment"],
          explain: "equipment sayılamaz, çoğul -s almaz; fiil de tekil (is)." },
        { type: "mcq", q: "In general, ___ glass breaks more easily than steel.",
          options: ["a", "the", "— (artikel yok)", "an"], answer: 2,
          explain: "Malzemeden genel olarak bahsederken artikel kullanılmaz." },
        { type: "match", pairs: [["a glass of water", "bir bardak su"], ["glass", "cam (malzeme)"], ["glasses", "gözlük"],
          ["a piece of luggage", "bir parça bagaj"], ["equipment", "ekipman"]],
          explain: "glass malzeme olarak sayılamaz; 'a glass' bardak, 'glasses' gözlük demektir." },
        { type: "mcq", q: "How ___ luggage do you have with you?",
          options: ["many", "much", "few", "a lot"], answer: 1,
          explain: "luggage sayılamaz → 'how much'." },
        { type: "order", answer: "Could you send us some information about the price?",
          tr: "Bize fiyat hakkında biraz bilgi gönderebilir misiniz?",
          explain: "some + sayılamaz isim (information); 'the price' belirli fiyat." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["We need some new furnitures for the office.", "We need a new furniture for the office.",
            "We need some new furniture for the office.", "We need new furnitures for the office."], answer: 2,
          explain: "furniture sayılamaz: -s almaz, 'a' ile kullanılmaz." },
        { type: "listen", text: "The news about the order is very good.",
          tr: "Siparişle ilgili haberler çok iyi." },
        { type: "fill", q: "What ___ lovely view! Is this your hometown?",
          answers: ["a"],
          explain: "What + a/an + sıfat + tekil sayılabilen isim (What a lovely view!)." },
        { type: "mcq", q: "We are ___ only manufacturer in the region with DNV approval for heated glass.",
          options: ["a", "an", "the", "— (artikel yok)"], answer: 2,
          explain: "'only' tek olanı belirtir → 'the only'." }
      ]
    },
    {
      id: "grammar-02",
      title: "Comparatives & Superlatives",
      level: "B1+",
      week: 1,
      intro: {
        tr: "Kısa sıfatlar -er / -est alır (cheap → cheaper → the cheapest), uzun sıfatlar more / the most ile kullanılır (more reliable, the most expensive). 'as ... as' eşitliği, 'not as ... as' daha az olmayı gösterir. 'The more ..., the more ...' bir şey arttıkça diğerinin de değiştiğini anlatır. Farkı güçlendirmek için much / far / a lot, azaltmak için slightly / a bit kullanılır.",
        points: [
          "Düzensiz: good → better → the best; bad → worse → the worst; far → further.",
          "Büyük fark: much / far / a lot cheaper; küçük fark: slightly / a bit thicker.",
          "Eşitlik: as strong as; 'twice as thick as' = iki katı kalın.",
          "The + comparative ..., the + comparative: The bigger the order, the lower the price.",
          "Zarflar: more fluently, more carefully (fluentlier değil!)."
        ],
        examples: [
          { en: "Laminated glass is much safer than ordinary float glass.", tr: "Lamine cam sıradan float camdan çok daha güvenlidir." },
          { en: "This is the thickest pane we have ever produced.", tr: "Bu, şimdiye kadar ürettiğimiz en kalın cam levha." },
          { en: "The bigger the order, the lower the unit price.", tr: "Sipariş ne kadar büyükse birim fiyat o kadar düşük olur." },
          { en: "My brother isn't as tall as me.", tr: "Erkek kardeşim benim kadar uzun değil." },
          { en: "Izmir is a bit warmer than Istanbul in winter.", tr: "İzmir kışın İstanbul'dan biraz daha sıcaktır." }
        ]
      },
      cards: [
        { en: "much cheaper", tr: "çok daha ucuz", ex: "Shipping by sea is much cheaper than by air." },
        { en: "slightly thicker", tr: "biraz daha kalın", ex: "The new pane is slightly thicker than the old one." },
        { en: "as ... as", tr: "... kadar", ex: "Our glass is as clear as the German product." },
        { en: "twice as ... as", tr: "iki katı ...", ex: "This window is twice as heavy as the standard one." },
        { en: "the ... -est ever", tr: "şimdiye kadarki en ...", ex: "It was the best holiday I've ever had." },
        { en: "the more ..., the more ...", tr: "ne kadar ... o kadar ...", ex: "The more you practise, the easier it gets." }
      ],
      exercises: [
        { type: "mcq", q: "Our new heated windows are ___ than the previous model.",
          options: ["more efficient", "efficienter", "most efficient", "as efficient"], answer: 0,
          explain: "Uzun sıfat (efficient) → more efficient than." },
        { type: "mcq", q: "This is ___ restaurant in town — you have to try it!",
          options: ["the best", "the better", "best", "the most good"], answer: 0,
          explain: "good → better → the best (düzensiz)." },
        { type: "fill", q: "The weather today is ___ (bad) than yesterday.",
          answers: ["worse"],
          explain: "bad → worse → the worst (düzensiz)." },
        { type: "fill", q: "The earlier you confirm the order, the ___ (soon) we can deliver.",
          answers: ["sooner"],
          explain: "The + comparative ..., the + comparative: the earlier ..., the sooner ..." },
        { type: "mcq", q: "Tempered glass is about five times ___ annealed glass of the same thickness.",
          options: ["stronger as", "as strong than", "stronger than", "more strong than"], answer: 2,
          explain: "Kısa sıfat: strong → stronger than. 'as strong as' de olurdu ama 'as ... than' yanlış." },
        { type: "mcq", q: "The new supplier's price is only ___ cheaper — about two percent less.",
          options: ["far", "a lot", "much", "slightly"], answer: 3,
          explain: "Küçük fark → slightly / a bit." },
        { type: "order", answer: "The more you practise, the easier it gets.",
          tr: "Ne kadar çok pratik yaparsan o kadar kolaylaşır.",
          explain: "The + comparative ..., the + comparative ... kalıbı." },
        { type: "match", pairs: [["good", "better"], ["bad", "worse"], ["far", "further"], ["little", "less"], ["many", "more"]],
          explain: "Düzensiz karşılaştırma biçimleri ezberlenmelidir." },
        { type: "mcq", q: "Istanbul isn't ___ as I expected; it's actually quite affordable.",
          options: ["as expensive", "so expensive than", "expensive", "more expensive"], answer: 0,
          explain: "not as + sıfat + as = ... kadar ... değil." },
        { type: "fill", q: "This is ___ (comfortable) hotel I have ever stayed in.",
          answers: ["the most comfortable"],
          explain: "Uzun sıfatın üstünlük hali: the most comfortable." },
        { type: "listen", text: "Our glass is twice as thick as the old one.",
          tr: "Camımız eskisinin iki katı kalınlığında." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["She speaks English more fluent than me.", "She speaks English most fluently than me.",
            "She speaks English more fluently than me.", "She speaks English fluentlier than me."], answer: 2,
          explain: "Fiili niteleyen zarf (fluently) → more fluently than." },
        { type: "order", answer: "This is the thickest glass we have ever produced.",
          alts: ["This glass is the thickest we have ever produced."],
          tr: "Bu, şimdiye kadar ürettiğimiz en kalın cam.",
          explain: "the + -est + ever (present perfect) kalıbı." }
      ]
    },
    // ───────────────────────── WEEK 2 ─────────────────────────
    {
      id: "grammar-03",
      title: "Modal Verbs: Ability, Obligation, Permission, Advice",
      level: "B1+",
      week: 2,
      intro: {
        tr: "Modal fiiller yetenek (can, be able to), zorunluluk (must, have to, need to), izin (can, may, could) ve tavsiye (should, ought to, had better) bildirir. 'Must' çoğunlukla kural veya konuşanın kendi zorunluluğu, 'have to' dışarıdan gelen zorunluluktur. Olumsuzda anlam değişir: 'mustn't' yasak, 'don't have to / don't need to / needn't' gerek yok demektir. Modal'dan sonra fiil yalın gelir (to yok, -s yok).",
        points: [
          "mustn't = yasak; don't have to / needn't = gerekli değil.",
          "Gelecek ve geçmişte yetenek: will be able to / was able to (tek seferlik başarı).",
          "Kibar izin: Could I ...? / May I ...?",
          "Tavsiye: should / ought to; güçlü uyarı: You'd better + yalın fiil.",
          "Geçmiş zorunluluk: had to (must'ın geçmişi yoktur)."
        ],
        examples: [
          { en: "All bridge windows must comply with ISO 3903.", tr: "Tüm köprüüstü pencereleri ISO 3903'e uymak zorundadır." },
          { en: "You don't have to pay in advance; thirty days is fine.", tr: "Peşin ödemek zorunda değilsiniz; otuz gün uygundur." },
          { en: "We were able to ship the order despite the strike.", tr: "Greve rağmen siparişi sevk etmeyi başardık." },
          { en: "You should try the fish here — it's amazing.", tr: "Buradaki balığı denemelisin, harika." },
          { en: "Could I use your phone for a moment?", tr: "Telefonunuzu bir dakikalığına kullanabilir miyim?" }
        ]
      },
      cards: [
        { en: "must comply with", tr: "... ile uyumlu olmak zorunda", ex: "The glass must comply with SOLAS requirements." },
        { en: "mustn't", tr: "yasak, yapmamalı", ex: "You mustn't smoke in the factory." },
        { en: "don't have to", tr: "zorunda değil", ex: "You don't have to come if you're busy." },
        { en: "be able to", tr: "-ebilmek", ex: "We will be able to deliver in May." },
        { en: "had better", tr: "-se iyi olur (uyarı)", ex: "We'd better leave now or we'll miss the ferry." },
        { en: "May I ...?", tr: "... yapabilir miyim? (resmi izin)", ex: "May I ask a question about the warranty?" }
      ],
      exercises: [
        { type: "mcq", q: "Visitors ___ enter the tempering area without safety glasses. It's strictly forbidden.",
          options: ["don't have to", "mustn't", "needn't", "aren't able to"], answer: 1,
          explain: "Yasak → mustn't. 'don't have to / needn't' gerek yok demektir." },
        { type: "mcq", q: "You ___ bring anything to the party — we have plenty of food.",
          options: ["don't have to", "mustn't", "can't", "had better"], answer: 0,
          explain: "Gerek yok → don't have to." },
        { type: "fill", q: "After the new furnace is installed, we ___ (be able to) produce curved glass.",
          answers: ["will be able to", "'ll be able to", "shall be able to"], hint: "gelecek",
          explain: "can'in gelecek hali yoktur → will be able to." },
        { type: "mcq", q: "___ I sit here? — Sure, go ahead.",
          options: ["Must", "Need", "Should", "May"], answer: 3,
          explain: "İzin isterken May I / Can I / Could I kullanılır." },
        { type: "mcq", q: "You look exhausted. You ___ go to bed earlier.",
          options: ["should", "mustn't", "don't have to", "may"], answer: 0,
          explain: "Tavsiye → should." },
        { type: "fill", q: "Yesterday the forwarder was late, so we ___ (have to) wait three hours at the port.",
          answers: ["had to"],
          explain: "Geçmişte zorunluluk → had to (must'ın geçmişi yok)." },
        { type: "mcq", q: "Despite the storm, the crew ___ unload the cargo safely.",
          options: ["could", "were able to", "can", "must"], answer: 1,
          explain: "Geçmişte tek seferlik başarı → were able to / managed to; 'could' genel yetenek içindir." },
        { type: "match", pairs: [["mustn't", "yasak"], ["don't have to", "gerek yok"], ["should", "tavsiye"],
          ["may", "izin"], ["be able to", "yetenek"]],
          explain: "Her modalın temel işlevi." },
        { type: "order", answer: "Could you send us the test certificates by Friday?",
          tr: "Test sertifikalarını cumaya kadar bize gönderebilir misiniz?",
          explain: "Kibar rica: Could you + yalın fiil ...?" },
        { type: "mcq", q: "We'd better ___ the customer before the price goes up.",
          options: ["to call", "calling", "call", "called"], answer: 2,
          explain: "had better + yalın fiil (to yok)." },
        { type: "listen", text: "You don't need to print the drawings.",
          tr: "Çizimleri yazdırmana gerek yok." },
        { type: "fill", q: "When I was a child, I ___ swim very well, but now I'm out of practice.",
          answers: ["could", "was able to"],
          explain: "Geçmişte genel yetenek → could / was able to." },
        { type: "mcq", q: "Which sentence means 'it is not necessary'?",
          options: ["You mustn't sign the contract today.", "You can't sign the contract today.",
            "You needn't sign the contract today.", "You shouldn't sign the contract today."], answer: 2,
          explain: "needn't = gerek yok; mustn't = yasak." }
      ]
    },
    {
      id: "grammar-04",
      title: "Gerund vs Infinitive",
      level: "B1+",
      week: 2,
      intro: {
        tr: "Bazı fiillerden sonra -ing (gerund), bazılarından sonra 'to + fiil' (infinitive) gelir. avoid, enjoy, finish, consider, suggest, mind → -ing; agree, decide, offer, promise, refuse, plan, manage → to. stop, remember, forget, try gibi fiillerde ikisi de gelebilir ama anlam değişir. Edatlardan (in, on, of, about, look forward to) sonra her zaman -ing gelir.",
        points: [
          "-ing alanlar: avoid, enjoy, finish, consider, suggest, mind, keep, deny.",
          "to alanlar: agree, decide, offer, promise, refuse, plan, manage, afford.",
          "look forward to / be used to / object to → buradaki 'to' edattır: + -ing.",
          "stop doing (bırakmak) / stop to do (bir şey yapmak için durmak).",
          "remember doing (yaptığını hatırlamak) / remember to do (yapmayı unutmamak); try doing (denemek) / try to do (çabalamak)."
        ],
        examples: [
          { en: "We look forward to hearing from you.", tr: "Sizden haber almayı dört gözle bekliyoruz." },
          { en: "The supplier agreed to reduce the price by five percent.", tr: "Tedarikçi fiyatı yüzde beş düşürmeyi kabul etti." },
          { en: "Please remember to attach the drawings.", tr: "Lütfen çizimleri eklemeyi unutmayın." },
          { en: "I enjoy cooking for my friends at the weekend.", tr: "Hafta sonu arkadaşlarıma yemek yapmaktan keyif alırım." },
          { en: "We stopped using silicone gaskets last year.", tr: "Geçen yıl silikon conta kullanmayı bıraktık." }
        ]
      },
      cards: [
        { en: "look forward to + -ing", tr: "...meyi dört gözle beklemek", ex: "I look forward to meeting you in Oslo." },
        { en: "agree to do", tr: "yapmayı kabul etmek", ex: "They agreed to share the transport cost." },
        { en: "avoid doing", tr: "yapmaktan kaçınmak", ex: "Avoid touching the coated surface." },
        { en: "be used to doing", tr: "yapmaya alışkın olmak", ex: "I'm used to working long hours." },
        { en: "remember to do", tr: "yapmayı unutmamak", ex: "Remember to bring your passport." },
        { en: "can't afford to", tr: "...meyi göze alamamak", ex: "We can't afford to lose this customer." }
      ],
      exercises: [
        { type: "mcq", q: "We look forward to ___ you at the exhibition in Hamburg.",
          options: ["seeing", "see", "to see", "have seen"], answer: 0,
          explain: "look forward to: 'to' edattır → -ing." },
        { type: "mcq", q: "The customer refused ___ for the damaged panels.",
          options: ["paying", "paid", "pay", "to pay"], answer: 3,
          explain: "refuse + to do." },
        { type: "fill", q: "Would you mind ___ (close) the window? It's a bit cold.",
          answers: ["closing"],
          explain: "mind + -ing." },
        { type: "fill", q: "We have decided ___ (open) an office in Rotterdam.",
          answers: ["to open"],
          explain: "decide + to do." },
        { type: "mcq", q: "I remember ___ him at a conference in Oslo years ago.",
          options: ["meeting", "to meet", "meet", "met"], answer: 0,
          explain: "Geçmişte yaptığını hatırlamak → remember + -ing." },
        { type: "mcq", q: "Please remember ___ the packing list with the shipment.",
          options: ["including", "include", "to include", "included"], answer: 2,
          explain: "Yapılacak bir şeyi unutmamak → remember + to do." },
        { type: "mcq", q: "On the way to the shipyard, we stopped ___ some coffee.",
          options: ["having", "to have", "have", "had"], answer: 1,
          explain: "Kahve içmek için durduk → stop + to do (amaç)." },
        { type: "match", pairs: [["stop smoking", "sigarayı bırakmak"], ["stop to smoke", "sigara içmek için durmak"],
          ["remember locking", "kilitlediğini hatırlamak"], ["remember to lock", "kilitlemeyi unutmamak"],
          ["try to open", "açmaya çalışmak"]],
          explain: "stop / remember / try fiillerinde -ing ve to farklı anlam verir." },
        { type: "order", answer: "We are considering opening a new factory.",
          tr: "Yeni bir fabrika açmayı düşünüyoruz.",
          explain: "consider + -ing." },
        { type: "mcq", q: "The window is still fogging up? Try ___ the heater on — maybe that will help.",
          options: ["turning", "to turn", "turn", "turned"], answer: 0,
          explain: "Bir çözümü deneme amaçlı yapmak → try + -ing." },
        { type: "fill", q: "I'm not used to ___ (get) up so early.",
          answers: ["getting"],
          explain: "be used to + -ing (alışkın olmak)." },
        { type: "listen", text: "He managed to finish the report on time.",
          tr: "Raporu zamanında bitirmeyi başardı." },
        { type: "mcq", q: "They suggested ___ the meeting until next week.",
          options: ["postponing", "to postpone", "postpone", "to postponing"], answer: 0,
          explain: "suggest + -ing (suggest to do yanlıştır)." }
      ]
    },
    // ───────────────────────── WEEK 3 ─────────────────────────
    {
      id: "grammar-05",
      title: "Conditionals 0, 1, 2 & unless / provided that",
      level: "B2",
      week: 3,
      intro: {
        tr: "Zero conditional genel gerçekleri (If + present, present), first conditional gerçekçi gelecek olasılıklarını (If + present, will), second conditional hayali veya düşük ihtimalli durumları (If + past, would) anlatır. 'Unless' = if ... not. 'Provided (that)', 'providing' ve 'as long as' = ... şartıyla. Koşul (if) cümleciğinde will / would kullanılmaz.",
        points: [
          "Zero: If you heat glass too quickly, it cracks.",
          "First: If you confirm today, we will start production on Monday.",
          "Second: If I had more time, I would learn Spanish. Tavsiye: If I were you, I'd ...",
          "unless = if not: We can't ship unless we receive the payment.",
          "provided that / as long as = şartıyla: We can offer a discount as long as you order 100 units.",
          "If cümleciğinde will yok: If it rains (If it will rain değil)."
        ],
        examples: [
          { en: "If you confirm the order today, we will start production on Monday.", tr: "Siparişi bugün onaylarsanız pazartesi üretime başlarız." },
          { en: "We can't ship the goods unless we receive the payment.", tr: "Ödemeyi almadıkça malları sevk edemeyiz." },
          { en: "If I lived by the sea, I would go swimming every day.", tr: "Deniz kenarında yaşasaydım her gün yüzmeye giderdim." },
          { en: "You can borrow my car as long as you bring it back tonight.", tr: "Bu gece geri getirmen şartıyla arabamı ödünç alabilirsin." }
        ]
      },
      cards: [
        { en: "unless", tr: "-medikçe, ...mezse", ex: "Unless we hear from you, we'll ship on Monday." },
        { en: "provided that", tr: "... şartıyla", ex: "We accept returns provided that the glass is undamaged." },
        { en: "as long as", tr: "... olduğu sürece", ex: "I'll come as long as I finish work early." },
        { en: "If I were you, ...", tr: "Senin yerinde olsam, ...", ex: "If I were you, I'd ask for a discount." },
        { en: "in case", tr: "... ihtimaline karşı", ex: "Take an umbrella in case it rains." },
        { en: "even if", tr: "... bile olsa", ex: "Even if the ship is late, we'll keep the windows in stock." }
      ],
      exercises: [
        { type: "mcq", q: "If you ___ the order by Friday, we will deliver in March.",
          options: ["confirm", "will confirm", "confirmed", "would confirm"], answer: 0,
          explain: "First conditional: If + present simple, will + fiil." },
        { type: "mcq", q: "If I ___ you, I would accept the job offer.",
          options: ["am", "was being", "were", "will be"], answer: 2,
          explain: "Tavsiye kalıbı: If I were you, I would ..." },
        { type: "fill", q: "If it ___ (rain) tomorrow, we'll stay at home and watch a film.",
          answers: ["rains"],
          explain: "If cümleciğinde gelecek anlamına rağmen present simple kullanılır." },
        { type: "fill", q: "If I won the lottery, I ___ (buy) a small boat.",
          answers: ["would buy", "'d buy"],
          explain: "Second conditional: If + past, would + fiil." },
        { type: "mcq", q: "We can't start production ___ we receive the signed drawings.",
          options: ["if", "provided", "as long as", "unless"], answer: 3,
          explain: "unless = if not: imzalı çizimleri almadıkça." },
        { type: "mcq", q: "We can offer a five percent discount ___ you order at least two hundred portlights.",
          options: ["unless", "provided that", "even if", "in case"], answer: 1,
          explain: "provided that = ... şartıyla." },
        { type: "mcq", q: "If you heat glass too quickly, it ___.",
          options: ["cracks", "would crack", "cracked", "had cracked"], answer: 0,
          explain: "Genel gerçek → zero conditional (present, present)." },
        { type: "order", answer: "We will deliver on time as long as you pay the deposit.",
          tr: "Kaporayı ödediğiniz sürece zamanında teslim ederiz.",
          explain: "as long as = ... şartıyla; ardından present simple." },
        { type: "match", pairs: [["Zero conditional", "If you press this, it stops."], ["First conditional", "If it's sunny, we'll go out."],
          ["Second conditional", "If I had a car, I'd drive."], ["unless", "if ... not"], ["as long as", "provided that"]],
          explain: "Koşul tiplerini ve eş anlamlı bağlaçları eşleştir." },
        { type: "mcq", q: "What would you do if you ___ a famous person on the street?",
          options: ["meet", "will meet", "met", "would meet"], answer: 2,
          explain: "Hayali durum → second conditional: if + past simple." },
        { type: "listen", text: "Unless the weather improves, the ship will be delayed.",
          tr: "Hava düzelmezse gemi gecikecek." },
        { type: "fill", q: "I'll lend you my car ___ you drive carefully.",
          answers: ["as long as", "so long as", "provided", "provided that", "providing", "if"], hint: "şartıyla",
          explain: "as long as / provided (that) = ... şartıyla." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["If the glass breaks, we will replace it.", "If the glass will break, we will replace it.",
            "If the glass broke, we will replace it.", "If the glass breaks, we would replace it."], answer: 0,
          explain: "First conditional: If + present, will. If cümleciğinde will kullanılmaz." }
      ]
    },
    {
      id: "grammar-06",
      title: "Passive Voice",
      level: "B2",
      week: 3,
      intro: {
        tr: "Edilgen yapı (be + V3), işi kimin yaptığı önemli olmadığında veya ürün/süreç ön planda olduğunda kullanılır; teknik ve iş İngilizcesinde çok yaygındır. Zamanı 'be' fiili gösterir: is tempered, was tested, has been certified, will be shipped, is being produced. Yapan önemliyse 'by' ile eklenir. Modallarla: must be approved, can be delivered.",
        points: [
          "Present: is/are + V3 → The glass is tempered.",
          "Past: was/were + V3 → The panes were tested last week.",
          "Present perfect: has/have been + V3 → It has been certified by DNV.",
          "Continuous: is being + V3 → The windows are being installed.",
          "Future / modal: will be / must be / can be + V3."
        ],
        examples: [
          { en: "The glass is tempered at around seven hundred degrees.", tr: "Cam yaklaşık yedi yüz derecede temperlenir." },
          { en: "Our bridge windows have been certified by DNV.", tr: "Köprüüstü pencerelerimiz DNV tarafından sertifikalandırıldı." },
          { en: "The order will be shipped next week.", tr: "Sipariş gelecek hafta sevk edilecek." },
          { en: "I was born in Izmir, but I grew up in Ankara.", tr: "İzmir'de doğdum ama Ankara'da büyüdüm." },
          { en: "The windows are being installed right now.", tr: "Pencereler şu anda takılıyor." }
        ]
      },
      cards: [
        { en: "is tempered", tr: "temperlenir", ex: "Each pane is tempered and heat-soaked." },
        { en: "has been certified", tr: "sertifikalandırıldı", ex: "The design has been certified by Bureau Veritas." },
        { en: "will be shipped", tr: "sevk edilecek", ex: "The crates will be shipped from Izmir port." },
        { en: "is being produced", tr: "üretiliyor (şu an)", ex: "Your order is being produced at the moment." },
        { en: "was born", tr: "doğdu", ex: "Where were you born?" },
        { en: "must be approved", tr: "onaylanmalı", ex: "The drawings must be approved by the class society." }
      ],
      exercises: [
        { type: "mcq", q: "All our toughened panes ___ according to ISO 614.",
          options: ["test", "have tested", "are testing", "are tested"], answer: 3,
          explain: "Camlar test edilir (kendileri test etmez) → present passive: are tested." },
        { type: "fill", q: "The glass ___ (test) last week and it passed.",
          answers: ["was tested"],
          explain: "Geçmiş zaman edilgen: was + V3." },
        { type: "fill", q: "Our heated windows ___ (approve) by Lloyd's Register since 2019.",
          answers: ["have been approved"],
          explain: "since → present perfect passive: have been + V3." },
        { type: "mcq", q: "Sorry, you can't use the meeting room now — it ___.",
          options: ["is cleaning", "has cleaned", "is being cleaned", "cleans"], answer: 2,
          explain: "Şu anda temizleniyor → present continuous passive: is being cleaned." },
        { type: "mcq", q: "The shipment ___ by the end of next week.",
          options: ["will deliver", "will be delivered", "is delivering", "delivers"], answer: 1,
          explain: "Gelecekte edilgen: will be + V3." },
        { type: "mcq", q: "This photo ___ in Cappadocia during our holiday.",
          options: ["was taken", "took", "was taking", "has taken"], answer: 0,
          explain: "Fotoğraf çekildi → past passive: was taken." },
        { type: "order", answer: "The windows must be installed by a qualified technician.",
          tr: "Pencereler kalifiye bir teknisyen tarafından takılmalıdır.",
          explain: "Modal + be + V3; yapan kişi 'by' ile." },
        { type: "fill", q: "English ___ (speak) all over the world.",
          answers: ["is spoken"],
          explain: "Genel gerçek, edilgen: is + V3." },
        { type: "mcq", q: "Make it passive: 'Someone has damaged two panes during transport.'",
          options: ["Two panes were damaged during transport.", "Two panes are damaged during transport.",
            "Two panes have damaged during transport.", "Two panes have been damaged during transport."], answer: 3,
          explain: "has damaged → have been damaged (zaman korunur, özne çoğul)." },
        { type: "match", pairs: [["Present simple", "is shipped"], ["Past simple", "was shipped"], ["Present perfect", "has been shipped"],
          ["Future", "will be shipped"], ["Present continuous", "is being shipped"]],
          explain: "Edilgende zamanı 'be' fiili taşır, ana fiil hep V3'tür." },
        { type: "listen", text: "The order has already been shipped.",
          tr: "Sipariş çoktan sevk edildi." },
        { type: "mcq", q: "Where ___? — In Izmir, but I grew up in Ankara.",
          options: ["were you born", "did you born", "are you born", "have you been born"], answer: 0,
          explain: "Doğmak İngilizcede edilgendir: be born → Where were you born?" },
        { type: "fill", q: "The drawings ___ (must / sign) before production can start.",
          answers: ["must be signed"],
          explain: "Modal edilgen: must be + V3." }
      ]
    },
    // ───────────────────────── WEEK 4 ─────────────────────────
    {
      id: "grammar-07",
      title: "Relative Clauses",
      level: "B2",
      week: 4,
      intro: {
        tr: "Relative clause (sıfat cümleciği) bir ismi tanımlar veya ona ek bilgi verir. Defining (tanımlayıcı) cümlecikte virgül yoktur ve 'that' kullanılabilir; non-defining (ek bilgi veren) cümlecikte virgül vardır ve 'that' kullanılamaz. who (insan), which (şey), whose (sahiplik), where (yer), when (zaman). ', which' bütün bir cümleyi de niteleyebilir.",
        points: [
          "Defining: The glass that/which we use comes from Germany. Nesne konumundaysa zamir düşebilir: The glass we use ...",
          "Non-defining: Mr Jensen, who is our Danish customer, visited us. → virgül var, 'that' yok, zamir düşmez.",
          "whose = sahiplik: the customer whose order was delayed.",
          "where = yer, when = zaman: the factory where we produce ..., the day when we met.",
          "', which' bütün cümleyi niteler: The ship was late, which caused problems."
        ],
        examples: [
          { en: "The customer who called this morning wants a quotation.", tr: "Bu sabah arayan müşteri teklif istiyor." },
          { en: "Our new furnace, which was installed in May, can temper large panes.", tr: "Mayısta kurulan yeni fırınımız büyük camları temperleyebiliyor." },
          { en: "That's the restaurant where we had our first date.", tr: "İlk randevumuza çıktığımız restoran orası." },
          { en: "I have a friend whose father is a ship captain.", tr: "Babası gemi kaptanı olan bir arkadaşım var." },
          { en: "The vessel arrived late, which delayed the installation.", tr: "Gemi geç geldi, bu da montajı geciktirdi." }
        ]
      },
      cards: [
        { en: "whose", tr: "-in/-ın (sahiplik)", ex: "We contacted the yard whose order was delayed." },
        { en: "where", tr: "-dığı yer", ex: "This is the hall where the glass is laminated." },
        { en: ", which ...", tr: "..., bu da ...", ex: "He missed the flight, which was annoying." },
        { en: "the one that", tr: "... olan", ex: "I prefer the one that has a heated layer." },
        { en: "the day when", tr: "... olduğu gün", ex: "I remember the day when I started this job." },
        { en: "someone who", tr: "... biri", ex: "We need someone who speaks German." }
      ],
      exercises: [
        { type: "mcq", q: "The engineer ___ designed these bridge windows is from Norway.",
          options: ["which", "who", "whose", "where"], answer: 1,
          explain: "İnsan için who (ya da that)." },
        { type: "mcq", q: "This is the café ___ we first met.",
          options: ["which", "who", "where", "whose"], answer: 2,
          explain: "Yer + cümle (we met) → where." },
        { type: "fill", q: "We apologised to the customer ___ order had been delayed.",
          answers: ["whose"],
          explain: "Sahiplik (müşterinin siparişi) → whose." },
        { type: "mcq", q: "Our new furnace, ___ was installed in May, can temper three-metre panes.",
          options: ["which", "that", "what", "who"], answer: 0,
          explain: "Virgüllü (non-defining) cümlecikte 'that' kullanılmaz → which." },
        { type: "mcq", q: "The ship arrived two days late, ___ meant we had to reschedule the installation.",
          options: ["that", "who", "what", "which"], answer: 3,
          explain: "', which' önceki cümlenin tamamını niteler." },
        { type: "fill", q: "Is this the book ___ you were talking about?",
          answers: ["that", "which"],
          explain: "Şey için defining cümlecik → that / which." },
        { type: "order", answer: "The customer who called this morning wants a quotation.",
          tr: "Bu sabah arayan müşteri teklif istiyor.",
          explain: "Özne + who-cümleciği + ana fiil." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["My sister, that lives in London, is a nurse.", "My sister who, lives in London, is a nurse.",
            "My sister, who lives in London, is a nurse.", "My sister, which lives in London, is a nurse."], answer: 2,
          explain: "Non-defining + insan → virgüller arasında who." },
        { type: "match", pairs: [["who", "insanlar için"], ["which", "şeyler için"], ["whose", "sahiplik"],
          ["where", "yer"], ["when", "zaman"]],
          explain: "İlgi zamirlerinin temel kullanımları." },
        { type: "listen", text: "The factory where we make the glass is near Izmir.",
          tr: "Camı ürettiğimiz fabrika İzmir'e yakın." },
        { type: "mcq", q: "In which sentence can the relative pronoun be left out?",
          options: ["The glass that we ordered has arrived.", "The man who called you is here.",
            "The window that broke was replaced.", "Our CEO, who is in Oslo, will call you."], answer: 0,
          explain: "Zamir cümleciğin nesnesiyse (we ordered it) düşebilir: The glass we ordered ..." },
        { type: "fill", q: "I'll never forget the day ___ I got my first job.",
          answers: ["when", "that", "on which"],
          explain: "Zaman ifadesi → when (veya that)." }
      ]
    },
    {
      id: "grammar-08",
      title: "Reported Speech & Reporting Verbs",
      level: "B2",
      week: 4,
      intro: {
        tr: "Dolaylı anlatımda birinin sözü aktarılır; genellikle zaman bir derece geriye kayar (am → was, will → would, have done → had done). Sorular düz cümle sırasıyla aktarılır (She asked where I lived) ve evet/hayır sorularında if / whether kullanılır. Rica ve emirler: ask / tell + kişi + to do. suggest, recommend, insist gibi fiillerin kendi kalıpları vardır.",
        points: [
          "say (something) / tell + kişi (something): He told me ..., He said that ...",
          "Sorular: She asked what time the meeting started. (do/does yok, soru sırası yok)",
          "Rica/emir: The customer asked us to send ..., told us not to ...",
          "suggest / recommend + -ing veya + that + özne + (should) + yalın fiil. 'suggest to do' yanlış!",
          "insist on + -ing; offer / agree / refuse / promise + to do.",
          "Zaman/yer: tomorrow → the next day, next week → the following week, here → there."
        ],
        examples: [
          { en: "He said they would send the samples the following week.", tr: "Numuneleri bir sonraki hafta göndereceklerini söyledi." },
          { en: "She asked me where I lived.", tr: "Bana nerede yaşadığımı sordu." },
          { en: "The customer asked us to speed up the delivery.", tr: "Müşteri teslimatı hızlandırmamızı istedi." },
          { en: "Our agent suggested quoting the price in euros.", tr: "Acentemiz fiyatı euro olarak vermeyi önerdi." },
          { en: "My friend recommended that I visit Cappadocia.", tr: "Arkadaşım Kapadokya'yı ziyaret etmemi önerdi." }
        ]
      },
      cards: [
        { en: "He told me that ...", tr: "Bana ... dedi", ex: "He told me that the vessel was in Piraeus." },
        { en: "She asked if ...", tr: "... olup olmadığını sordu", ex: "She asked if we had DNV approval." },
        { en: "suggest doing", tr: "yapmayı önermek", ex: "I suggest meeting at the hotel." },
        { en: "insist on doing", tr: "yapmakta ısrar etmek", ex: "The captain insisted on checking every window." },
        { en: "ask someone to do", tr: "birinden bir şey yapmasını istemek", ex: "They asked us to resend the invoice." },
        { en: "promise to do", tr: "yapmaya söz vermek", ex: "She promised to call me back." }
      ],
      exercises: [
        { type: "mcq", q: "'We will send the samples next week.' → He said they ___ the samples the following week.",
          options: ["will send", "would send", "sent", "have sent"], answer: 1,
          explain: "will → would (zaman bir derece geriye kayar)." },
        { type: "mcq", q: "She asked me where ___.",
          options: ["I lived", "do I live", "did I live", "I am living"], answer: 0,
          explain: "Dolaylı soruda düz cümle sırası: where I lived." },
        { type: "fill", q: "'Are you coming to the dinner?' → He asked me ___ I was coming to the dinner.",
          answers: ["if", "whether"],
          explain: "Evet/hayır sorusu → if / whether." },
        { type: "mcq", q: "The inspector ___ us that the certificates were missing.",
          options: ["said", "spoke", "talked", "told"], answer: 3,
          explain: "tell + kişi (told us); say'den sonra doğrudan kişi gelmez." },
        { type: "mcq", q: "The customer asked us ___ the delivery.",
          options: ["speed up", "to speed up", "speeding up", "that we speed up"], answer: 1,
          explain: "ask + kişi + to do." },
        { type: "mcq", q: "Our agent suggested ___ the price in euros.",
          options: ["to quote", "quote", "quoting", "us to quote"], answer: 2,
          explain: "suggest + -ing; 'suggest to do' ve 'suggest us to do' yanlıştır." },
        { type: "fill", q: "The captain insisted ___ (check) every window himself.",
          answers: ["on checking"], hint: "insist + edat + -ing",
          explain: "insist on + -ing." },
        { type: "order", answer: "She told me not to worry about the exam.",
          tr: "Bana sınav için endişelenmememi söyledi.",
          explain: "Olumsuz emir: tell + kişi + not to do." },
        { type: "mcq", q: "'I've lost my keys,' she said. → She said she ___ her keys.",
          options: ["had lost", "has lost", "was losing", "have lost"], answer: 0,
          explain: "Present perfect → past perfect: had lost." },
        { type: "match", pairs: [["'Let's meet on Monday.'", "suggest"], ["'I'll definitely call you.'", "promise"],
          ["'No, I won't pay.'", "refuse"], ["'You should use laminated glass.'", "recommend"],
          ["'Shall I carry your bag?'", "offer"]],
          explain: "Cümleyi anlamına uygun aktarma fiiliyle eşleştir." },
        { type: "listen", text: "He asked whether we could deliver earlier.",
          tr: "Daha erken teslim edip edemeyeceğimizi sordu." },
        { type: "fill", q: "'I'm tired.' → Ayşe said that she ___ tired.",
          answers: ["was"],
          explain: "am → was." },
        { type: "mcq", q: "We recommend that the gaskets ___ every two years.",
          options: ["are replacing", "replacing", "to be replaced", "be replaced"], answer: 3,
          explain: "recommend that + özne + (should) + yalın fiil → (should) be replaced." }
      ]
    },
    // ───────────────────────── WEEK 5 ─────────────────────────
    {
      id: "grammar-09",
      title: "Third & Mixed Conditionals, wish / if only / I'd rather",
      level: "B2+",
      week: 5,
      intro: {
        tr: "Third conditional geçmişte gerçekleşmemiş bir durumu ve hayali sonucunu anlatır: If + had V3, would have V3. Mixed conditional geçmişteki bir koşulu şimdiki sonuçla (If I had studied harder, I would be a doctor now) ya da şimdiki bir durumu geçmiş sonuçla birleştirir. 'wish / if only' pişmanlık ve özlem bildirir: şimdi için past simple, geçmiş için past perfect, başkasının davranışından şikayet için would. 'I'd rather' tercih bildirir.",
        points: [
          "Third: If we had checked the packaging, the glass wouldn't have broken.",
          "Mixed (geçmiş → şimdi): If I had taken that job, I would be living in Dubai now.",
          "wish + past simple = şimdiki durum: I wish I had more time.",
          "wish + past perfect = geçmiş pişmanlık: I wish I hadn't said that.",
          "wish + would = şikayet: I wish you would stop interrupting.",
          "I'd rather + yalın fiil (kendim); I'd rather + özne + past simple (başkası)."
        ],
        examples: [
          { en: "If we had packed the panes better, they wouldn't have cracked.", tr: "Camları daha iyi paketleseydik çatlamazlardı." },
          { en: "If I had learned German at school, I would speak it now.", tr: "Okulda Almanca öğrenseydim şimdi konuşuyor olurdum." },
          { en: "I wish I had more free time.", tr: "Keşke daha fazla boş vaktim olsa." },
          { en: "If only we had ordered the glass earlier!", tr: "Keşke camı daha erken sipariş etseydik!" },
          { en: "I'd rather you didn't tell anyone yet.", tr: "Henüz kimseye söylemesen daha iyi olur." }
        ]
      },
      cards: [
        { en: "If I had known, ...", tr: "Bilseydim, ...", ex: "If I had known, I would have called you." },
        { en: "would have + V3", tr: "...rdı (geçmişte olmayan sonuç)", ex: "We would have delivered on time." },
        { en: "I wish I had ...", tr: "Keşke ... olsa / olsaydı", ex: "I wish I had studied engineering." },
        { en: "If only ...", tr: "Keşke ...", ex: "If only the weather were better!" },
        { en: "I'd rather ...", tr: "... tercih ederim", ex: "I'd rather stay in tonight." },
        { en: "I'd rather you ...", tr: "...mesini tercih ederim", ex: "I'd rather you sent it by email." }
      ],
      exercises: [
        { type: "mcq", q: "If we had checked the packaging, the glass ___.",
          options: ["wouldn't break", "won't break", "wouldn't have broken", "hadn't broken"], answer: 2,
          explain: "Third conditional: If + had V3, would have + V3." },
        { type: "fill", q: "If I ___ (know) you were in town, I would have called you.",
          answers: ["had known", "'d known"],
          explain: "Third conditional: if cümleciğinde past perfect." },
        { type: "mcq", q: "If I had taken that job in Dubai, I ___ there now.",
          options: ["would be living", "would have lived", "will live", "had lived"], answer: 0,
          explain: "Mixed: geçmiş koşul + şimdiki sonuç (now) → would be (living)." },
        { type: "mcq", q: "I wish I ___ more time to travel. I'm always so busy.",
          options: ["have", "had", "would have", "had had"], answer: 1,
          explain: "Şimdiki durum için wish + past simple." },
        { type: "fill", q: "I wish I ___ (not / say) that to her yesterday.",
          answers: ["hadn't said", "had not said"],
          explain: "Geçmiş pişmanlık → wish + past perfect." },
        { type: "mcq", q: "I wish you ___ interrupting me during meetings. It's really annoying.",
          options: ["would stop", "stop", "had stopped", "will stop"], answer: 0,
          explain: "Başkasının davranışından şikayet → wish + would." },
        { type: "mcq", q: "I'd rather ___ by train than by plane.",
          options: ["travel", "to travel", "travelling", "travelled"], answer: 0,
          explain: "I'd rather + yalın fiil." },
        { type: "mcq", q: "I'd rather you ___ the price to anyone yet.",
          options: ["don't mention", "won't mention", "not mention", "didn't mention"], answer: 3,
          explain: "I'd rather + başka özne + past simple." },
        { type: "order", answer: "If only we had ordered the glass earlier.",
          tr: "Keşke camı daha erken sipariş etseydik.",
          explain: "If only + past perfect = geçmişe dair pişmanlık." },
        { type: "match", pairs: [["I wish I knew.", "Keşke bilsem (şimdi)."], ["I wish I had known.", "Keşke bilseydim (geçmiş)."],
          ["I wish you would listen.", "Keşke dinlesen (şikayet)."], ["I'd rather stay.", "Kalmayı tercih ederim."],
          ["I'd rather you stayed.", "Kalmanı tercih ederim."]],
          explain: "wish ve I'd rather kalıplarının anlam farkları." },
        { type: "listen", text: "If you had asked me, I would have helped you.",
          tr: "Bana sorsaydın sana yardım ederdim." },
        { type: "fill", q: "If the vessel ___ (not / be) delayed, the windows would have been installed last week.",
          answers: ["hadn't been", "had not been"],
          explain: "Third conditional: If + had (not) + V3." },
        { type: "mcq", q: "If I spoke better German, I ___ the job in Hamburg last year.",
          options: ["would get", "would have got", "will get", "had got"], answer: 1,
          explain: "Mixed: şimdiki durum (Almancam iyi değil) + geçmiş sonuç → would have + V3." }
      ]
    },
    {
      id: "grammar-10",
      title: "Modals of Deduction & Past Modals",
      level: "B2+",
      week: 5,
      intro: {
        tr: "Tahmin ve çıkarım yaparken must (kesin öyle), can't (kesin değil), might / may / could (belki) kullanılır. Geçmişe dair çıkarım için modal + have + V3: must have left, can't have seen, might have forgotten. Geçmişteki hata veya pişmanlık için should have / shouldn't have; yapılmış ama gereksiz olan iş için needn't have done kullanılır.",
        points: [
          "Şimdi: must be (eminim öyle), can't be (eminim değil), might be (belki).",
          "Geçmiş: must have done / can't have done / might have done.",
          "should have done = yapmalıydın ama yapmadın (eleştiri, pişmanlık).",
          "needn't have done = yaptın ama gerek yokmuş.",
          "Çıkarımda 'mustn't' kullanılmaz; olumsuz kesinlik için can't / couldn't."
        ],
        examples: [
          { en: "The pane cracked. The frame must have been too tight.", tr: "Cam çatladı. Çerçeve çok sıkı olmuş olmalı." },
          { en: "He can't have seen my email — he was on holiday.", tr: "E-postamı görmüş olamaz, tatildeydi." },
          { en: "You should have told me it was your birthday!", tr: "Doğum günün olduğunu bana söylemeliydin!" },
          { en: "We needn't have worried; the inspection went perfectly.", tr: "Endişelenmemize gerek yokmuş, denetim mükemmel geçti." },
          { en: "She might have missed the bus.", tr: "Otobüsü kaçırmış olabilir." }
        ]
      },
      cards: [
        { en: "must have + V3", tr: "...mış olmalı", ex: "The parcel must have been lost in transit." },
        { en: "can't have + V3", tr: "...mış olamaz", ex: "They can't have received the drawings yet." },
        { en: "might have + V3", tr: "...mış olabilir", ex: "I might have left my phone in the taxi." },
        { en: "should have + V3", tr: "...malıydı", ex: "We should have checked the dimensions." },
        { en: "needn't have + V3", tr: "...mesine gerek yokmuş", ex: "You needn't have brought a gift!" },
        { en: "could have + V3", tr: "...ebilirdi", ex: "It could have been much worse." }
      ],
      exercises: [
        { type: "mcq", q: "All the lights are off. They ___ be at home.",
          options: ["mustn't", "shouldn't", "can't", "needn't"], answer: 2,
          explain: "Olumsuz kesin çıkarım → can't (mustn't çıkarım için kullanılmaz)." },
        { type: "mcq", q: "The pane cracked during installation. The frame ___ been too tight.",
          options: ["must have", "can't have", "should", "needn't have"], answer: 0,
          explain: "Geçmişe dair güçlü çıkarım → must have + V3." },
        { type: "fill", q: "He ___ (can't / see) the email — he was on holiday with no internet.",
          answers: ["can't have seen", "cannot have seen", "couldn't have seen", "could not have seen"],
          explain: "Geçmişte olmuş olamaz → can't / couldn't have + V3." },
        { type: "mcq", q: "You ___ told me it was your birthday! I would have bought you a present.",
          options: ["should have", "must have", "can't have", "might"], answer: 0,
          explain: "Eleştiri / pişmanlık → should have + V3." },
        { type: "mcq", q: "We ___ worried about the inspection — everything was fine.",
          options: ["needn't have", "mustn't have", "can't have", "didn't have"], answer: 0,
          explain: "Endişelendik ama gereksizmiş → needn't have + V3." },
        { type: "fill", q: "I'm not sure where Mehmet is. He ___ (might / miss) the bus.",
          answers: ["might have missed", "may have missed", "could have missed"],
          explain: "Geçmişe dair olasılık → might have + V3." },
        { type: "mcq", q: "She speaks perfect Turkish. She ___ lived in Turkey for years.",
          options: ["must have", "should have", "can't have", "needn't have"], answer: 0,
          explain: "Kanıta dayalı güçlü çıkarım → must have." },
        { type: "order", answer: "The documents must have been sent to the wrong address.",
          tr: "Belgeler yanlış adrese gönderilmiş olmalı.",
          explain: "Edilgen geçmiş çıkarım: must have been + V3." },
        { type: "match", pairs: [["must have done", "kesin yapmıştır"], ["can't have done", "yapmış olamaz"],
          ["might have done", "yapmış olabilir"], ["should have done", "yapmalıydı (ama yapmadı)"],
          ["needn't have done", "gerek yokmuş (ama yaptı)"]],
          explain: "Geçmiş modalların anlamları." },
        { type: "listen", text: "You should have called me earlier.",
          tr: "Beni daha erken aramalıydın." },
        { type: "mcq", q: "The customer hasn't replied yet. He ___ our quotation.",
          options: ["can't read", "shouldn't have read", "mustn't have read", "might not have read"], answer: 3,
          explain: "Belki okumamıştır → might not have + V3." },
        { type: "fill", q: "We ___ (should / pack) the panes more carefully; three of them arrived broken.",
          answers: ["should have packed"],
          explain: "Geçmişteki hata → should have + V3." },
        { type: "mcq", q: "That ___ be Jan at the door — he said he'd come around six.",
          options: ["must", "can't", "needn't", "mustn't"], answer: 0,
          explain: "Güçlü olumlu çıkarım (şimdi) → must be." }
      ]
    },
    // ───────────────────────── WEEK 6 ─────────────────────────
    {
      id: "grammar-11",
      title: "Causative: have / get something done",
      level: "B2+",
      week: 6,
      intro: {
        tr: "Causative yapı, bir işi kendimiz yapmak yerine başkasına yaptırdığımızı anlatır: have + nesne + V3 (I had my car repaired), get + nesne + V3 (daha gündelik). Bir kişiye iş yaptırmak için: have someone do (yalın fiil), get someone to do (ikna ederek). Başımıza gelen kötü olaylar için de kullanılır: I had my wallet stolen. 'need + -ing' edilgen anlam taşır: The gasket needs replacing = needs to be replaced.",
        points: [
          "have/get + nesne + V3: We had the glass tested by an independent lab.",
          "have + kişi + yalın fiil: I'll have my assistant send you the invoice.",
          "get + kişi + to + fiil: I got my brother to help me.",
          "Kötü olay: She had her phone stolen.",
          "need + -ing = need to be + V3: The windows need cleaning."
        ],
        examples: [
          { en: "We had the glass tested by an independent laboratory.", tr: "Camı bağımsız bir laboratuvarda test ettirdik." },
          { en: "I'm going to get my hair cut on Saturday.", tr: "Cumartesi saçımı kestireceğim." },
          { en: "I'll have my colleague send you the certificates.", tr: "Sertifikaları size meslektaşıma gönderteceğim." },
          { en: "The rubber seals need replacing.", tr: "Kauçuk contaların değiştirilmesi gerekiyor." },
          { en: "He had his wallet stolen in Barcelona.", tr: "Barselona'da cüzdanını çaldırdı." }
        ]
      },
      cards: [
        { en: "have something done", tr: "bir şeyi yaptırmak", ex: "We had the frames painted." },
        { en: "get something done", tr: "bir şeyi yaptırmak (gündelik)", ex: "I need to get my passport renewed." },
        { en: "have someone do", tr: "birine yaptırmak", ex: "I'll have our engineer call you." },
        { en: "get someone to do", tr: "birini ikna edip yaptırmak", ex: "Can you get the driver to wait?" },
        { en: "need doing", tr: "yapılması gerekmek", ex: "The car needs washing." },
        { en: "have something stolen", tr: "bir şeyini çaldırmak", ex: "I had my bike stolen last year." }
      ],
      exercises: [
        { type: "mcq", q: "My hair is too long. I'm going to ___ tomorrow.",
          options: ["have cut my hair", "have my hair cutting", "have my hair cut", "have to my hair cut"], answer: 2,
          explain: "have + nesne + V3: have my hair cut." },
        { type: "mcq", q: "We had the glass ___ by an independent laboratory.",
          options: ["test", "tested", "testing", "to test"], answer: 1,
          explain: "have + nesne + V3 (camı test ettirdik)." },
        { type: "fill", q: "We'll get the drawings ___ (check) by our engineer before production.",
          answers: ["checked"],
          explain: "get + nesne + V3." },
        { type: "mcq", q: "I'll have my assistant ___ you the invoice.",
          options: ["send", "sent", "to send", "sending"], answer: 0,
          explain: "have + kişi + yalın fiil." },
        { type: "mcq", q: "I finally got my brother ___ me with the move.",
          options: ["to help", "help", "helped", "helping"], answer: 0,
          explain: "get + kişi + to + fiil." },
        { type: "fill", q: "She had her phone ___ (steal) on the metro last week.",
          answers: ["stolen"],
          explain: "Başa gelen kötü olay: have + nesne + V3." },
        { type: "mcq", q: "The rubber seals are old. They need ___.",
          options: ["replace", "replaced", "to replace", "replacing"], answer: 3,
          explain: "need + -ing = edilgen anlam (değiştirilmeleri gerekiyor)." },
        { type: "order", answer: "We are having the windows installed next month.",
          tr: "Pencereleri gelecek ay taktırıyoruz.",
          explain: "Planlanmış causative: be having + nesne + V3." },
        { type: "fill", q: "The bridge windows need ___ (clean) before the inspection.",
          answers: ["cleaning", "to be cleaned"],
          explain: "need + -ing veya need to be + V3." },
        { type: "match", pairs: [["have something done", "bir şeyi yaptırmak"], ["get someone to do", "birini ikna edip yaptırmak"],
          ["have someone do", "birine yaptırmak"], ["need doing", "yapılması gerekmek"],
          ["have something stolen", "bir şeyini çaldırmak"]],
          explain: "Causative kalıpları ve anlamları." },
        { type: "listen", text: "Where do you usually get your hair cut?",
          tr: "Saçını genelde nerede kestirirsin?" },
        { type: "mcq", q: "Which sentence means the customer did NOT do the work himself?",
          options: ["The customer repaired the frame.", "The customer had the frame repaired.",
            "The customer was repairing the frame.", "The customer has repaired the frame."], answer: 1,
          explain: "had the frame repaired = çerçeveyi tamir ettirdi (başkası yaptı)." },
        { type: "fill", q: "Can you get the forwarder ___ (confirm) the delivery date?",
          answers: ["to confirm"],
          explain: "get + kişi + to + fiil." }
      ]
    },
    {
      id: "grammar-12",
      title: "Participle Clauses",
      level: "B2+",
      week: 6,
      intro: {
        tr: "Participle clause, iki cümleyi kısaltarak daha akıcı ve resmi bir anlatım sağlar. Present participle (-ing) aktif ve eşzamanlı eylemi, 'having + V3' önce tamamlanmış eylemi, past participle (V3) edilgen anlamı verir. Ana cümlenin öznesi, participle'ın da öznesi olmalıdır; aksi halde 'dangling participle' denen bir hata oluşur.",
        points: [
          "-ing (eşzamanlı/aktif): Walking along the coast, we saw dolphins.",
          "Having + V3 (önce olan): Having checked the drawings, we sent the quotation.",
          "V3 (edilgen): Made of laminated glass, the window is very safe.",
          "Relative clause kısaltma: The panes (which are) stored in the warehouse are ready.",
          "Olumsuz: Not knowing the address, I called him.",
          "Özne aynı olmalı: 'Arriving at the airport, my phone died' yanlıştır."
        ],
        examples: [
          { en: "Having checked the drawings, we sent the quotation.", tr: "Çizimleri kontrol ettikten sonra teklifi gönderdik." },
          { en: "Made of laminated glass, the window is very safe.", tr: "Lamine camdan yapıldığı için pencere çok güvenlidir." },
          { en: "Walking along the beach, we found a lovely fish restaurant.", tr: "Sahilde yürürken güzel bir balık restoranı bulduk." },
          { en: "Anyone wishing to join the factory tour should contact us.", tr: "Fabrika turuna katılmak isteyen herkes bizimle iletişime geçmeli." },
          { en: "Not knowing anyone at the party, I stayed close to the host.", tr: "Partide kimseyi tanımadığım için ev sahibinin yanından ayrılmadım." }
        ]
      },
      cards: [
        { en: "Having finished ...", tr: "... bitirdikten sonra", ex: "Having finished the tests, we packed the glass." },
        { en: "Made of ...", tr: "...dan yapılmış", ex: "Made of tempered glass, the portlight is very strong." },
        { en: "Not knowing ...", tr: "... bilmediği için", ex: "Not knowing the way, we took a taxi." },
        { en: "Anyone wishing to ...", tr: "... isteyen herkes", ex: "Anyone wishing to attend should register." },
        { en: "Attached please find ...", tr: "Ekte ... bulabilirsiniz", ex: "Attached please find the test report." },
        { en: "Based on ...", tr: "...ya dayanarak", ex: "Based on your drawings, we have prepared an offer." }
      ],
      exercises: [
        { type: "mcq", q: "___ the drawings, our engineer sent the quotation.",
          options: ["Having checked", "Checked", "Having been checked", "To check"], answer: 0,
          explain: "Önce kontrol etti, sonra gönderdi → Having + V3 (aktif)." },
        { type: "mcq", q: "___ of nineteen-millimetre tempered glass, these windows can withstand heavy seas.",
          options: ["Making", "Having made", "Made", "To make"], answer: 2,
          explain: "Pencereler yapılmıştır (edilgen) → V3: Made of ..." },
        { type: "fill", q: "___ (not / know) anyone at the party, I stayed close to the host.",
          answers: ["Not knowing"],
          explain: "Olumsuz participle: Not + -ing." },
        { type: "mcq", q: "The panes ___ in the warehouse are ready for shipment.",
          options: ["stored", "storing", "having stored", "to store"], answer: 0,
          explain: "which are stored → stored (edilgen kısaltma)." },
        { type: "mcq", q: "___ along the beach, we found a nice little fish restaurant.",
          options: ["Walked", "To walk", "Been walking", "Walking"], answer: 3,
          explain: "Eşzamanlı aktif eylem → -ing (yürürken)." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["Arriving at the airport, my phone died.", "Arrived at the airport, I realised my phone was dead.",
            "Arriving at the airport, I realised my phone was dead.", "Having arrive at the airport, I realised my phone was dead."], answer: 2,
          explain: "Participle'ın öznesi ana cümlenin öznesiyle aynı olmalı (I arrived)." },
        { type: "order", answer: "Having signed the contract, we started production immediately.",
          tr: "Sözleşmeyi imzaladıktan sonra hemen üretime başladık.",
          explain: "Having + V3 önce tamamlanan eylemi gösterir." },
        { type: "fill", q: "___ (test) to ISO 614, all our toughened panes meet SOLAS requirements.",
          answers: ["Tested", "Having been tested"],
          explain: "Camlar test edilmiştir (edilgen) → Tested / Having been tested." },
        { type: "match", pairs: [["Having finished", "bitirdikten sonra"], ["Made in Turkey", "Türkiye'de üretilmiş"],
          ["Not wanting to be late", "geç kalmak istemediği için"], ["Walking home", "eve yürürken"],
          ["Having been delayed", "geciktirilmiş olduğu için"]],
          explain: "Participle clause'ların Türkçe karşılıkları." },
        { type: "listen", text: "Having finished work, I went straight home.",
          tr: "İşi bitirdikten sonra doğruca eve gittim." },
        { type: "mcq", q: "Anyone ___ to attend the factory visit should contact Ms Demir.",
          options: ["wishing", "wished", "having wished", "to wish"], answer: 0,
          explain: "who wishes → wishing (aktif kısaltma)." },
        { type: "fill", q: "The woman ___ (sit) next to me on the plane was a ship captain.",
          answers: ["sitting"],
          explain: "who was sitting → sitting." },
        { type: "mcq", q: "___ by the delay, the customer asked for compensation.",
          options: ["Annoying", "Annoyed", "Having annoyed", "To annoy"], answer: 1,
          explain: "Müşteri rahatsız edilmiş (edilgen) → Annoyed." }
      ]
    },
    // ───────────────────────── WEEK 7 ─────────────────────────
    {
      id: "grammar-13",
      title: "Advanced Passive: It is said that / is believed to",
      level: "C1",
      week: 7,
      intro: {
        tr: "Reporting passive, bir bilgiyi kaynağını belirtmeden ve mesafeli bir dille aktarmanın resmi yoludur. İki kalıp vardır: 'It + is said / believed / reported / expected + that ...' ve 'Özne + is said / believed / thought + to do'. Geçmiş olay için 'to have + V3', şu anda süren olay için 'to be + -ing' kullanılır. Haberlerde, raporlarda ve resmi yazışmalarda sık görülür.",
        points: [
          "It is said that + cümle: It is expected that the rules will change.",
          "Özne + is said to + fiil (şimdi/genel): She is said to speak five languages.",
          "Özne + is said to have + V3 (geçmiş): The company is said to have opened a plant.",
          "Özne + is believed to be + -ing (süren): He is believed to be working on a project.",
          "There is said to be ...: There is said to be a great view from the tower.",
          "Fiiller: say, believe, think, report, expect, know, consider, rumour."
        ],
        examples: [
          { en: "It is expected that the new SOLAS amendments will come into force next year.", tr: "Yeni SOLAS değişikliklerinin gelecek yıl yürürlüğe girmesi bekleniyor." },
          { en: "The damage is thought to have been caused by poor packaging.", tr: "Hasarın kötü paketlemeden kaynaklandığı düşünülüyor." },
          { en: "The new restaurant is said to be excellent.", tr: "Yeni restoranın mükemmel olduğu söyleniyor." },
          { en: "The vessel is reported to have been delayed by a storm.", tr: "Geminin fırtına nedeniyle geciktiği bildiriliyor." }
        ]
      },
      cards: [
        { en: "It is expected that ...", tr: "...mesi bekleniyor", ex: "It is expected that prices will rise." },
        { en: "is said to be", tr: "... olduğu söyleniyor", ex: "The old town is said to be beautiful." },
        { en: "is thought to have + V3", tr: "...dığı düşünülüyor (geçmiş)", ex: "The crack is thought to have started at the edge." },
        { en: "is believed to be doing", tr: "...makta olduğuna inanılıyor", ex: "They are believed to be expanding into Asia." },
        { en: "is reported to", tr: "... olduğu bildiriliyor", ex: "The ship is reported to be in Gibraltar." },
        { en: "There is said to be", tr: "... olduğu söyleniyor", ex: "There is said to be a shortage of float glass." }
      ],
      exercises: [
        { type: "mcq", q: "It ___ that the new SOLAS amendments will come into force next year.",
          options: ["is expected", "expects", "is expecting", "has expected"], answer: 0,
          explain: "It + is + V3 + that ... (reporting passive)." },
        { type: "mcq", q: "The company is said ___ a new plant in Poland last year.",
          options: ["to have opened", "to open", "opening", "to be opened"], answer: 0,
          explain: "Geçmiş olay (last year) → to have + V3." },
        { type: "fill", q: "The damage is thought ___ (cause) by poor packaging.",
          answers: ["to have been caused"],
          explain: "Geçmiş + edilgen → to have been + V3." },
        { type: "mcq", q: "He is believed ___ on a new project at the moment.",
          options: ["to work", "working", "to have worked", "to be working"], answer: 3,
          explain: "Şu anda süren eylem → to be + -ing." },
        { type: "order", answer: "It is widely believed that laminated glass is safer.",
          tr: "Lamine camın daha güvenli olduğuna yaygın olarak inanılır.",
          explain: "It + is + (zarf) + V3 + that-cümlesi." },
        { type: "mcq", q: "Transform: 'People say that she speaks five languages.' →",
          options: ["She is said to speak five languages.", "She is said speaking five languages.",
            "She says to speak five languages.", "It is said her to speak five languages."], answer: 0,
          explain: "Özne + is said + to + yalın fiil." },
        { type: "fill", q: "There ___ to be a great view from the top of Galata Tower.",
          answers: ["is said", "is supposed", "is believed", "is thought"], hint: "say, edilgen",
          explain: "There is said to be ... = ... olduğu söyleniyor." },
        { type: "mcq", q: "The vessel ___ to have been delayed by a storm in the Bay of Biscay.",
          options: ["reports", "is reported", "has reported", "reported"], answer: 1,
          explain: "Özne + is reported + to have been + V3." },
        { type: "match", pairs: [["It is said that ...", "... olduğu söyleniyor"], ["is thought to have done", "yaptığı düşünülüyor (geçmiş)"],
          ["is believed to be doing", "yapmakta olduğuna inanılıyor"], ["is expected to", "...mesi bekleniyor"],
          ["is known to", "... olduğu biliniyor"]],
          explain: "Reporting passive kalıplarının anlamları." },
        { type: "listen", text: "The new restaurant is said to be excellent.",
          tr: "Yeni restoranın mükemmel olduğu söyleniyor." },
        { type: "mcq", q: "Which is the most formal way to report the rumour?",
          options: ["People say the factory will close.", "They say the factory will close.",
            "The factory is rumoured to be closing.", "I heard the factory will close."], answer: 2,
          explain: "Reporting passive (is rumoured to) en resmi ve mesafeli seçenektir." },
        { type: "fill", q: "It ___ (report) that two windows were damaged during unloading.",
          answers: ["has been reported", "was reported", "is reported"],
          explain: "It + be + reported + that ..." },
        { type: "mcq", q: "The fire is believed ___ in the engine room.",
          options: ["to start", "starting", "to have started", "to be started"], answer: 2,
          explain: "Yangın geçmişte başladı → to have + V3." }
      ]
    },
    {
      id: "grammar-14",
      title: "Inversion for Emphasis",
      level: "C1",
      week: 7,
      intro: {
        tr: "Inversion (devrik yapı), olumsuz veya kısıtlayıcı bir ifade cümlenin başına geldiğinde yardımcı fiilin özneden önce gelmesidir: Never have I seen ... Vurgu katar ve resmi yazışmada sık kullanılır. Yaygın başlangıçlar: Not only, Never, Rarely, Seldom, Little, Under no circumstances, Hardly/Scarcely ... when, No sooner ... than, Only then / Only after. Koşul cümlelerinde 'if' düşürülerek de kullanılır: Should you need ..., Had we known ..., Were it not for ...",
        points: [
          "Yapı: olumsuz ifade + yardımcı fiil + özne + fiil (Rarely do we receive ...).",
          "Yardımcı fiil yoksa do/does/did eklenir: Only then did I realise ...",
          "Hardly/Scarcely had ... when; No sooner had ... than.",
          "Resmi koşul: Should you need help = If you need help.",
          "Had we known = If we had known; Were it not for = If it weren't for.",
          "Under no circumstances should/must/may ... (kesin yasak)."
        ],
        examples: [
          { en: "Should you need any further information, please do not hesitate to contact us.", tr: "Daha fazla bilgiye ihtiyacınız olursa lütfen bizimle iletişime geçmekten çekinmeyin." },
          { en: "Not only was the delivery late, but some panes were also cracked.", tr: "Teslimat sadece gecikmekle kalmadı, bazı camlar da çatlaktı." },
          { en: "Never have I seen such a beautiful sunset.", tr: "Hiç bu kadar güzel bir gün batımı görmedim." },
          { en: "Had we known about the strike, we would have shipped earlier.", tr: "Grevden haberimiz olsaydı daha erken sevk ederdik." },
          { en: "Under no circumstances should the protective film be removed before installation.", tr: "Koruyucu film montajdan önce hiçbir koşulda çıkarılmamalıdır." }
        ]
      },
      cards: [
        { en: "Should you need ...", tr: "... ihtiyacınız olursa", ex: "Should you need samples, please let us know." },
        { en: "Not only ... but also", tr: "sadece ... değil, aynı zamanda", ex: "Not only is it stronger, but it is also lighter." },
        { en: "Under no circumstances", tr: "hiçbir koşulda", ex: "Under no circumstances should the glass be cut after tempering." },
        { en: "Had I known ...", tr: "Bilseydim ...", ex: "Had I known, I would have come earlier." },
        { en: "No sooner had ... than", tr: "... yapar yapmaz", ex: "No sooner had we landed than it started snowing." },
        { en: "Only then did ...", tr: "ancak o zaman ...", ex: "Only then did we understand the problem." }
      ],
      exercises: [
        { type: "mcq", q: "Not only ___ late, but some panes were also cracked.",
          options: ["was the delivery", "the delivery was", "did the delivery be", "the delivery did"], answer: 0,
          explain: "Not only başta → devrik: was the delivery." },
        { type: "mcq", q: "___ you need any further information, please do not hesitate to contact us.",
          options: ["Should", "Would", "If should", "Had"], answer: 0,
          explain: "Should you need ... = If you need ... (resmi)." },
        { type: "fill", q: "Under no circumstances ___ the protective film be removed before installation.",
          answers: ["should", "must", "may"],
          explain: "Under no circumstances + modal + özne + fiil." },
        { type: "mcq", q: "Hardly had we sat down ___ the fire alarm went off.",
          options: ["than", "then", "that", "when"], answer: 3,
          explain: "Hardly ... when (No sooner ... than ile karıştırma)." },
        { type: "mcq", q: "No sooner had I arrived home ___ it started to rain.",
          options: ["when", "then", "than", "as"], answer: 2,
          explain: "No sooner ... than." },
        { type: "fill", q: "___ we known about the strike, we would have shipped earlier.",
          answers: ["Had"],
          explain: "Had we known = If we had known (devrik third conditional)." },
        { type: "order", answer: "Never have I seen such a beautiful sunset.",
          tr: "Hiç bu kadar güzel bir gün batımı görmedim.",
          explain: "Never + yardımcı fiil (have) + özne + V3." },
        { type: "mcq", q: "Rarely ___ such high-quality laminated glass at this price.",
          options: ["you find", "do you find", "you do find", "find you"], answer: 1,
          explain: "Rarely başta → do + özne + fiil." },
        { type: "match", pairs: [["Should you need help,", "If you need help,"], ["Had I known,", "If I had known,"],
          ["Were it not for you,", "If it weren't for you,"], ["Not until later did I see it.", "I only saw it later."],
          ["Little did she know.", "She had no idea."]],
          explain: "Devrik yapı ve normal karşılıkları." },
        { type: "listen", text: "Only then did I realise my mistake.",
          tr: "Hatamı ancak o zaman fark ettim." },
        { type: "mcq", q: "Only after the inspection ___ the windows to the shipyard.",
          options: ["did we send", "we sent", "we did send", "sent we"], answer: 0,
          explain: "Only after ... → ana cümlede devrik: did we send." },
        { type: "fill", q: "Little ___ I know that this meeting would change my career.",
          answers: ["did"],
          explain: "Little + did + özne + yalın fiil." },
        { type: "mcq", q: "Which sentence is correct?",
          options: ["Seldom we receive complaints about our portlights.", "Seldom receive we complaints about our portlights.",
            "Seldom do we received complaints about our portlights.", "Seldom do we receive complaints about our portlights."], answer: 3,
          explain: "Seldom + do + özne + yalın fiil." }
      ]
    },
    // ───────────────────────── WEEK 8 ─────────────────────────
    {
      id: "grammar-15",
      title: "Cleft Sentences & Emphasis",
      level: "C1",
      week: 8,
      intro: {
        tr: "Cleft sentence, bir bilgiyi öne çıkarmak için cümleyi ikiye böler. 'It is/was ... that/who ...' kalıbı belirli bir öğeyi vurgular (It was the gasket that failed, not the glass). 'What ... is/was ...' kalıbı ana fikri sona taşır (What we need is a faster delivery). 'All I want is ...', 'The reason why ... is that ...' da yaygındır. Olumlu cümlede vurgu için do/does/did + yalın fiil kullanılır (I do understand your concern).",
        points: [
          "It + be + vurgulanan öğe + that/who: It was Ayşe who found the mistake.",
          "What + özne + fiil + be + ...: What surprised me was the price.",
          "All I want / need is ...: All we need is your signature.",
          "The reason why ... is that ...; The thing that ... is ...",
          "Vurgulu do: We did send the invoice — please check your spam folder."
        ],
        examples: [
          { en: "It was the gasket that failed, not the glass.", tr: "Arızalanan cam değil, contaydı." },
          { en: "What we need is a clear delivery schedule.", tr: "İhtiyacımız olan şey net bir teslimat takvimi." },
          { en: "What I love about Istanbul is the food.", tr: "İstanbul'da en sevdiğim şey yemekleri." },
          { en: "I do understand your concern, and we are looking into it.", tr: "Endişenizi gerçekten anlıyorum ve konuyu inceliyoruz." },
          { en: "All I want to do this weekend is relax.", tr: "Bu hafta sonu tek istediğim dinlenmek." }
        ]
      },
      cards: [
        { en: "What we need is ...", tr: "İhtiyacımız olan şey ...", ex: "What we need is the final drawing." },
        { en: "It was ... that ...", tr: "... olan ...ydı", ex: "It was the frame that caused the leak." },
        { en: "All I want is ...", tr: "Tek istediğim ...", ex: "All I want is a quiet weekend." },
        { en: "The reason why ... is that ...", tr: "...nın sebebi şu ki ...", ex: "The reason why we're late is that the port was closed." },
        { en: "I do apologise", tr: "Gerçekten özür dilerim", ex: "I do apologise for the delay." },
        { en: "What surprised me was ...", tr: "Beni şaşırtan şey ...", ex: "What surprised me was how friendly everyone was." }
      ],
      exercises: [
        { type: "mcq", q: "It was the gasket ___ failed, not the glass itself.",
          options: ["what", "that", "where", "when"], answer: 1,
          explain: "It was + öğe + that ... (cleft)." },
        { type: "mcq", q: "___ we need is a clear delivery schedule.",
          options: ["That", "Which", "What", "It"], answer: 2,
          explain: "What-cleft: What we need is ..." },
        { type: "fill", q: "I ___ understand your concern, and we will investigate the issue immediately.",
          answers: ["do"],
          explain: "Vurgu için do + yalın fiil." },
        { type: "mcq", q: "It was only last week ___ I found out she was married.",
          options: ["that", "what", "which", "where"], answer: 0,
          explain: "It was + zaman ifadesi + that ..." },
        { type: "fill", q: "What I love about Istanbul ___ the food.",
          answers: ["is"],
          explain: "What-cleft'te fiil genellikle tekil: is." },
        { type: "order", answer: "What surprised me most was the quality of the glass.",
          tr: "Beni en çok şaşırtan camın kalitesiydi.",
          explain: "What + cümlecik + was + vurgulanan bilgi." },
        { type: "mcq", q: "She ___ call you yesterday — you just didn't answer!",
          options: ["did", "does", "was", "has"], answer: 0,
          explain: "Geçmişte vurgu: did + yalın fiil." },
        { type: "mcq", q: "All I want to do this weekend ___ relax.",
          options: ["is", "are", "being", "has"], answer: 0,
          explain: "All I want to do is (to) relax." },
        { type: "match", pairs: [["What we need is ...", "İhtiyacımız olan şey ..."], ["It was John who ...", "... yapan John'du"],
          ["The reason why ... is that ...", "...nın sebebi şu ki ..."], ["All I want is ...", "Tek istediğim ..."],
          ["I do apologise.", "Gerçekten özür dilerim."]],
          explain: "Vurgu kalıplarının anlamları." },
        { type: "listen", text: "What we need is a faster delivery.",
          tr: "İhtiyacımız olan daha hızlı bir teslimat." },
        { type: "mcq", q: "Make it emphatic: 'The delay caused the problem.' →",
          options: ["It was the delay that caused the problem.", "What caused the problem it was the delay.",
            "The delay it was caused the problem.", "It was the delay what caused the problem."], answer: 0,
          explain: "It was + öğe + that + cümlenin geri kalanı." },
        { type: "fill", q: "The reason why we chose your company ___ that your glass has DNV approval.",
          answers: ["is", "was"],
          explain: "The reason why ... is that ..." },
        { type: "mcq", q: "Which is the most emphatic apology to a customer?",
          options: ["We are sorry.", "We apologise, maybe.", "Sorry for that.", "We do apologise for the inconvenience."], answer: 3,
          explain: "do apologise: vurgulu ve resmi özür." }
      ]
    },
    {
      id: "grammar-16",
      title: "Hedging & Formal Grammar for Business Writing",
      level: "C1",
      week: 8,
      intro: {
        tr: "C1 seviyesinde iş yazışmasında kesin ve sert ifadeler yerine temkinli (hedging) dil kullanmak profesyonel ve diplomatik görünür: It would appear that ..., The damage seems to have been caused by ..., tend to, may / might, to some extent. Resmi öneri ve taleplerde subjunctive kullanılır: We recommend that the pane be replaced (yalın fiil; -s yok). Nominalisation, fiilleri isme çevirerek yazıyı daha resmi yapar: We will deliver → Delivery will take place.",
        points: [
          "It would appear / It seems that ...; seem / appear to have + V3.",
          "tend to: Customers tend to prefer laminated glass.",
          "Subjunctive: recommend / insist / request / it is essential that + özne + yalın fiil (be, have, replace).",
          "Nominalisation: decide → decision, deliver → delivery, approve → approval.",
          "Yumuşatıcılar: slightly, somewhat, relatively, in most cases, to some extent.",
          "Günlük dilde de: I'm not entirely sure ..., I would have thought ..."
        ],
        examples: [
          { en: "It would appear that the cracks were caused by incorrect installation.", tr: "Çatlakların hatalı montajdan kaynaklandığı anlaşılıyor." },
          { en: "We recommend that the damaged pane be replaced as soon as possible.", tr: "Hasarlı camın en kısa sürede değiştirilmesini öneriyoruz." },
          { en: "Approval of the drawings is required before production.", tr: "Üretimden önce çizimlerin onaylanması gereklidir." },
          { en: "Customers in Northern Europe tend to prefer heated windows.", tr: "Kuzey Avrupa'daki müşteriler ısıtmalı pencereleri tercih etme eğilimindedir." },
          { en: "To be honest, I'm not entirely sure that's true.", tr: "Açıkçası bunun doğru olduğundan tam emin değilim." }
        ]
      },
      cards: [
        { en: "It would appear that ...", tr: "Görünüşe göre ...", ex: "It would appear that the invoice contains an error." },
        { en: "seems to have + V3", tr: "...mış gibi görünüyor", ex: "The seal seems to have dried out." },
        { en: "tend to", tr: "... eğiliminde olmak", ex: "Prices tend to rise in winter." },
        { en: "We recommend that it be ...", tr: "...lmesini öneriyoruz", ex: "We recommend that the frame be inspected." },
        { en: "a slight discrepancy", tr: "küçük bir tutarsızlık", ex: "There seems to be a slight discrepancy in the figures." },
        { en: "to some extent", tr: "bir dereceye kadar", ex: "I agree with you to some extent." }
      ],
      exercises: [
        { type: "mcq", q: "We recommend that the damaged pane ___ as soon as possible.",
          options: ["replaces", "will be replaced", "be replaced", "replacing"], answer: 2,
          explain: "recommend that + özne + yalın fiil (subjunctive) → be replaced." },
        { type: "mcq", q: "It ___ that the cracks were caused by incorrect installation.",
          options: ["would appear", "appears to", "is appearing", "would appearing"], answer: 0,
          explain: "Temkinli ifade: It would appear that ..." },
        { type: "fill", q: "It is essential that every window ___ (have) a valid class certificate.",
          answers: ["have", "should have"], hint: "subjunctive",
          explain: "It is essential that + özne + yalın fiil: have (has değil)." },
        { type: "mcq", q: "Customers in Northern Europe ___ prefer heated bridge windows.",
          options: ["tend to", "tend", "are tending", "tend for"], answer: 0,
          explain: "tend to + yalın fiil = ... eğiliminde olmak." },
        { type: "fill", q: "The damage seems ___ (occur) during transport.",
          answers: ["to have occurred"],
          explain: "Geçmişe dair temkinli ifade: seem + to have + V3." },
        { type: "mcq", q: "Nominalisation: 'We decided to postpone the shipment.' →",
          options: ["The decision was made to postpone the shipment.", "We made decide to postpone the shipment.",
            "The deciding was postponing the shipment.", "Postponing decided the shipment."], answer: 0,
          explain: "decide → decision; resmi ve kişisiz anlatım." },
        { type: "order", answer: "It would appear that the invoice contains an error.",
          tr: "Görünüşe göre faturada bir hata var.",
          explain: "It would appear that + cümle: kibar, temkinli tespit." },
        { type: "match", pairs: [["approve", "approval"], ["deliver", "delivery"], ["install", "installation"],
          ["fail", "failure"], ["comply", "compliance"]],
          explain: "Fiil → isim (nominalisation)." },
        { type: "mcq", q: "Which reply to a customer is the most diplomatic?",
          options: ["Your drawing is wrong.", "There seems to be a slight discrepancy in the drawing.",
            "You made a mistake in the drawing.", "The drawing is totally wrong."], answer: 1,
          explain: "seems to be + slight → yumuşatılmış, diplomatik ifade." },
        { type: "listen", text: "There may be a slight delay in delivery.",
          tr: "Teslimatta küçük bir gecikme olabilir." },
        { type: "mcq", q: "Your friend wants to drive to Bodrum in August. You say: 'I ___ think the traffic might be quite heavy.'",
          options: ["would", "will", "am", "do be"], answer: 0,
          explain: "I would think ... = yumuşatılmış görüş bildirme." },
        { type: "fill", q: "The client insisted that the inspection ___ (carry out) by Lloyd's Register.",
          answers: ["be carried out", "should be carried out"],
          explain: "insist that + özne + (should) + be + V3 (subjunctive edilgen)." },
        { type: "mcq", q: "Which sentence uses hedging correctly?",
          options: ["This would seem to suggest that the sealant was not cured.", "This would seems to suggest that the sealant was not cured.",
            "This seems suggesting that the sealant was not cured.", "This would to seem suggest the sealant was not cured."], answer: 0,
          explain: "would + seem (yalın) + to suggest: çifte yumuşatma." }
      ]
    }
  ]
});
